### ISSUE TITLE
pip install qiskit-ignis should be pip install qiskit

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#100]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/15731369/53776271-915f5680-3ec3-11e9-86a1-34ca38235ba5.png">

**Comment by lerongil** [comment]
Noticed that too, wanted to confirm with Dave that it worked before updating this. Should be working now.

**Comment by carlosazaustre** [comment]
So the correct way is `pip install qiskit`, isn't it?

**Comment by lerongil** [comment]
yes, that's right
