### ISSUE TITLE
Update content and images on dark page

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#1011]

**Comment by JRussellHuffman** [comment]
All the finalized assets are here: https://ibm.box.com/s/nkc31044mdeul9wrzn1f0ahsa312xldd Not that we're still waiting on the 3rd video. But everything else is in place. All the copy in the figma is final too.

**Comment by delapuente** [comment]
Calling your attention on this @y4izus ⬆️

**Comment by delapuente** [comment]
Closed by #1013
