### ISSUE TITLE
Enhance accessibility for embedded video

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1018]
In order to keep with web accessibility standards, we need to ensure that our video components allow all users to have full control of such elements.

There's good documentation on one way to approach this, courtesy of [MDN](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia).

**Comment by korgan00** [comment]
I was reading that Article. It has some interesting things about video accessibility.
Some of our short videos have illustrative purposes as a substitution for a gif or an image (no sound, loop, and autoplay). For example, the scrolling section on the Metal page. Do we still need the controls on those videos?

**Comment by delapuente** [comment]
Usually, best results are achieved if you create a GIF, then use video. Using GIF is for reducing the color palette and the number of frames, then using video is for leveraging frame reuse from video compression techniques.

**Comment by techtolentino** [comment]
It looks like this was addressed long ago and there's no action needed. Our videos are essentially illustrative, so we won't need controls.
