### ISSUE TITLE
Center icon on Empty Events card (on mobile)

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1034]
We need to fix the centering position of the icon on mobile, for the empty Events state

![Screen Shot 2020-10-20 at 12 38 30 PM](https://user-images.githubusercontent.com/6276074/96629790-5779d880-12d1-11eb-83e4-94c396778d4d.png)

**Comment by korgan00** [comment]
The image is centered, the problem is the image itself.
I think it is for visual weight purposes. The triangle is slightly up.
@JRussellHuffman Can you upload a new SVG with the triangle centered?

**Comment by JRussellHuffman** [comment]
Try this one that doesn't have margins.
[warning.svg.zip](https://github.com/Qiskit/qiskit.org/files/5423471/warning.svg.zip)
