### ISSUE TITLE
Update references to python 3.5

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit.org#1046]
### Where is the problem?

Quick Start section on https://qiskit.org/

https://qiskit.org/documentation/install.html

### What is the problem?

Installation instructions list python 3.5+ as a requirement for Qiskit. Qiskit 0.22.0 is the last version to support python 3.5, so we should recommend python 3.6+.

### What would you expect?

Python 3.6+

**Comment by aryansi225** [comment]
Hi, Can I work on this.

**Comment by delapuente** [comment]
Go for it, @aryansi225
