### ISSUE TITLE
Graph state tool

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit.org#1050]
There is an interactive website being made that allows people to create and analyse graph states. It will also get some Qiskit integration (such as with [GraphState](https://qiskit.org/documentation/stubs/qiskit.circuit.library.GraphState.html#graphstate)).

I think qiskit.org could be a good home for this. Maybe via in qiskit.org/learn or a revived qiskit.org/experiments

@delapuente suggested I post this issue and tag @lerongil and @JRussellHuffman.

**Comment by DMillerIBM** [comment]
This is an early demo of the tool:

https://graphvis.uber.space/app/
Nutzername: graphvis
Passwort: Gr4phV!$

**Comment by delapuente** [comment]
New cases for reviving `/experiments` continue showing up. We really need to find a champion here.

**Comment by DMillerIBM** [comment]
Actually, I just started to work for IBM a few weeks ago. I do not know about qiskit/experiments.

We coded the tool for a paper in quantum information which we are writing up now.
It would be nice, if the tool was online when we upload the preprint such that we can put a link in the paper.

If we put it on qiskit/learn, I could write an introduction about graph states and which quantum properties can be inferred from the corresponding graph, etc.

We also consider performing some experiments for our paper. Perhaps this can be modified for qiskit/experiments

**Comment by DMillerIBM** [comment]
[This Github Repository](https://github.com/DMillerIBM/graph_visualization) comprises the Code for the `Graph State Visualization` application.

To deploy the code follow the instructions provided in the [README](https://github.com/DMillerIBM/graph_visualization/blob/master/README.md) file.
 
@delapuente @quantumjim @lerongil @JRussellHuffman You can accept the invites I sent to you to receive collaborator access to the repo.

**Comment by aasfaw** [comment]
This is awesome. Daniel, can you write a chapter on the qiskit textbook about your results for an undergraduate student audience, and then we can embed this tool within the textbook?

**Comment by DMillerIBM** [comment]
@aasfaw  Thanks a lot.

Yes, I would love to write such a chapter.

Currently, I am anyway working through the textbook to learn the qiskit programming language.

When I am finished with this, I will be able to write the new chapter about graph states and sector length distributions in the style of the textbook.

**Comment by y4izus** [comment]
This issue is no longer relevant, so I close it
