### ISSUE TITLE
[General UI] Dropdown arrow should be align on learn page

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#1056]
### Steps to reproduce the problem
Go to https://qiskit.org/learn/ with the mobile version

### What is the current behavior?

<img width="449" alt="Screen Shot 2020-10-29 at 16 57 13" src="https://user-images.githubusercontent.com/17231966/97598977-ce1c8180-1a07-11eb-9ac3-5f28c6ce1dca.png">

### What is the expected behavior?
Dropdown arrows should be aligned

**Comment by techtolentino** [comment]
After checking just now - I think this issues is still happening

**Comment by VicentePerezSoloviev** [comment]
If this issue is still open, I would like to be assigned to fix it. Thank you

**Comment by y4izus** [comment]
Yes @VicentePerezSoloviev , it is still open and you can work on it :) . Thank you very much!

**Comment by VicentePerezSoloviev** [comment]
Great, if you assign me the task, I start now to implement it

**Comment by pandasa123** [comment]
Learn page is [migrated](https://qiskit.org/learn/) now. We can close this issue
