### ISSUE TITLE
Use module store model instead of classic store model

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#1058]
We are using [classic store model](https://nuxtjs.org/guide/vuex-store/#classic-mode), but it's deprecated and will disappear with Nuxtjs 3. We have to change to the [module store model ](https://nuxtjs.org/guide/vuex-store/#modules-mode) to avoid problems when we move to the new Nuxtjs version

**Comment by eddybrando** [comment]
@y4izus both links point now to a 404 😕

**Comment by y4izus** [comment]
@eddybrando , the links are working again
