### ISSUE TITLE
Add Community Tab on header

### ISSUE THREAD

**Issue by carlosazaustre** [Qiskit/qiskit.org#106]
Create a Community tab on qiskit.org to hold items from all our community related initiatives (qiskit camp, contribution guidelines, roadmap, community groups, etc.)

**Comment by carlosazaustre** [comment]
@lerongil 
I'm working on the Community page. Here you have a Work in progress. I will need the copywriting for the sections, and if necessary something more, please let me know :)

![image](https://user-images.githubusercontent.com/650752/54272868-d13dd200-4584-11e9-89ca-ede82c0f7268.png)

**Comment by lerongil** [comment]
Thanks Carlos! I will get back to you with copy/images and (possibly) an updated format here.
