### ISSUE TITLE
Add a section in CONTRIBUTING.md about writing components

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1062]
Use it to explain how we try to meet Vue strongest recommendations, how we use different HTML tags, class-based components, common patterns like container > content, etc. Feel free to delegate in external content by linking.

**Comment by eddybrando** [comment]
I think that we can close this.

We try to follow the conventions and examples from the Nuxt documentation. Other than that, we've made some decisions during the years to adapt the repository to our needs. Given the not so high complexity of this codebase, I don't think that we need to explain in detail how we write components. A dev can make an educated guess by looking at the current components.

CC: @y4izus
