### ISSUE TITLE
Qiskit Metal text improvements

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1069]
### Steps to reproduce the problem
Got to qiskit.org/metal

### What is the current behavior?
This issue is to call out grammatical and spelling errors and feedback from a content specialist.

### What is the expected behavior?

Capitalize Python in 2 places and remove the comma after Simply
<img width="483" alt="Screen Shot 2020-10-16 at 1 09 56 PM" src="https://user-images.githubusercontent.com/7633881/97886003-b259f980-1ced-11eb-9005-a1b677c25355.png">

remove extra space after parens
<img width="487" alt="Screen Shot 2020-10-16 at 1 11 48 PM" src="https://user-images.githubusercontent.com/7633881/97886032-ba199e00-1ced-11eb-8581-e6cc17757282.png">

Remove the word “to”
<img width="484" alt="Screen Shot 2020-10-16 at 1 13 09 PM" src="https://user-images.githubusercontent.com/7633881/97886059-c1d94280-1ced-11eb-9a62-68fad15ed604.png">

“Metal helps bridge” or “Metal bridges”.  Change ampersands to and.  Capitalize Metal.
<img width="566" alt="Screen Shot 2020-10-16 at 1 14 47 PM" src="https://user-images.githubusercontent.com/7633881/97886088-cc93d780-1ced-11eb-95ea-21a807f4f1d6.png">

“and that we are developing” is awkward
<img width="580" alt="Screen Shot 2020-10-16 at 1 16 49 PM" src="https://user-images.githubusercontent.com/7633881/97886110-d4537c00-1ced-11eb-8e41-69d373819ce7.png">

comma after teaching
<img width="503" alt="Screen Shot 2020-10-16 at 1 18 44 PM" src="https://user-images.githubusercontent.com/7633881/97886146-dc132080-1ced-11eb-85d2-b023716f0f97.png">

Something is missing in this sentence…
<img width="500" alt="Screen Shot 2020-10-16 at 1 19 48 PM" src="https://user-images.githubusercontent.com/7633881/97886177-e46b5b80-1ced-11eb-8cce-f914176d0001.png">

**Comment by korgan00** [comment]
@JRussellHuffman I need a solution for the “and that we are developing” and the last one (something is missing). You can check the other changes in PR #1081

**Comment by JRussellHuffman** [comment]
@korgan00 For the “and that we are developing” sentence:

> "Metal utilizes quantization methods and techniques from both the community and our own development."

For the "something is missing" sentence:

> "We hope to form this software into something that is usable by superconducting quantum hardware designers across industry and academia, and perhaps even for other qubit architectures."

**Comment by JRussellHuffman** [comment]
^ copy past the above to the PR as well.
