### ISSUE TITLE
Create a header web component

### ISSUE THREAD

**Issue by carlosazaustre** [Qiskit/qiskit.org#107]
In order to reuse in Documentation website also.

**Comment by lerongil** [comment]
Seems like we can close this issue @delapuente

**Comment by delapuente** [comment]
This will be partially solved when merging #258. It will be still valuable to keep documentation header in sync. Let's keep it open.

**Comment by lerongil** [comment]
@delapuente Is this still relevant?

**Comment by delapuente** [comment]
Nope. Thanks for the heads up. Closing.
