### ISSUE TITLE
Stop using travis CI

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit.org#1090]
With travis's recent billing changes that went into effect this month: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing we're rapidly approach the qiskit project quota for the free trial accounts. This is problematic as both retworkx (for non-x86 jobs) and ibmq provider (for networking reasons) both rely on travis for their CI. We don't want to hit that quota and block development/testing on those projects. So we should try to remove our travis usage for things that dwe can run elsewhere to prioritize access to projects that really need it.

Github actions provides a good alternative that has all the necessary capabilities and native integration with github so we should migrate our CI jobs to use that instead.

**Comment by delapuente** [comment]
Thank you @mtreinish for the notice.

**Comment by vabarbosa** [comment]
@delapuente @y4izus 

draft PR https://github.com/Qiskit/qiskit.org/pull/1127 has been submitted to replace Travis CI with GitHub Actions.

before the PR can be merged, the environment variables defined in the [Travis CI settings](https://www.travis-ci.com/github/Qiskit/qiskit.org/settings) should be added to the [GitHub secrets](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization) so they can be accessed in the GitHub Actions workflow. 

unfortunately, i do not have access to create the secrets nor do i know the values of the environments variables. i am not sure if all the environment variables are needed but in any case, i will need assistance adding those that are still required.

**Comment by delapuente** [comment]
@mtreinish this is done. Thank you, @vabarbosa!
