### ISSUE TITLE
U2 is a depreciated gate and H will soon be a basis gate

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#1092]
The following graphic will soon be obsolete:

<img width="626" alt="Screen Shot 2020-11-09 at 06 35 19" src="https://user-images.githubusercontent.com/1249193/98536437-d2da0480-2255-11eb-9d84-2c9cc6d52b13.png">U2

**Comment by delapuente** [comment]
Thank you for the heads up! Can you provide an estimated date for when it will become obsolete?

**Comment by delapuente** [comment]
@JRussellHuffman what do you think?

**Comment by y4izus** [comment]
We don't have that section anymore, so we can close this issue
