### ISSUE TITLE
404 page design

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1093]
We should have simple page to display site visitors when they hit a dead end. 

**Open questions:**
Are there more errors that just 404 we should design for? 
Any other "empty states" that should be desigend for?

**Comment by y4izus** [comment]
@JRussellHuffman , since we already have a 404 page on platypus, should we close this issue?

**Comment by JRussellHuffman** [comment]
Yep. and we have other issues to cover the other domains. closing.
