### ISSUE TITLE
Document changes with an automated changelog.md file

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1095]
**Is your feature request related to a problem? Please describe.**

Currently we don't have a **changelog.md** file that documents notable changes to this project.

Here is a good explanation about the importance of a changelog file ([source](https://keepachangelog.com/en/1.0.0/)):

> What is a changelog?
> A changelog is a file which contains a curated, chronologically ordered list of notable changes for each version of a project.
> 
> Why keep a changelog?
> To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.
> 
> Who needs a changelog?
> People do. Whether consumers or developers, the end users of software are human beings who care about what's in the software. When the software changes, people want to know why and how.

---

**Describe the solution you'd like**

Changelog files can be easily automated with projects like [standard-version](https://github.com/conventional-changelog/standard-version), although it would require to introduce [semantic versioning](https://semver.org/) to this project first (see #1096).

---

Related to #1096

**Comment by y4izus** [comment]
This issue is no longer relevant, so I close it
