### ISSUE TITLE
[General UI] Remove the width constrains for all the titles.

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#1104]
As mentioned in #1097, we can remove the width constrains a check what titles are affected and how.
@JRussellHuffman also proposed several times to check all the titles with the typewriter effect that creates new lines pushing content.

**Comment by delapuente** [comment]
Although the change may improve the user experience, it does not have a direct impact on code quality.

**Comment by techtolentino** [comment]
[This issue](https://github.com/Qiskit/qiskit.org/issues/920) could be related or might be handled in the same effort

**Comment by korgan00** [comment]
Is this solved?

**Comment by eddybrando** [comment]
@JRussellHuffman, would you say this is still an issue?

**Comment by JRussellHuffman** [comment]
I think the jumpiness of the typewriter effect is a bug that has been opened and closed on a handful of occasions. It would be good to fix for all the page once and for all.
