### ISSUE TITLE
Implement accessibility of typewriter effect

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#1105]
Using investigation on #921, implement accessibility based on the mentioned [article](https://dev.to/savvasstephnds/the-problem-with-the-typewriter-effect-and-how-to-fix-it-2731),
We should use the ARIA attributes to create an understandable message for text readers.
It could also be a good option to ignore the whole typewriter effect using `aria-hidden` and put the `aria-label` into the titles.

**Comment by delapuente** [comment]
Although related to our codebase, this is simply a task for adding an accessibility feature and not improving the quality of code.

**Comment by y4izus** [comment]
We are not gonna add more features to this repo so we can close this issue
