### ISSUE TITLE
Add Slack link to advocate card

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1110]

**Comment by korgan00** [comment]
I think it is already done at the [AdvocateCard](https://github.com/korgan00/qiskit.org/blob/de04f39a3a6b630420fcd73a6f8fafdea1ba9839/components/advocates/AdvocateCard.vue) line 14-16

**Comment by techtolentino** [comment]
@korgan00 - a lot of the code is there already yes, but we need to make slight updates...
