### ISSUE TITLE
Qiskit Advocate page post-mvp enhancement: sticky filtering

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1115]
It would be a more ideal experience if the region filter component next to the advocate cards was sticky in the same way the overview page navigation is sticky because of the amount of the advocate cards.
The same applies to the component on the learn page and events page. I think every instance of this component should be stikcy.

**Comment by y4izus** [comment]
This issue is no longer relevant, so I close it
