### ISSUE TITLE
Qiskit events title text wrapping

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1126]
### Steps to reproduce the problem
Go to https://qiskit.org/events. I see the issue on both Chrome and Firefox

### What is the current behavior?
Title text doesn't wrap. 
![Screen Shot 2020-11-17 at 3 58 22 PM](https://user-images.githubusercontent.com/7633881/99455765-e9cfc500-28ed-11eb-80e3-a570e93de6e1.png)

### What is the expected behavior?
The text needs to stay within the card, wrapping to a second line if necessary

**Comment by delapuente** [comment]
This is a dup of #1124. Closing.
