### ISSUE TITLE
Events cards special images

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#1134]
Looking at the events page, I noticed that we have a bunch of Seminar Series events, and their images don't fit into our design.
![2020-11-20 18_40_39-Qiskit Events](https://user-images.githubusercontent.com/4138279/99831794-eb082880-2b5f-11eb-9c03-8a716d7fe297.png)

I propose to make a specialized card for this series. Instead of an image, We can use three main elements, the background, the title, and the "Qiskit live" pill. This will fit and scale with the page and also improve text readability.

**Comment by y4izus** [comment]
Seminar series now have the picture of the speaker, so we can close this issue
