### ISSUE TITLE
Qiskit logo broken on the textbook

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1135]
### Steps to reproduce the problem

Go to https://qiskit.org/textbook/preface.html

### What is the current behavior?
Browsers shows a broken image icon.
<img width="541" alt="Screen Shot 2020-11-20 at 3 54 19 PM" src="https://user-images.githubusercontent.com/7633881/99853479-a7ee8b00-2b48-11eb-9392-63f8650cda78.png">

### What is the expected behavior?
The header is currently out of date on the textbook anyway. Can we take this opportunity to update the header to match the rest of Qiskit.org?

**Comment by vabarbosa** [comment]
related issue was opened in textbook: https://github.com/qiskit-community/qiskit-textbook/issues/837
a PR (https://github.com/qiskit-community/qiskit-textbook/pull/838) was submitted to resolve the broken image in textbook.
