### ISSUE TITLE
Qiskit.org is showing old events as upcoming

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1138]
### Steps to reproduce the problem
1. Visit https://qiskit.org/events

### What is the current behavior?
Qiskit Global Summer School is shown and it is an old event.
<img width="1108" alt="Screen Shot 2020-11-23 at 10 25 17 AM" src="https://user-images.githubusercontent.com/757942/100001774-a06df280-2d91-11eb-819c-6d364a4c402e.png">

### What is the expected behavior?
The current line-up seminars show up.

**Comment by delapuente** [comment]
Possibly related or a dup of #872

**Comment by lerongil** [comment]
this probably can be closed now, right?

**Comment by delapuente** [comment]
Right. This seems solved.
