### ISSUE TITLE
Content is pushed down and up when header changes making links hard to reach

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1139]
### Steps to reproduce the problem
1. Visit https://qiskit.org/events
2. Scroll to the event list
3. Wait for the header to change as a result of the typewriter effect.

### What is the current behavior?
![ezgif-6-2bc93ed5efc3](https://user-images.githubusercontent.com/757942/100002609-d19af280-2d92-11eb-8afb-dd20e98d9d5f.gif)

### What is the expected behavior?
The content does not change place regardless of the effects happening in the header.

**Comment by delapuente** [comment]
Possibly related or a dup of #872

**Comment by y4izus** [comment]
I think this is a dup of #920 (in the title says "on mobile", but on the discussion, we can read that this behavior is not just on mobile)

If you agree, we can close this issue and add the bug label to the other one to give it a higher priority

**Comment by delapuente** [comment]
Yes. Mark it as dup.

**Comment by y4izus** [comment]
Closed because it's a dup of #920
