### ISSUE TITLE
Update Qiskit Documentation Header

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1176]
Qiskit.org/documentation was recently updated with a new theme. This theme looks similar to the rest of qiskit.org but introduces a new header. This should be resolved by the end of the year if time permits.

**Comment by lerongil** [comment]
As part of #1321 1321

**Comment by delapuente** [comment]
Seems like a dup of #1384 

Can you confirm @lerongil ?

**Comment by techtolentino** [comment]
Closing for now - will revisit when needed.
