### ISSUE TITLE
Iterate on content for quantum volume

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1187]

**Comment by JRussellHuffman** [comment]
This is done for the most part. I suspect a few edits will continue to trickle in, but if anything substantial pops up, I will make a new issue to track it. final prototype here: https://www.figma.com/proto/QicY1yBT9hGP2Rln4Wu3Jn/915-quantum-volume?node-id=1125%3A40&viewport=-1104%2C-1253%2C0.3001520037651062&scaling=min-zoom
