### ISSUE TITLE
Implement conversion pipeline of notebook to mathigon

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1189]

**Comment by vabarbosa** [comment]
- Jupyter Notebook conversion to Mathigon format: https://github.com/Qiskit/qiskit.org/issues/1342
- implement progress tracking: https://github.com/Qiskit/qiskit.org/issues/1344
- integrate Vue components/widget: https://github.com/Qiskit/qiskit.org/issues/1343
