### ISSUE TITLE
home page illustration update

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1190]
### Steps to reproduce the problem
go to the qiskit.org home page

### What is the current behavior?
the illustrations are slightly out of data, or preliminary version.

### What is the expected behavior?
The 3 illustrations on the home page are a bit out of date. Let's update them to match the ones in Figma. Specifically, the image under "Access to Circuits" has a version with corrected colors. I think the images under "Noise Mitigation" would be better suited if replaced with the noise mitigation image from the overview page. All of which are reflected in the figma file.

**Comment by y4izus** [comment]
The "Noise Mitigation" image has been already updated. Right now this is how the mosaic on the home page looks:
<img width="1020" alt="Screen Shot 2021-02-15 at 11 20 48" src="https://user-images.githubusercontent.com/17231966/107934059-dc26eb80-6f7f-11eb-9c98-146265e8d72e.png">

And this is how the Figma file looks:
<img width="604" alt="Screen Shot 2021-02-15 at 11 21 17" src="https://user-images.githubusercontent.com/17231966/107934107-ed6ff800-6f7f-11eb-8184-cc9805a87266.png">

So, I think the only image that is still out of date is the one under "Access to circuits". @JRussellHuffman , do you agree or there is something else I'm missing?
