### ISSUE TITLE
Design links for storybook

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1209]
We want to link the designed components from figma to Storybook. 

@techtolentino and @eddybrando let me know what specifics you need. for now, I'm going to drop links here.

**Comment by JRussellHuffman** [comment]
buttons: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=1%3A2

Code blocks: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=1%3A28

accordions: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=3%3A0

tabs: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=5%3A145

cards: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=6%3A86

dropdowns: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=9%3A111

pictograms: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=5%3A1452

Typewriter: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=5%3A38

Selectors: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=9%3A2530

large type: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=5%3A15

medium type: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=9%3A35

small type: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=9%3A78

**Comment by JRussellHuffman** [comment]
Related to #1155

**Comment by eddybrando** [comment]
Awesome! Thanks a lot @JRussellHuffman 🙂

I'll ask for more links whenever I see fit, but this should be a great start.
