### ISSUE TITLE
Update maintainers in README.md

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1216]
The **Maintainers** section in the **README.md** file is outdated.

Referencing the [newly updated **CODEOWNERS** file](https://github.com/Qiskit/qiskit.org/pull/1202), the list should include:

- @delapuente
- @y4izus
- @techtolentino
- @korgan00
- @eddybrando
- @abdonrd

Probably also:

- @lerongil (advocates)
- @aasfaw (advocates)
- @justjosie (events)
- @KallieFerguson (events)

**Comment by 96RadhikaJadhav** [comment]
@eddybrando  Could you please assign this issue to me?

**Comment by eddybrando** [comment]
> @eddybrando Could you please assign this issue to me?

Of course! Thank you very much @96RadhikaJadhav! 🙂

**Comment by 96RadhikaJadhav** [comment]
@eddybrando  A little help here. I'm not getting from where to get the info of "alt" parameter in the maintainers sections?

**Comment by eddybrando** [comment]
You're right @96RadhikaJadhav, that information wasn't available to you, I'm sorry.

I just created the PR since I believe that is more time efficient in this specific case.

Nevertheless, I would like to thank you very much for your help and would like to encourage you to keep contributing to this and other open source projects. 🙂

Thanks!
