### ISSUE TITLE
[General UI] The icon in the landing CTA should be an arrow

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1228]
### Steps to reproduce the problem

1. Navigate to qiskit.org
2. Notice the icon of the "Get started" CTA

### What is the current behavior?

The icon is the one indicating a navigation outside qiskit.org.

### What is the expected behavior?

Since `qiskit.org/documentation/install.html` is under qiskit.org, the icon should be an arrow.

**Comment by delapuente** [comment]
There are three projects under qiskit.org, one is this Nuxt site, living under `qiskit.org/`. The other two, the documentation and the textbook are static sites and do not belong to this project. Trying to navigate to them using the Vue.js router breaks the navigation. We need to use the native navigation provided by the `a` HTML element.

Our `AppLink` component, encapsulates this behavior. It has mechanisms to determine when using `a` or `nuxt-link` components. If passed an absolute URL, the component immediately assumes we want to navigate outside the domain. This is leveraged in PR #1227 but introduces a regression making the component to display the incorrect icon.

Perhaps we should make the Nuxt project aware about the static sites and let it know those navigations to `/documentation` and `/textbook` should rely on the native HTML navigation regardless if we want it to open in the same or a different tab.

**Comment by JRussellHuffman** [comment]
To add to this, I would prefer if both links to documentation and textbook open in the same tab instead of opening a new tab. To our users, they won't know its a different site with a different structure. Particularly on the textbook, opening new tabs could result in several tabs open unknowingly with our given navigation.

**Comment by y4izus** [comment]
Per offline conversations, all the links that contains `qiskit.org` should have the arrow.
