### ISSUE TITLE
Fix broken link for tutorials 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#125]
We need to update the link for the tutorials

**Comment by carlosazaustre** [comment]
Closes with the following [PR in Qiskit repo](https://github.com/Qiskit/qiskit/pull/258)

**Comment by lerongil** [comment]
This still seems to be broken on mobile and in some cases on desktop too. I checked with chrome and safari (desktop) and it works but on safari mobile it returns a 404.

@aasfaw @asier have encountered similar experiences.
