### ISSUE TITLE
Update individual event pages with new design 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1263]

**Comment by JRussellHuffman** [comment]
The most recent version of the individual event pages is at the bottom here: https://www.figma.com/file/N2pCxg9COPfh2bKHNdxNcI/502-community-carbon?node-id=146%3A30184

Note that these designs are only for the Qiskit camps and should probably be revisited. Any other individual event pages needs to be designed

**Comment by JRussellHuffman** [comment]
created a figma file updated designs here: https://www.figma.com/file/nqFBhDOUq6Dknbw9pM92AE/1263-individual-event-pages?node-id=0%3A1

**Comment by lerongil** [comment]
Thanks Russell. Closing this!
