### ISSUE TITLE
Use Carbon CSS as Sass modules

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1290]
### Sass modules

`@import`s in Sass have some limitations that are being solved by using **Sass modules** and the `@use` and `@forward` rules.

Here is some information about Sass modules:

- https://sass-lang.com/blog/the-module-system-is-launched
- https://css-tricks.com/introducing-sass-modules/

Some main issues with the current `@import` rules in Sass (from [css-tricks.com](https://css-tricks.com/introducing-sass-modules/)):

- `@import` is also a CSS feature, and the differences can be confusing
- If you `@import` the same file multiple times, it can slow down compilation, cause override conflicts, and generate duplicate output.
- Everything is in the global namespace, including third-party packages – so my `color()` function might override your existing `color()` function, or vice versa.
- When you use a function like `color()`. it’s impossible to know exactly where it was defined. Which `@import` does it come from?

### Why is it important for us?

The migration to **Sass modules** could improve our code quality and DX, and optimise our final CSS bundles.

Also, `@import` will be eventually deprecated in Sass.

### Why now?

Recently, the Carbon library has migrated to **Sass modules** with changes like this: https://github.com/carbon-design-system/carbon/pull/7395.

**Comment by y4izus** [comment]
This is already resolved, we can close it
