### ISSUE TITLE
a link to the FAQ. 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#13]
We would like have a link to both FAQ on the landing page somewhere. 

Quantum Computing FAQ https://quantumexperience.ng.bluemix.net/qx/tutorial?sectionId=full-user-guide&page=000-FAQ~2F000-Frequently_Asked_Questions

Quantum Program FAQ
https://github.com/QISKit/qiskit-sdk-py/wiki/QISKit-Troubleshooting

But we should maybe change the name if QISKit-Troubleshooting to QISKit-FAQ.

**Comment by lbello** [comment]
This issue is related to https://github.com/QISKit/qiskit-sdk-py/issues/240

**Comment by francabrera** [comment]
In the landing page? wouldn't it make more sense to add them on the Documentation site?

**Comment by jaygambetta** [comment]
The document should be more focused on how to use qiskit. This would be more for quick questions that many people ask.

**Comment by abdonrd** [comment]
Closing old issue after the website update.
