### ISSUE TITLE
Brainstorming and prototyping learning paths in textbook

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1333]
Learning paths as a concept has been floated for quite a while now, but it's mostly been hypothetical and an agreed upon vision has not be fully established (or at least not written down) for what a learning path is. This issue is to brainstorm what learning paths are at a high level as well as to think through the content and user experience of learning paths.

**Comment by JRussellHuffman** [comment]
Figma file for this piece of work is here: https://www.figma.com/file/5WCqX5D5r2PVYnv0FpN8RN/1333-Learning-Path-explorations?node-id=78%3A2814

This work is ongoing but in terms of spelling out the high level vision, this work is done, so I am closing the issue.
