### ISSUE TITLE
Qiskit Docs tracking is no longer working

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit.org#1340]
As a Qiskit Documentation localization technical lead, I would want to see the page traffic in the Qiskit Docs. This further extends us to predict the language that user prefers to read the documentation in. 

Further to the conversation with @nonhermitian offline, it was blocking the language selector button 

![Screenshot from 2020-11-06 06-51-20](https://user-images.githubusercontent.com/11485594/100652652-3915ec80-3315-11eb-979e-5dd2924998c9.png)

But we need a tracking mechanism to get more info on the page traffic.

[qiskit.org](https://qiskit.org) uses Segment for tracking. (@delapuente please add your comments on this issue)

**Comment by delapuente** [comment]
PR Qiskit/qiskit_sphinx_theme#23 changes the location of the language selector and so, this functionality can be reenabled.

**Comment by nonhermitian** [comment]
The point of removing it was not really the overlap but that we really do not need IBM cookie tracking in an open source projects docs. A lighter solution should be found.

**Comment by delapuente** [comment]
@nonhermitian @SooluThomas did you agree on what lighter solution you want to implement? In lack of a better option, I would recommend adding the IBM one.

**Comment by nonhermitian** [comment]
Google analytics is directly supported in the theme via the `'analytics_id'` option.

**Comment by SooluThomas** [comment]
@delapuente @nonhermitian I'm okay with either. In my opinion it is very important to get the data of user demographics which can help the Documentation Localization team to filter requests for adding new languages.

**Comment by SooluThomas** [comment]
Closing this as tracking is now available. Thanks to @javabster and team!!
