### ISSUE TITLE
Consider adding code snippets on website

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#1356]
Typically websites like this have code snippets at show users how to accomplish some small but meaningful task.  Qiksit.org has none.  Prior art includes:

https://www.tensorflow.org/overview/

https://pytorch.org/features/

https://quantumai.google/cirq

**Comment by delapuente** [comment]
Changing the title to make clear it is a request.

**Comment by pandasa123** [comment]
We have a small example of creating and running a circuit on the Qiskit.org homepage

<img width="1550" alt="Screenshot 2022-06-21 at 16 02 59" src="https://user-images.githubusercontent.com/6241840/174887709-29030482-08a8-430d-8eee-4e0a572f0f14.png">

This issue can be closed
