### ISSUE TITLE
[Lean Page Content] Qiskit tutorials listed under "Advanced" learning resources

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#1357]
The Qiskit tutorials are listed as "advanced" but then link out to a notebook that says "Basics" because it is basic.

**Comment by delapuente** [comment]
Labeling as a bug to highlight its importance since it is confusing.

**Comment by techtolentino** [comment]
This is no longer an issue since the Learn page has been redesigned.

The feature mentioned here has been removed altogether.
