### ISSUE TITLE
Raise the visibility of the translated docs

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit.org#1364]
Who are we building this for?

As a visitor of the Qiskit Docs website, I don't easily know that the documentation is available in languages other than English.
Currently the language selector button is placed on the bottom right which IMO is not really promoting the translated docs. Other open source documentations have their language selector tool somewhere on the top (for example [TensorFlow](https://www.tensorflow.org/api_docs), [Python](https://docs.python.org/3/)) and some of them change the docs language automatically based on geolocation.

“Wants to”

Raise visibility of the translated docs

“So that”:

We can widen the Qiskit community.

**Comment by JRussellHuffman** [comment]
In the design refresh for the documentation, the translation options are given more prominence in the UI being a part of the side navigation, above the footer (screenshot below). Hopefully this will satisfy this user story. I'm not sure when this will get into development, but it's on our radar.
![Main Page-1056px-Breakpoint-16 column](https://user-images.githubusercontent.com/7633881/107059737-c9e8c880-679b-11eb-92f4-f5897617da73.png)

**Comment by delapuente** [comment]
Thank you @JRussellHuffman. I took that into consideration creating a quick fix for this bug, given our resource restrictions. The style is not there yet but the design served as a guide for it. You can take a look at some screenshots at Qiskit/qiskit_sphinx_theme#23
