### ISSUE TITLE
Update background grid to carbon color

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1366]
The background grid/metal grid currently uses #e1e1e2, but should be changed to #DDE1E6, which is carbon's cool-gray-20. This update needs to happen in the design files as well as the live version.

**Comment by eddybrando** [comment]
Should be closed with #1679

**Comment by y4izus** [comment]
@JRussellHuffman this issue has been close automatically with the PR. The design part is finished or should I reopen the issue?

**Comment by JRussellHuffman** [comment]
Design part is finished in the components and will be migrated to the main qiskit.org file shortly. You can keep it closed.
