### ISSUE TITLE
Drag and Drop code interaction for QV

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1379]

**Comment by JRussellHuffman** [comment]
Screenshot of the interaction for this issue

<img width="767" alt="Screen Shot 2021-02-08 at 1 09 15 PM" src="https://user-images.githubusercontent.com/7633881/107269189-d9237c80-6a0e-11eb-97aa-4476865ae3dc.png">

**Comment by vabarbosa** [comment]
@korgan00 i am closing this as it has been available in the qv page for a couple weeks now.
please re-open if you are still working on it and i missed something
