### ISSUE TITLE
Mirror qiskit.org menu in sphinx theme

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1384]

**Comment by eddybrando** [comment]
The PR for this issue: https://github.com/Qiskit/qiskit_sphinx_theme/pull/22

**Comment by delapuente** [comment]
Holding this until we can realign with the documentation team.

**Comment by delapuente** [comment]
Short-term collaborations with the documentation team have been deprioritized. Moving it back to the backlog.

**Comment by y4izus** [comment]
We already have a web component with the top menu that is being shared across qiskit.org and qiskit.org/documentation, so we can close this issue
