### ISSUE TITLE
Learning Path Wireframes

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1385]
This is a follow up to #1333 to start wire framing the interactions around learning paths based on the IA laid in that issue.

**Comment by JRussellHuffman** [comment]
Wireframes are made and a prototype is here: https://www.figma.com/proto/EPP103zwRkZwiG3x1emEHc/1385-learning-path-wireframes?node-id=4%3A1&viewport=652%2C570%2C0.2320360541343689&scaling=min-zoom

That said, the prototype is still mostly empty as the content continues to develop, but hopefully this will serve as a good skeleton as we continue to design the learning path itself.

**Comment by lerongil** [comment]
Thanks Russell. This looks good. I'm opening up a new issue called Learning Path Content to encompass the completion of the content of the introductory course.
