### ISSUE TITLE
 Redo medium.com/Qiskit banner image

### ISSUE THREAD

**Issue by ryanfmandelbaum** [Qiskit/qiskit.org#1402]
At present, the medium.com/qiskit blog's banner image doesn't align with the rest of the Qiskit imagery, such as the imagery that appears on the QIskit website. I'd appreciate if the design team can give it a facelift.

Requirements here: https://medium.com/blogging-guide/medium-publication-header-3de12f8acada

**Comment by JRussellHuffman** [comment]
Done and delivered. closing
