### ISSUE TITLE
Design end to end beta experience for project platypus

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1421]

**Comment by JRussellHuffman** [comment]
End to end beta clickable prototype is here: https://www.figma.com/proto/kt2YyAApLBGSlSqJ6dXFqa/1421-platypus-prototype?node-id=40%3A107&viewport=1534%2C-96%2C0.17211852967739105&scaling=min-zoom. For design, it is done and end development

**Comment by delapuente** [comment]
Can we close this?

**Comment by JRussellHuffman** [comment]
Closing.
