### ISSUE TITLE
Modify robots.txt file to ensure the page is invisible

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1440]

**Comment by techtolentino** [comment]
@vabarbosa - this is done, yes?

**Comment by vabarbosa** [comment]
@techtolentino 
for platypus `robots.txt` has been added (https://github.com/Qiskit/qiskit.org/issues/1450) so none of its pages are allowed.
however, i think for `qiskit.org`, it still needs to be updated to not include the textbook demo/landinpg page for learning paths.

**Comment by y4izus** [comment]
We added `disallow textbook-*` to the `robots.txt`, it's mean that every page under `/textbook-*` won't be indexed. We have all the new demo pages under this path, so, from our side, this task is completed too :). I close it
