### ISSUE TITLE
Learning Path Content

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1487]
For the updated textbook, a new set of content is needed to give users the ability too choose paths that best fits their needs. In this case, the issue is related to the completion of the content for the introductory course.

**Comment by JRussellHuffman** [comment]
Currently working on pages 3&4 of the learning path, which has it's own issue #1497 .

**Comment by lerongil** [comment]
Let's close this one given the scope can be narrowed.
