### ISSUE TITLE
fix the broken link to link to the new index.ipynb in master

### ISSUE THREAD

**Issue by jaygambetta** [QISKit/qiskit.org#15]
https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/stable/index.ipynb does not work with the rework. Could you link to the index in the master and then the download as a zip should work. I think we should make it more visible on the notebook so let me know if you have ideas

**Comment by jaygambetta** [comment]
https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/master/index.ipynb is the link.

**Comment by francabrera** [comment]
Fixed on https://github.com/QISKit/qiskit.org/commit/09e75608b3bfeff73c3b83e30c9ab3f853923f04
