### ISSUE TITLE
Create reusable definitions of segments actions' names for tracking

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1511]
The tracking segment actions consist of long strings which can be broken down into reusable pieces in the form of constants.

This will help with future maintenance as well as providing a general overview of the labels we're using across the project.

**Comment by eddybrando** [comment]
This issue required a more in-depth analysis of the way we could track event data.

Here are the results of that analysis:

### What are we currently tracking with `action`?

When tracking events, Segment allows us to pass relevant data in the form of **properties** ([Segment spec: Track](https://segment.com/docs/connections/spec/track/)).

For the "CTA Clicked" event we’re sending a property named `CTA`, which contains the data that we call `action` in our codebase.

The content of `action` -and thus the content of the `CTA` property- is a string that aims to describe the CTA.

### How are we structuring the content of `action` / the `CTA` property?

We’re currently sending this data in two different ways:

1. Unstructured (Examples: `"Get started"`, `"Release notes"`)
2. Structured (Examples: `"events-summer-school > header > register"`, `"physics-of-computation > header > register"`)

### Issues with our current implementation

There are a couple of problems that I could identify with our current way of sending tracked events' data via `action`/ the `CTA` property to Segment:

- **Data structure inconsistency:** We're sending the string both structured and unstructured. By not following one standard, we end up with a mixed structure in our data, which might make data analysis harder.
![Screenshot 2021-06-16 at 12 40 13](https://user-images.githubusercontent.com/22047320/122204956-00e48e80-cea0-11eb-815a-c5d680d7b6fc.png)
- **Multiple information data within one property:** We're sending multiple information types as one string instead of passing multiple properties. By doing this, we might make data analysis harder, since we would need to create complex filters to extract information pieces from one single string, instead of having multiple properties that would allow us to use simple filters and matching functionalities. ([Segment spec: Properties](https://segment.com/docs/connections/spec/track/#properties))
- **Redundant data:** We're sending the path context within our structured `action` string (for example: `physics-of-computation`. This is already available in Amplitude for each event via the `path` property (for example: `events/physics-of-computation`).
![Screenshot 2021-06-16 at 12 47 33](https://user-images.githubusercontent.com/22047320/122205876-05f60d80-cea1-11eb-92f3-f43e551cf330.png)

### Suggested next steps

1. Agree on a structure for the properties sent to Segment for CTAs.
Proposal:
```typescript
interface CtaEventProperties {
  CTA: string
  location: string
}

// Example: Instead of `CTA: 'physics-of-computation > header > register'`

const ctaEventProperties: CtaEventProperties = {
  CTA: 'register',
  location: 'header'
}

segment.trackEvent('CTA Clicked', ctaEventProperties)
```
2. Document the agreed upon structure.
3. Apply that structure to the current CTA events tracking.
4. Evaluate if some of the data (like the possible values for the `location` property) might be defined somewhere centrally to generate some kind of benefit.

**Comment by delapuente** [comment]
I'd love to hear from @lerongil but I share the same opinion as @eddybrando. Also, from an implementation perspective, the way we are including the path context couple us to the path, making changing CTA's location harder to alter.

**Comment by lerongil** [comment]
@eddybrando your suggestion seems to be ideal. When building dashboards, I would search for the specific CTA (i.e. register) and so using `CTA: 'physics-of-computation > header > register'` is not as ideal as   CTA: 'register',  location: 'header'
