### ISSUE TITLE
Art for Qiskit Dev Cert Blog

### ISSUE THREAD

**Issue by ryanfmandelbaum** [Qiskit/qiskit.org#1529]
Publishing 3/29, we're announcing our Qiskit developer certification. I'll be writing a blog about it. I think it would be a nice opportunity to create some art assets for a blog and to potentially use when talking about the certification from the Qiskit voice. Specifically looking for something that feels like quantum software - imagery incorporating circuits, perhaps, in the usual qiskit art style.

**Comment by JRussellHuffman** [comment]
Final artwork below. closing.
![software](https://user-images.githubusercontent.com/7633881/112548036-9aad0b80-8d89-11eb-80fa-5caa0dfd446e.png)
