### ISSUE TITLE
Update Platypus page nav buttons w/ qiskit CTAs

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1535]
In Platypus, part of the page navigation uses buttons that need to be updated to match Qiskit's brand.

Buttons like these should be replaced with Qiskitorg CTA components (`AppCTA`s or `BasicLink`s)
![image (1)](https://user-images.githubusercontent.com/6276074/111184761-e7693900-8576-11eb-8894-bb0b21d353fb.png)

**Comment by vabarbosa** [comment]
thanks @techtolentino
