### ISSUE TITLE
Add the Qiskit Virtual Event Guide pdf to the static folder

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#1564]
The event's team need a URL to have the Qiskit Virtual Event Guide ready to share. The pdf is still in review, we should add it to the web when it is ready

**Comment by delapuente** [comment]
Any update regarding this?

**Comment by y4izus** [comment]
@KallieFerguson , do you have the pdf updated?

**Comment by delapuente** [comment]
Deprioritizing due to lack of response.

**Comment by y4izus** [comment]
The Qiskit Virtual Event already finished, so we can close this issue
