### ISSUE TITLE
❤️ Refactor CSS to use Carbon grid's 16 column layout system

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1567]
We currently have UI designs that are based on the 16 column layout variant of the Carbon grid system, but the implementation is not always matching those designs.

Further, we aren't leveraging Carbon's build-in grid system classes.

This refactor aims to use Carbon's build-in classes to adapt the design to the 16 column layout.

**Comment by y4izus** [comment]
We have tried the Carbon grid on the blockbuster page and it help us with the development. Also it makes the code cleaner
