### ISSUE TITLE
Link in Documention error 400

### ISSUE THREAD

**Issue by MannimMond86** [Qiskit/qiskit.org#1575]
### Where is the problem?
The link at following page is broken:
https://qiskit.org/documentation/getting_started.html

### What is the problem?
https://qiskit.org/documentation/apidoc/providers/aer/aer_backends.html
Page Not Found
### What would you expect?
Step 5 : Simulate the Experiment¶
Qiskit Aer is a high performance simulator framework for quantum circuits. It provides *several backends* [ this is the broken link ] to achieve different simulation goals.

**Comment by eddybrando** [comment]
Thanks a lot @MannimMond86 for reporting this.

Since this is related to the Qiskit documentation page, we'll follow up here: https://github.com/Qiskit/qiskit/issues/1194
