### ISSUE TITLE
Provide a space inside GitHub for wiki images

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1619]
This task holds the images in the wiki.

**Comment by delapuente** [comment]
![qiskit.org/events UI](https://user-images.githubusercontent.com/757942/113093424-d860c880-91bd-11eb-9224-1609ca0e6ded.png)

**Comment by y4izus** [comment]
<img width="344" alt="Captura de pantalla 2021-06-04 a las 10 19 43" src="https://user-images.githubusercontent.com/17231966/120774692-d0593800-c522-11eb-8c39-ae8449381575.png">

**Comment by y4izus** [comment]
<img width="1016" alt="Captura de pantalla 2021-06-04 a las 10 54 15" src="https://user-images.githubusercontent.com/17231966/120775726-c7b53180-c523-11eb-88fe-67ab0b0b7640.png">

**Comment by techtolentino** [comment]
Is this still relevant @y4izus ?

**Comment by eddybrando** [comment]
It looks like this can be closed.
