### ISSUE TITLE
Show speaker names or affliations when applicable in the events page

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#1640]
See here: https://qiskit.org/events

**Comment by delapuente** [comment]
This is intended, I'm going to rename this issue to make clear it is a request and tag the event team for them to be aware.
@KallieFerguson @justjosie @AnaMaria

**Comment by eddybrando** [comment]
I believe that this issue can be closed now.

I'm not sure about what the exact intent was, but the "events" page probably looked very different in 2021.

In general, the title and description of the event cards allow for space to display speaker names and affiliations if added in Airtable.

Closing for now, but can be revisited in the future if we see the need.

CC: @y4izus
