### ISSUE TITLE
Create a reusable banner component for special statements

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1669]
As discussed offline with @y4izus and @delapuente, we may need to have a banner component ready to be used for special statements like our support to the BLM movement.

We previously had one for this occasion but are removing it from the codebase as part of a CSS refactory that would otherwise need to update this component as well, which may introduce unnecessary complexity, considering that recreating a similar component in the future may constitute an easier effort.

**Comment by y4izus** [comment]
We already have this component: https://github.com/qiskit-community/qiskit-vue/tree/main/src/components/QiskitBanner, so I think we can close this issue. @eddybrando , do you agree?

**Comment by eddybrando** [comment]
> We already have this component: https://github.com/qiskit-community/qiskit-vue/tree/main/src/components/QiskitBanner, so I think we can close this issue. @eddybrando , do you agree?

Yes, I agree!
