### ISSUE TITLE
[Code Quality] Some instances of the HTML main tag are not hierarchically correct

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1700]
### Steps to reproduce the problem

Take a look at https://github.com/Qiskit/qiskit.org/pull/1699/files#r615520384

### What is the current behavior?

Some `main` tags appear inside the `header` tag. This is incorrect attending to the [HTML specification](https://html.spec.whatwg.org/#hierarchically-correct-main-element).

### What is the expected behavior?

All `main` occurrences should be hierarchically correct.

**Comment by eddybrando** [comment]
We should use this opportunity to also check the correct use of other semantic tags like "footer" or "aside".
