### ISSUE TITLE
Refactor Carbon CSS reusable overwrites

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1701]
We have identified some Carbon CSS overwrites, like the one applied to the accordions in **ContentAccordion** and **StartLocally**.

This overwrite (and potentially others) should be reviewed to check the need for more than 1 customisation of the component, and the definitions should be moved to the `assets/css/components` directory to organise them better and avoid repetition, following the new structure introduced with #965.

**Comment by delapuente** [comment]
Returning this to a regular level of priority.

**Comment by eddybrando** [comment]
I believe this issue doesn't apply anymore as we've refactored our codebase since then.
