### ISSUE TITLE
Develop the final formula widget

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1704]
In order to finalize the formula widget, we need to answer three questions: 

- [x] What is the best way to ensure a user understands that the formula is interactive? 

- [x] At what level does the user interact with the formula?

- [x] How does an educator use this with other formulas?

In order to answer this question, let's use the 2nd equation from the QV lesson as the base example:
<img width="733" alt="Screen Shot 2021-04-19 at 8 26 01 PM" src="https://user-images.githubusercontent.com/9096989/115332982-b7045400-a14d-11eb-97f0-8ea980171115.png">

**Comment by techtolentino** [comment]
Update to checkbox 1:
The team decided to use a light underline for each interactive part of the formula. After several prototypes and discussion, we merged the update here - https://github.ibm.com/IBM-Q-Software/project-platypus/pull/52

Please note that this is currently being tested through our user testing sessions.
