### ISSUE TITLE
As a designer, I want a consistent and flexible way of integrated cards into design files, so that designs match development and the design system.

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1744]
The card components in figma need to be updated to match the standard of quality of the rest of the components in figma.

## acceptance criteria
- [x] A card component (or possibly two) that works for all breakpoints
- [x] A card component that works for all instances where a card gets used (eg. advocates page, events page, textbook, etc)
- [x] A card that matches the development implementation of cards.
- [x] [optional] A card that fully utilizes "auto-layout" in Figma

**Comment by JRussellHuffman** [comment]
This is related to #1747

**Comment by korgan00** [comment]
#1775
