### ISSUE TITLE
As a website user, I expect to leverage the space of my monitor in displaying meaningful information, so that I have a better time reading and understanding qiskit.org information.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1747]
Display new max break points: 
- [x] [Landing Page](https://github.com/Qiskit/qiskit.org/issues/1707) 
- [x] [Learn Page](https://github.com/Qiskit/qiskit.org/issues/1761)
- [x] [Advocate Page](https://github.com/Qiskit/qiskit.org/issues/1762)
- [x] [Overview Page](https://github.com/Qiskit/qiskit.org/issues/1815)
- [x] [Event Page](https://github.com/Qiskit/qiskit.org/issues/1816)
- [x] [Individual Event Pages](https://github.com/Qiskit/qiskit.org/issues/1867)

**Comment by y4izus** [comment]
Should we also modify these pages?
- https://qiskit.org/learn/intro-qc-qh/
- https://qiskit.org/events/seminar-series/
- https://qiskit.org/events/physics-of-computation/

**Comment by lerongil** [comment]
Thank you @eddybrando and @y4izus. This looks great and should have been closed a while ago. Appreciate it.
