### ISSUE TITLE
As an IQC 2021 participant, I want to see my statistics, so I can better understand how well I am doing

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#1754]
- [x] Figma designs are accurately implemented.
- [x] User stats are retrieved from stats endpoint
- [x] User stats are displayed in desktop and mobile view
- [x] User can share statistics
- [x] Final score is show upon completion of last exercise

**Comment by delapuente** [comment]
Designs in Figma are missing the statistic about the number of participants. I included it in the implementation although we need to find a better place for the "Share your progress" link.

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/757942/117097218-03988380-ad39-11eb-8459-9eae88061af4.png">

**Comment by delapuente** [comment]
We need an SVG version and the color specification of the new "ranking" icon.

<img width="41" alt="image" src="https://user-images.githubusercontent.com/757942/117097355-6d189200-ad39-11eb-85dd-2daa4487e229.png">

**Comment by delapuente** [comment]
@vabarbosa can you clarify what do you mean with the following, please?

> Final score is show upon completion of last exercise

**Comment by delapuente** [comment]
The alignment of the statistic icons, labels, and values is set to vertical-center for simplicity.

**Comment by delapuente** [comment]
The circular progress indication keeps the old colors since the duo elements are not updated yet.

**Comment by delapuente** [comment]
> @vabarbosa can you clarify what do you mean with the following, please?
>
>>    Final score is show upon completion of last exercise

Got it! Nevermind.

**Comment by delapuente** [comment]
Users can share progress but not by sharing an image of their stats board.
