### ISSUE TITLE
Minor Typo on page/section https://qiskit.org/documentation/qc_intro.html#quantum-circuits

### ISSUE THREAD

**Issue by td2014** [Qiskit/qiskit.org#1771]
### Where is the problem?

https://qiskit.org/documentation/qc_intro.html#quantum-circuits

Typo in fourth paragraph.  Please see below for specific location.

### What is the problem?

The word "to" is reversed ("ot") in the last sentence of the paragraph below.  I have indicated the location in bold below.  Please check the second word from the end of the paragraph.

> Quantum gates form the primitive operations on quantum data. Quantum gates represent information preserving, reversible transformations on the quantum data stored in qubits. These “unitary” transformations represent the quantum mechanical core of a quantum circuit. Some gates such as 𝑋 (also written as ⊕) and 𝐶𝑋 have classical analogs such as bit-flip and 𝑋𝑂𝑅 operations, respectively, while others do not. The Hadamand (𝐻) gate, along with the parameterized rotates 𝑟𝑋(𝜃) and 𝑟𝑌(𝜃), generate superposition states, while gates such as 𝑍, 𝑟𝑍(𝜃), 𝑆, and 𝑇 impart phases that can be used for interference. Two-qubit gates like the 𝐶𝑋 gate are used to generate entanglement between pairs of qubits, or to “kick” the phase from one qubit **ot** another.

### What would you expect?

> ...the phase from one qubit to another.

**Comment by divshacker** [comment]
I think this issue is not of this repo but of qiskit main repository. 
@vabarbosa  @td2014  can you please transfer this issue there
Thank you

**Comment by td2014** [comment]
@divshacker  I have reposted this issue to repo  Qiskit /qiskit (New Issue #1254) and am closing issue here.  Thank you.
