### ISSUE TITLE
As an IQC 2021 participant, I want to know how to grade and submit the exercises from a local environment

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#1773]
- [x] Grader documentation
- [x] Grading service documentation
- [x] Review with Junye

**Comment by vabarbosa** [comment]
documentation for installing and running locally has been added to the wiki of the grading service

**Comment by delapuente** [comment]
Nicely done. We should add some way of configuring the env variables from Python. Aside from that, everything looks good.
