### ISSUE TITLE
Textbook utility panel should behave as push panel

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1774]
Currently, the Textbook utility panel behaves as an overlaying panel (it sits atop the main content).
We need to restructure this behavior so that it acts as a _push_ panel.

- the main content should still be in full display, when panel is open
- panel should still be fixed, while overflowing, internal content still should be scrollable

**Comment by lerongil** [comment]
Thanks @techtolentino. LGTM!
