### ISSUE TITLE
Textbook homepage links

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1788]
- [x] Relinking all of the links from "browse content" to stay internal to the beta, now that we have all those pages migrated - [#1812](https://github.com/Qiskit/qiskit.org/issues/1812)
- [x] Connect to intro learning path

**Comment by y4izus** [comment]
We need to clarify the last acceptance criteria. [Here](https://github.com/Qiskit/qiskit.org/issues/1803#issue-893806279), one acceptance criteria says that the link should be open on a new tab

**Comment by JRussellHuffman** [comment]
Good catch. Sounds like a little more discussion is still needed. My general rule of thumb is that if it's under the same domain (eg. qiskit.org), it should stay in the same tab. It should only be another tab if it's external.

**Comment by lerongil** [comment]
@y4izus @vabarbosa We stopped working on the QML learning path and changed it back to the intro learning path. This is already completed but will let you check it off if you agree.

**Comment by vabarbosa** [comment]
@lerongil will do. thanks!

**Comment by lerongil** [comment]
Per offline conversations, we removed the acceptance criteria for opening the content within the same tab. We will test this hypothesis upon launch and seeing user experience.
