### ISSUE TITLE
Homepage Hero redesign on "sm" breakpoint

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1790]
The goal is to work on the redesign of the Hero section for the "sm breakpoint".

We need to review the Figma design and adjust it so that it leaves enough room at the top for the interactive "Metal" square whilst also not expanding too far vertically so that the CTA is bellow the fold.

**Comment by lerongil** [comment]
Related to #1747

**Comment by JRussellHuffman** [comment]
will revisit this when the home page goes through an overall redesign.
