### ISSUE TITLE
Add code of conduct to Qiskit.org

### ISSUE THREAD

**Issue by ryanfmandelbaum** [Qiskit/qiskit.org#1798]
Visitors of Qiskit.org should be able to click through somewhere to the code of conduct, perhaps via a link at the bottom. Thanks! 
Code of Conduct link: 
https://github.com/Qiskit/qiskit/blob/master/CODE_OF_CONDUCT.md

**Comment by vabarbosa** [comment]
@JRussellHuffman do you have preferred location to add the Code of Conduct link on qiskit.org. thank you.
cc: @y4izus

**Comment by JRussellHuffman** [comment]
I think the footer is best. It could do under the "community" column in the footer. Or it could go at the very bottom next to "accessibility". I lean towards having it under "community". Thoughts?

**Comment by vabarbosa** [comment]
do the contents in the Community footer column need to coincide with the submenu options in the Community menu bar entry? if not, i would vote for the Community footer column.

**Comment by JRussellHuffman** [comment]
No, I don't think so. The footer can be different. As long as everything under Community relates to the community, which code of conduct seems to fit.
