### ISSUE TITLE
[General UI] Filter section in filtered content such learn, events, and advocates pages too narrow

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1806]
### Steps to reproduce the problem

Visit one of the current [learn](qiskit.org/learn/), or [events](https://qiskit.org/events) on a widescreen.

### What is the current behavior?

The column section holding the filters is too narrow.

![image (11)](https://user-images.githubusercontent.com/757942/118575901-751efb80-b755-11eb-99a5-ec02b3944a03.png)

### What is the expected behavior?

@JRussellHuffman this needs confirmation but I would say we expect the column to keep the same width as in the large break-point:

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/757942/118577191-ee1f5280-b757-11eb-8811-f74e78c5d07d.png">

**Comment by JRussellHuffman** [comment]
The design is based off the carbon columns. The column and gutter widths change from lg to xl, so they are given different column amounts (see below)
<img width="1026" alt="Screen Shot 2021-05-18 at 9 07 35 AM" src="https://user-images.githubusercontent.com/7633881/118666087-7df4e900-b7b8-11eb-8135-6a633234a7a2.png">
<img width="829" alt="Screen Shot 2021-05-18 at 9 07 47 AM" src="https://user-images.githubusercontent.com/7633881/118666116-851bf700-b7b8-11eb-812a-2f299feb2ea8.png">

To me, this is the best option in terms of visual balance, but if it's problematic for development, I'm happy to discuss.

**Comment by eddybrando** [comment]
With the introduction of the new "max" layout for the _learn_ and _events_ pages, the filter will have more space in big viewports: https://qiskitorg-git-fork-eddybrando-ev-issue-1761-learn-m-22548b.vercel.app/learn

But it's true that there are still some viewports (see that page at 1330px width) where the filters may still occupy too little space.

**Comment by JRussellHuffman** [comment]
yep. closing.
