### ISSUE TITLE
"browse all content" (the mega menu/mega dropdown done in #1466) is available from any page

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#1807]
Latest explorations found [here](https://www.figma.com/file/kt2YyAApLBGSlSqJ6dXFqa/platypus-main-file?node-id=485%3A1)

- [x] qiskit.org/textbook-demo
- [x] qiskit.org landing page for course
- [x] every page on platypus [#1868](https://github.com/Qiskit/qiskit.org/issues/1892)

**Comment by JRussellHuffman** [comment]
explorations so far here: https://www.figma.com/file/kt2YyAApLBGSlSqJ6dXFqa/1421-platypus-prototype?node-id=1488%3A4584

Note that I will make a new figma file for final designs. the above link is just for my current explorations
