### ISSUE TITLE
Add Chapter Index to navigation panel

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1820]
~~Part of #1811~~

~~This task is to update the right-side panel with a Chapter Index view~~

~~Note: Chapter index view should be the default _pane_ within the panel~~

A criteria of #1802 is to include an index of the chapters.

This task is to update the left-side (navigation) panel with the chapter index.

This task depends on the index being generated and made available (#1822).

**Comment by vabarbosa** [comment]
just updating the title and comment based on the review and redesign of chapter context
