### ISSUE TITLE
Request for art for Qiskit Blog

### ISSUE THREAD

**Issue by ryanfmandelbaum** [Qiskit/qiskit.org#1825]
Olivia and I are writing a blog titled "How Do You Explain Quantum Computing To..." And then explaining quantum computing to several different segments. I'd love some fun whimsical art showing a few diffrent people (our segments) around a quantum computer. Those people are:

A family member (just a regular looking person will do) 
A child
A scientist
A physicist
A conspiracy theorist
A dog
A software developer
A venture capitalist 
A high school student 

Hoping to run the blog next week!

**Comment by JRussellHuffman** [comment]
Final illustration is here: https://ibm.box.com/s/54fbqjatv3l5v0vlg8w0uslisn7n0fgf
