### ISSUE TITLE
Platypus 404

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#1828]
Currently, we have the default 404. We should design and implement it.

![Captura de pantalla 2021-05-25 a las 13 37 03](https://user-images.githubusercontent.com/4138279/119492832-cfc0e480-bd5f-11eb-89b7-8f3b2533c80b.png)

**Comment by JRussellHuffman** [comment]
Good call. We should do one for the mathigon server and the qiskit.org server. The page can be the same, but I believe we have the same issue on both servers.

**Comment by techtolentino** [comment]
Closing this issue since this is complete, and new issues were created with respective labels.

**Comment by JRussellHuffman** [comment]
thanks! The final implementation looks great, by the way.
