### ISSUE TITLE
Update qiskit summer school page to include bib file

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit.org#1831]
### Where/what is the problem?
Update the page  https://qiskit.org/learn/intro-qc-qh/ to have a citable bib file at the bottom
![image](https://user-images.githubusercontent.com/15937254/119563267-53d19700-bd75-11eb-8a10-94a6f622c920.png)
 
  -- Abe, Zlatko, Leron - moving here from slack chat

### What would you expect?
The bib file is
```
@misc{qgss2020,
abstract = {This course is an introduction to the world of quantum computing, with an exploration of some of the key quantum algorithms and their implementations using quantum circuits, as well as the quantum hardware that is designed to run these algorithms. The course was first offered during the Qiskit Global Summer School in July 2020 as a two-week intensive summer school. There are 27 lectures in this course, which cover the material in 9 lecture notes and 9 associated labs. The textbook for the course is available online: Learn Quantum Computation using Qiskit.},
author = {Asfaw, Abraham and B{\"{a}}umer, Elisa and Bronn, Nicholas and Kandala, Abhinav and Mezzacapo, Antonio and Minev, Zlatko K. and Wootton, James},
keywords = {Quantum circuits,Superconducting qubits,quantum,school},
title = {{Introduction to Quantum Computing and Quantum Hardware}},
url = {https://qiskit.org/learn/intro-qc-qh},
year = {2020}
}
```

**Comment by shil-m** [comment]
Hi, can I work on this? @zlatko-minev

**Comment by zlatko-minev** [comment]
To add the changes to the site? Sounds good to me? Maybe check with @lerongil  or @delapuente, to be sure?

**Comment by shil-m** [comment]
@zlatko-minev  Okay, I will wait for their response :)

**Comment by chrsfshr** [comment]
I'm willing to update this...Any ideas on how the bib file should be included on this page?

**Comment by shil-m** [comment]
Hi @chrsfshr, I am planning to do this, just waiting for confirmation.
