### ISSUE TITLE
hotjar content doesn't scroll down the page

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1851]
### Steps to reproduce the problem
Go to hotjar, any page, for example: https://insights.hotjar.com/sites/1586421/heatmap/view?url=platypus.qiskit.org%2Fcourse%2Fquantum-hardware%2Fmeasuring-quantum-volume&match=simple_match&device=desktop&type=click&range=relative&dates=30d

### What is the current behavior?
The page is cut off and does not show data when scrolling

### What is the expected behavior?
Hotjar data is shown for all of the page.

**Comment by JRussellHuffman** [comment]
This still appears to be an issue as of Jun 28.

Example of the bug: https://insights.hotjar.com/sites/1586421/heatmap/view?url=https:%2F%2Flearn.qiskit.or[…]le_match&device=desktop&type=click&range=relative&dates=30d

**Comment by techtolentino** [comment]
This is working now 🙏

**Comment by JRussellHuffman** [comment]
Just tested it and it works for me too. Thanks for looking into it!! 

Kind of interesting that there is data from 47 sessions even though we haven't publicly announced it yet 🤔
