### ISSUE TITLE
As a quantum curious individual, I want to learn the foundations of quantum computing, so that I can understand how to contribute and work within the quantum computing field.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1853]
Acceptance criteria: 
- [x] mini-composer widget finalized for Z, X and H gate #1856
- [x] static graphics for the learning path as shown in [figma](https://www.figma.com/file/EPP103zwRkZwiG3x1emEHc/1385-learning-path-wireframes?node-id=1807%3A17427)
- [x] (@frankharkins) content written for the remaining intro course pages pages "why quantum computing" through "applied grovers project" [#1895](https://github.com/Qiskit/qiskit.org/issues/1895)

**Comment by korgan00** [comment]
Should we schedule binary demo and matrices interactions?

**Comment by JRussellHuffman** [comment]
Let's move the nice to have material (binary demo, matrices demo, and amplitude demo) to another user story so it can be handled after this story is complete

**Comment by lerongil** [comment]
Are we still targeting the completion of this acceptance criteria: 

-  mini-composer widget finalized for CNOT Implement mini-composer CX #1918

@korgan00

**Comment by lerongil** [comment]
Good job @korgan00 and Frank!
