### ISSUE TITLE
Verify all CTAs are instrumented in platypus and qiskit.org

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#1861]

**Comment by techtolentino** [comment]
Hey @vabarbosa 

I can verify that we have all the CTAs instrumented, between Platypus and Qiskit. We can close this issue.

I think we'll have to do a follow-up PR to ensure that we have consistency in how we're sending `action`s in our data. We can have that PR after we hear back on https://github.com/Qiskit/qiskit.org/issues/1511

**Comment by vabarbosa** [comment]
@techtolentino thank you!
