### ISSUE TITLE
Implement max-size screen for blockbuster page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1873]
We need to adapt the [Blockbuster page](https://qiskit.org/blockbuster/) to support the new layout for the "max" breakpoint.

**Comment by lerongil** [comment]
Blockbuster page won't be used and is not linked from qiskit.org so this isn't necessary

**Comment by eddybrando** [comment]
As discussed offline with @lerongil, implementing the _max-size_ layout in this page will allow us to consolidate the default layout and DRY some code.

Currently we have two "default layouts". One with and one without the support for the _max-size_ breakpoint. We should only have one default layout (the one that supports said breakpoint).

We agree on still working on this without putting too much effort into adapting the design for wider screens.

**Comment by techtolentino** [comment]
I don't think we'll be prioritizing this any time soon. Closing this issue.
