### ISSUE TITLE
Implement max-size screen for individual the Metal page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1874]
We need to adapt the [Metal page](https://qiskit.org/metal) to support the new layout for the "max" breakpoint.

**Comment by lerongil** [comment]
Metal page will be removed in the short term so this isn't necessary

**Comment by eddybrando** [comment]
As discussed offline with @lerongil, implementing the _max-size_ layout in this page will allow us to consolidate the default layout and DRY some code.

Currently we have two "default layouts". One with and one without the support for the _max-size_ breakpoint. We should only have one default layout (the one that supports said breakpoint).

We agree on still working on this without putting too much effort into adapting the design for wider screens.

**Comment by eddybrando** [comment]
This issue is no longer needed. There is no plan to adapt the Metal page to a new design.
