### ISSUE TITLE
Request for art for Qiskit Blog about Germany

### ISSUE THREAD

**Issue by ryanfmandelbaum** [Qiskit/qiskit.org#1878]
We've written a Qiskit blog feature about the quantum community in Germany and what Germans as well as Qiskit are doing to support the budding German Quantum Ecosystem. We'd love a hero image in the Qiskit art style showing the map of Germany with some sort of Quantum feel. Maybe a Q-sphere but instead of a sphere it's the outline of Germany. I'll let you run with it :)

**Comment by delapuente** [comment]
@JRussellHuffman FYI ☝️

**Comment by JRussellHuffman** [comment]
Done. Final art attached. Closing.
![Germany](https://user-images.githubusercontent.com/7633881/122065479-99531400-cdb7-11eb-9d77-5ac3f22bd625.png)
