### ISSUE TITLE
Title with incorrect format

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#1884]
### Steps to reproduce the problem
Go to: https://platypus.qiskit.org/course/introduction/single-qubit-gates

### What is the current behavior?
One of the titles doesn't have the proper format:
<img width="224" alt="Captura de pantalla 2021-06-11 a las 10 15 23" src="https://user-images.githubusercontent.com/17231966/121654646-3bb08600-ca9e-11eb-859b-2bb4ce014e5d.png">

### What is the expected behavior?
The title should show the title with the correct format

**Comment by shil-m** [comment]
Hi @y4izus, I wish to work on this but I am unable to locate the file in this repository.

**Comment by techtolentino** [comment]
Hi @shil-m - thank you for wanting to help with this one 👍 
My apologies for making the PR before seeing your comment.

I committed to looking at this earlier this week, with another team member, and forgot assign.
