### ISSUE TITLE
Update main page of the course with the proper images

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#1887]
Images on the "Course page" section under `/textbook-demo/course/introduction-course`, should be updated with the new ones when they are ready:

<img width="1203" alt="Captura de pantalla 2021-06-11 a las 10 49 28" src="https://user-images.githubusercontent.com/17231966/121659549-b4194600-caa2-11eb-9d8c-7bcfe3e1dc62.png">

**Comment by JRussellHuffman** [comment]
This issue will completed when we have final(ish) pages, by @frankharkins and @JRussellHuffman
