### ISSUE TITLE
Design "What is Qiskit" Slides 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1908]
As a companion to the What is Qiskit [video](https://vimeo.com/user71735722/review/552070067/c7a3fec6f6), we should have 3 slides that covers the following:

Slide 1

Video Embedded 
 

Slide 2

Two options 
1. start locally 
Get started in your own environment with a quick local instal 
2. start online 
Get started in the cloud without installing anything with IBM Quantum Lab.

Slide 3 

1. Build your first quantum circuit 
code for bell state 

(optional) Slide 4

Go further with these resources:
github 
textbook 
youtube 
medium

**Comment by JRussellHuffman** [comment]
After discussing, it may be better to only have 2 slides, one for the video, one for everything else someone would need to get started (the content of slides 2,3,4 as outlined above).

Draft of the slides is here: https://ibm.box.com/s/wcrekmqrdaty387p5bhub8oifh0pc95u

**Comment by JRussellHuffman** [comment]
Marking this done for now.
@lerongil let me know if you want changes and I'll open a new story.
