### ISSUE TITLE
Formatting problems in textbook beta

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit.org#1913]
### Steps to reproduce the problem

Go to https://learn.qiskit.org/course/introduction/

### What is the current behavior?

I've noticed a few formatting quirks:

- [x] Text inside back-ticks (e.g. \`x = 5\`) is currently interpreted as maths, but this text should be interpreted as code.
   - https://github.com/qiskit-community/platypus/pull/28
- [x] The pre-rendered cell output images are broken when the image format is SVG. The problem seems to be with text in the SVG.
    - https://github.com/qiskit-community/platypus/pull/21
- [x] I think code cells should scroll instead of wrapping text. (On my end, I will try and keep all lines below 74 characters, but users may enter longer lines).
   - https://github.com/qiskit-community/platypus/pull/30
- [x] Text outputs from code cells have extra backslashes prepended.
- [x] ~~The sidebar contents are not working for "why quantum computing" ([link](https://learn.qiskit.org/course/introduction/why-quantum-computing))~~

And some clarification is needed:
- What is the correct way to link between pages? Authors have been linking between `.ipynb` files, but these are not converted to urls correctly. Alternatively we can link to webpages (e.g. `https://learn.qiskit.org/course/introduction/why-quantum-computing`)

**Comment by vabarbosa** [comment]
@frankharkins can you clarify the point:

> The sidebar contents are not working for "why quantum computing" ([link](https://learn.qiskit.org/course/introduction/why-quantum-computing))

not sure if the problem has been resolved (i.e., ) or if you are referring to a separate issue?

**Comment by frankharkins** [comment]
Yes they're working now. Before, the subsections (e.g. "what is a computer?" / "classifying computer algorithms") were not displaying. I'll remove that from the issue.
