### ISSUE TITLE
Stabilize/prepare branch for merge

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1934]
- [x] Platypus: replace any link/reference to qiskitorg vercel.app with the new qiskit org url  
    -  https://github.com/qiskit-community/platypus/pull/37
- [x] ~~Platypus: update `robots.txt` to index pages~~ ([Not needed](https://github.com/Qiskit/qiskit.org/issues/1934#issuecomment-876610600))
- [x] Textbook: update beta link  
    -  https://github.com/qiskit-community/qiskit-textbook/pull/1193
- [x] Textbook: add banner with link to beta
    -  https://github.com/qiskit-community/qiskit-textbook/pull/1195
- [x] **Qiskit.org:** Removes any reference to "textbook demo": doc, components, ...
   #1945
 - [x] **Qiskit.org:** the textbook link on the footer and the /learn page, (and any other link) should point to the new textbook
   #1947
- [x] ~~**Qiskit.org:** Update robots.txt to index pages~~ ([Not needed](https://github.com/Qiskit/qiskit.org/issues/1934#issuecomment-876610600))
  #1949

**Comment by eddybrando** [comment]
@techtolentino as clarified by @delapuente offline, we might not need the task "Platypus: update robots.txt to index page".

**Comment by lerongil** [comment]
Let's discuss in our next sprint planning the release plan including specifics around this issue.
