### ISSUE TITLE
[Advocates Page Content] Typo error on slack IDs of advocates on https://qiskit.org/advocates/

### ISSUE THREAD

**Issue by AnsahMohammad** [Qiskit/qiskit.org#1940]
### Where is the problem?

https://qiskit.org/advocates/

### What is the problem?

In this page the slack IDs of the following advocates is having an error:

 Almudena Carrera Vazquez (no id given)
 Ana Martin (no id given)
 David Ittah (no id given)
 Desiree Vogt-Lee (no id given)
 Eesh Gupta( it is \@Quintiii not \@Quintiiii)
 Henrik Dreyer (no id given)
 Ismail Yunus Akhalwaya (no id given)
 Karel Dumon (no id given)
 Kohei Souji (wrong id )
 Mathew Treinish (no id given)
 Michele Grossi (no id given)
 Miguel Parades Quinones (no id given)
 Mohammed Ghazi Vakili (no id given)
 Pauline Ollitrault (no id given)
 Pedro Rivero Ramirez (no id given)
 Sasha Lazarevic (no id given)
 Yael Ben- Hain (no id given)
 Yehuda Naveh (no id given)

For example:
![IMG_20210702_151246](https://user-images.githubusercontent.com/85027826/124255792-2fbd5e80-db48-11eb-8909-9e0a04aa88d2.jpg)

### What would you expect?

Correct the error on Slack IDs of those Advocates listed above!

**Comment by GemmaDawson** [comment]
Eesh Gupta - Slack display name updated to @Quintiii and should reflect on the website within 24 hours.
Ismail Yunus Akhalwaya - Display name was updated sometime in the past

**Comment by GemmaDawson** [comment]
I reviewed the provided list and found an additional three names that need to be updated.

Advocates listed on the website with missing Slack display names

1. Almudena Carrera Vazquez (no display name)
2. Ana Martin (no display name)
3. David Ittah (no display name)
4. Desiree Vogt-Lee (no display name)
5. Edoardo Giusto (no display name)
6. Henrik Dreyer (no display name)
7. Karel Dumon (no display name)
8. Jaeun Kim (no display name)
9. Jody Burks (no display name)
10. Matthew Treinish (no display name)
11. Michele Grossi (no display name)
12. Miguel Parades Quinones (no display name)
13. Mohammed Ghazi Vakili (no display name)
14. Pauline Ollitrault (no display name)
15. Pedro Rivero Ramirez (no display name)
16. Sasha Lazarevic (no display name)
17. Yael Ben- Hain (no display name)
18. Yehuda Naveh (no display name)

Advocates listed on the website with Slack username issues

1. Kouhei Souji (links to deactivated account)
