### ISSUE TITLE
Africa challenge event page

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1943]
Tentative date for the page to launch is **July 28**

**Comment by JRussellHuffman** [comment]
Figma file for this page is here: https://www.figma.com/file/eIoNwe2HfBcyJLssJTHvSt/1943-Africa-Challenge?node-id=0%3A1

**Comment by lerongil** [comment]
Considering the challenge is past, I'll be closing this one out.
