### ISSUE TITLE
Reading time in learn.qiskit.org overlaps the old textbook banner

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1954]
### Steps to reproduce the problem

1. Start an icognito/private browser session.
2. Visit https://learn.qiskit.org/course/introduction

### What is the current behavior?

The reading time indicator overlaps the old textbook banner.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/757942/125166715-dc13cc00-e16a-11eb-8b63-9567cfc06d0a.png">

### What is the expected behavior?

The reading time indicator and the old textbook banner are both fully visible.

**Comment by y4izus** [comment]
Could you try again reloading the page? I don't have this issue. That's what I see going to that page on incognito mode

<img width="1027" alt="Captura de pantalla 2021-07-12 a las 11 22 19" src="https://user-images.githubusercontent.com/17231966/125263615-79a20380-e303-11eb-886d-02f21fcaa7cf.png">

**Comment by lerongil** [comment]
This looks solved.
