### ISSUE TITLE
As a contributor, I want to setup the project in less than 5 min., so I can concentrate on start contributing ASAP.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1961]
- [ ] The project is public and can be cloned.
- [ ] The project explains clearly what needs to be done to set up the environment.
- [ ] The project environment is easy to set up and supports Windows and iOS workflows.

**Comment by jackoconnordev** [comment]
I think this can be closed? The 3 steps clone, npm install and run dev on the README.md work
