### ISSUE TITLE
As a contributor, I want to feel part the Qiskit community, so that I feel easier to contribute to other Qiskit-related initiatives.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1962]
- [ ] Qiskit Code of Conduct is reachable from the repository.
- [ ] Contribution guidelines are clear and easy to follow.

**Comment by eddybrando** [comment]
The Code of Conduct is linked in the repository now in multiple places.

The Contribution guidelines are also linked, but we might be able to improve these and update them to also reflect what parts of Qiskit are situated where.

What do you think @y4izus?

**Comment by y4izus** [comment]
We are having a reorganization of content and those files will live in other place, so we can close this issue
