### ISSUE TITLE
As a user, I want an ever-improving experience, so I can enjoy new features without detriment of previous ones.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1964]
- [x] New acceptance criteria are automatically checked on every new addition.
- [x] The team has identified the most important functionality to be preserved through versions.
- [x] There is a mechanism to check new changes do not break the most important functionality.

---
Related
- #1987 
- #1988 
- #1989 
- #1990

**Comment by lerongil** [comment]
@vabarbosa Can this be closed out?

**Comment by vabarbosa** [comment]
@lerongil, yes the test framework is in place and moving forward will be adding individual testing of the acceptance criteria as the functionality is added
