### ISSUE TITLE
As part of the product team, I want to release new features as soon as they become available, so that we can gather insights faster. 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1967]
- [ ] New functionality is deployed to production as soon as it meets acceptance criteria.

---
Related
- Qiskit/platypus#507
- Qiskit/platypus#506
- Qiskit/platypus#521

**Comment by pandasa123** [comment]
@lerongil, I think we can close this issue?

**Comment by y4izus** [comment]
All the tasks on this issue are completed, so I'm gonna close the issue
