### ISSUE TITLE
Translate the results of the July, 12th smoke tests into issues

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1968]
Document and open, in form of bugs, the issues you found during July, 12th smoke test.

**Comment by vabarbosa** [comment]
Created the following issues:

- https://github.com/Qiskit/qiskit.org/issues/1977
- https://github.com/Qiskit/qiskit.org/issues/1976
- https://github.com/Qiskit/qiskit.org/issues/1975
- https://github.com/Qiskit/qiskit.org/issues/1974
- https://github.com/Qiskit/qiskit.org/issues/1973
