### ISSUE TITLE
As a developer, I want to use the most modern and well-supported technologies, so we can benefit from the learnt lessons and accumulated best practices of new versions..

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1969]
- [ ] Dependencies remain up to date.
- [ ] The project does not use deprecated features.
- [ ] The project does leverage technology possibilities, embracing best practices.
- [ ] The project is always in a good shape for transitioning to the next version of the involved technologies.

**Comment by y4izus** [comment]
We are not gonna add more features to this repo so we can close this issue
