### ISSUE TITLE
As a learner from outside of the US, I want to read the textbook in my language, so that I can better comprehend and understand quantum computing.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1971]
Acceptance Criteria:

- [x] Translation selector accessible to user via UI 
    - #1979
- [x] At least 2 translated languages available
    - #1982 
    - #1983 
- [x] Automated or easy-to-use system for translators providing translations 
    - #1984 
    - Add documentation on how it all works, for collaboration
    - Coordinate w/ Translation team https://github.com/Qiskit/qiskit.org/issues/2151
- [x] Manage out of sync translations from parent textbook
- [x] Fix bug https://github.com/Qiskit/qiskit.org/issues/2150

**Comment by JRussellHuffman** [comment]
Component details here: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=1345%3A2554

Shown in the UI here: https://www.figma.com/file/kt2YyAApLBGSlSqJ6dXFqa/platypus-main-file?node-id=499%3A0

**Comment by lerongil** [comment]
Thanks a lot for the great work @vabarbosa @techtolentino @y4izus !
