### ISSUE TITLE
Add Translation selector component to Textbook Beta UI

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1979]
Figma designs for the Language Selector component [here](https://www.figma.com/file/kt2YyAApLBGSlSqJ6dXFqa/platypus-main-file?node-id=2098%3A20216)

![Screen Shot 2021-07-20 at 10 05 12 AM](https://user-images.githubusercontent.com/6276074/126365925-6842afba-2883-4498-8bec-8a4b13421b30.png)

Related #1971

**Comment by JRussellHuffman** [comment]
Component details in the qiskit component file here: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=1345%3A2554

Note, the component includes a state where a language is not available, such as the intro course in Japanese. Is that a valid use case? Are there other states that we should account for?

**Comment by JRussellHuffman** [comment]
It sounds like there is one more state needed for the UI for a page in english, but the user has "japanese" selected.

**Comment by delapuente** [comment]
Is this done? This is under "done", right?

**Comment by JRussellHuffman** [comment]
Can we open up a follow up issue for this, regarding when the UI is closed? It looked good open, but there are issues when the panel is closed. (see screenshot). The better user experience is in the figma [here](https://www.figma.com/file/kt2YyAApLBGSlSqJ6dXFqa/platypus-main-file?node-id=532%3A0)
<img width="119" alt="Screen Shot 2021-08-09 at 10 50 29 AM" src="https://user-images.githubusercontent.com/7633881/128884020-4bd02ce4-9dab-4a10-a6df-b4cee59e9455.png">

**Comment by techtolentino** [comment]
@JRussellHuffman - new story here: https://github.com/Qiskit/qiskit.org/issues/2054

**Comment by JRussellHuffman** [comment]
thanks!
