### ISSUE TITLE
Intro Course: "What is quantum?" chapter not filling in all progress bubble 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1981]
### Steps to reproduce the problem

Navigate to: https://learn.qiskit.org/course/introduction/what-is-quantum
Complete all interactions

### What is the current behavior?

Leaves bubble empty about 25% despite everything complete

### What is the expected behavior?

Should be fully completed after all actions are filled

**Comment by vabarbosa** [comment]
@korgan00 do you mind looking at this? i believe what is happening here is when you finish the minicomposer exercise the goal/score is not being updated
