### ISSUE TITLE
Update deployment process/steps where possible to simplify and improve the deploy to production

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#1986]
After findings from review (#1985), are there any updates that can be made to improve deploy to production

---
Related
- https://github.com/Qiskit/qiskit.org/issues/1967
- https://github.com/Qiskit/qiskit.org/pull/1999

**Comment by techtolentino** [comment]
Leaving a summary of updates:

- [x] updated Qiskit.org and Textbook beta documentation, to include Deployment sections
- [x] synced w/ infrastructure team to update internal documentation (specifically in the  `Edge functions` section)
- [x] updated Qiskit.org build process to leverage caching
- [x] added Cypress testing to the Textbook beta Build and release process
