### ISSUE TITLE
Identify initial set of functionality to be tested

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#1988]
Review smoke test and create decision matrix to identify the tests that should/can be automated within this sprint

---
Related #1964

**Comment by eddybrando** [comment]
Based on our [curated set of tests for the Platypus smoke test](https://ibm.ent.box.com/notes/830873296907?s=xgzmi4dlrv3cuir41d942rq397vr3mja), I've created a [decision matrix spreadsheet](https://ibm.box.com/s/b3u4npyshs3lnycws0o2uzbgld6xcrky):

![Screenshot 2021-07-21 at 15 41 13](https://user-images.githubusercontent.com/22047320/126498491-8c6003b9-fc42-46aa-9fef-25a7132b8979.png)

The bigger the weighted total, the higher should be the test in our list of priorities to automate.

Please feel free to suggest different values or even other criteria for the matrix. I tried to keep it simple.

According to my results, we should prioritise the automation of these tests in the following order:

1. Are the CTAs working? Or do they lead to 404?
2. Is the text always readable?
3. Is some page not loading or taking a long time to load?

**Comment by vabarbosa** [comment]
@eddybrando well done!
