### ISSUE TITLE
Some math and text not rendering properly

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1996]
### Steps to reproduce the problem
Go to https://learn.qiskit.org/course/ch-applications/solving-combinatorial-optimization-problems-using-qaoa and scroll to 4.3.3

### What is the current behavior?
<img width="560" alt="Screen Shot 2021-07-19 at 11 51 34 AM" src="https://user-images.githubusercontent.com/7633881/126197333-e9d3da5b-c0b8-453c-91c8-747a1591cda9.png">

### What is the expected behavior?
It should render as standard legible notation

**Comment by eddybrando** [comment]
This issue has been solved.

![Screenshot 2021-12-21 at 10 12 30](https://user-images.githubusercontent.com/22047320/146903417-f260f4f4-db03-471f-b517-f1081314bff3.png)
