### ISSUE TITLE
Math in section titles not rendering in left hand navigation

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1998]
### Steps to reproduce the problem
https://learn.qiskit.org/course/ch-applications/solving-combinatorial-optimization-problems-using-qaoa

### What is the current behavior?
<img width="215" alt="Screen Shot 2021-07-19 at 2 54 59 PM" src="https://user-images.githubusercontent.com/7633881/126219135-6c9edc24-cb86-4a96-9f0c-d60c32798b3f.png">

### What is the expected behavior?
Section titles should render the same as they do inline.

**Comment by eddybrando** [comment]
This issue has been solved.
