### ISSUE TITLE
As a reader, I want to understand my progress throughout textbook pages and courses, so that I can pick up where I left off reading last time.

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2001]
This is related to the page index work that was started before the beta release. The mvp implemntation was delivered, but post-mvp features will be important to helping users understand where they are in the textbook.

Post mvp designs are here: https://www.figma.com/file/WbSzQJbyjP85Jh8o0oFw5W/1802-in-page-index?node-id=62%3A1, but they should be revisited and expanded into the non-course textbook pages.

**Comment by y4izus** [comment]
this is done, so i close the issue
