### ISSUE TITLE
As a learner, I expect to be able to consume the textbook material on any device or hardware, so that I can learn regardless screen or bandwidth restrictions.

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2003]
Based on feedback from user testing, we need to optimize textbook performance and component design for less than ideal devices. This includes

- [ ] all responsive screen screen widths for components
- [ ] make sure components aren't too tall, or have a solution for when components get tall
- [ ] optimize for low bandwidth usage
- [ ] dark mode (this may need to be a separate user story)

**Comment by y4izus** [comment]
This is no more relevant, I close it
