### ISSUE TITLE
As a learning, I want to be able to highlight text and add notes in the textbook that is familiar to taking notes in a standard book, so that I can recall my thoughts as I was reading the material

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2004]
- [ ] ability to highlight text in the textbook and save the highlight
- [ ] add text notes associated with a given highlight and save it.
- [ ] create threads based off notes
- [ ] update or delete notes and highlights

This is the highlighter/note taker feature show here: https://www.figma.com/file/kt2YyAApLBGSlSqJ6dXFqa/platypus-main-file?node-id=1660%3A15191
and outlined here: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=506%3A0

**Comment by y4izus** [comment]
The learning platform has been completely redesigned and move to another repo, so I close this issue
