### ISSUE TITLE
As a learner, I want supplementary information in the textbook so that I don't need to leave the textbook if I need help

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2007]
This is relating to adding helpful material to the right-side panel. We already have the glossary, which is a great start, and we can push it further. We should add
- [ ] gate glossary. (early designs: https://www.figma.com/file/kt2YyAApLBGSlSqJ6dXFqa/platypus-main-file?node-id=1660%3A3107)
- [ ] FAQs (no design yet)
- [ ] Docs. I'm not sure the feasibility on this one, but if we could integrated some of the material from the documentation into the textbook, it would probably be very helpful.

**Comment by y4izus** [comment]
per offline conversations, we can close this issue
