### ISSUE TITLE
As a reader, I want all pages of the textbook to meet the same standards of quality on all pages, so that I can learn all textbook content in the same way as the intro course.

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2008]
Now that we have the introductory course in place, what can be done to the rest of the textbook pages so that there is consistent representation across all pages. This may include

- [ ] vocab and math annotations on all pages
- [ ] new illustrations for each page
- [ ] added interactive components for each page

**Comment by lerongil** [comment]
@JRussellHuffman should we just close this one out due to the large scope and focus on the iterative approach we are taking with the other legacy pages?

**Comment by JRussellHuffman** [comment]
yeah. that sounds good to me.
