### ISSUE TITLE
As a quantum developer, I want to realize the key features about Qiskit, so I can decide if it is worth a try and start hacking.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#2009]
The final designs can be found [here](https://www.figma.com/file/ndskBjmtWzjhdPCRrwMGBi/2009-home-page-key-features?node-id=119%3A11778) under the "FINAL for mvp" page. 

- [ ] User should realize about the circuit library.
- [ ] User should realize about the compiler.
- [ ] User should realize about how to run their code in real hardware.
- [ ] User should know there are ways of starting developing immediately.
- [ ] Re-use the metal component if possible 

<img width="476" alt="image" src="https://user-images.githubusercontent.com/757942/126374992-887e9d5b-827a-4194-b498-c186dae191a9.png">

**Comment by delapuente** [comment]
These two items needs further clarifications, in my opinion:

> User should realize about how to run their code in real hardware.
User should know there are ways of starting developing immediately.

**Comment by 1ucian0** [comment]
Im not sure if these snippets are just illustrative.

If so, here is my suggestion (the `#N` comments refers the numbered items after):

```python
import qiskit
```
```python
# Qiskit quantum circuits libraries
quantum_circuit = qiskit.circuit.library.QuantumVolume(5)  #1  #3
quantum_circuit.draw()
```
```python
# prepare your circuit to run
from qiskit import IBMQ #2

provider = IBMQ.load_account()  #3
backend = provider.get_backend('ibmq_santiago')  #4

optimized_circuit = qiskit.transpile(quantum_circuit, backend)  #5
optimized_circuit.draw()
```
```python
# run in real hardware
job = backend.run(optimized_circuit)
retrieved_job = backend.retrieve_job(job.job_id())
result = retrieved_job.result()  #6
```

1. The line `quantum_circuit = qiskit.library("QV", 27)` is not currently valid in Qiskit (0.29).

2. `IBMQ.load_account()` is not a line that you can just run the first time. You need to set up the token. 

3. Vigo is retired https://quantum-computing.ibm.com/lab/docs/iql/manage/systems/retired-systems . Also, that QV circuit needs a bigger system. However, there are no systems on that side that are currently open (as far as I know).

4. `IBMQ` is being deprecated (it's going to be replaced by `qiskit-ibm` https://github.com/Qiskit-Partners/qiskit-ibm). Should this change wait for it? @jyu00 ?

5. `transpile` needs the backend. `qiskit.compiler` is the name of the module and cannot be callable.

6. Which kind of "result" makes sense to show to a first-time user?

**Comment by ismaelfaro** [comment]
Hi @lerongil and @1ucian0 I'll set a meeting with you to move this ahead.

I would like to have something done for the next month.

**Comment by 1ucian0** [comment]
I suggest to have a `IBMQ.load_account(<API token>)` to avoid having two lines for the save and the load. In situation like this example, having a way to use a token for a single time might be handy.

**Comment by 1ucian0** [comment]
I just learned from @rathishcholarajan that is possible to use `IBMQ.enable_account(<API token>)` for exactly this case, where we want to avoid having two lines for the save and the load. This would leave the example as this:
```python
from qiskit import IBMQ

provider = IBMQ.enable_account(<API token>)
backend = provider.get_backend('ibmq_santiago')

optimized_circuit = qiskit.transpile(quantum_circuit, backend)
optimized_circuit.draw()
```

**Comment by 1ucian0** [comment]
With the help of @jyu00 (and with the new interface for ibm-qiskit coming in next year) the third snippet would look like this:

```python
# run in real hardware
job = backend.run(optimized_circuit)
retrieved_job = backend.job(job.job_id())
result = retrieved_job.result()
```

**Comment by JRussellHuffman** [comment]
@1ucian0 There should be 3 snippets in total, right? Can you post all 3 together as a single comment in this thread, so we don't have to hunt them down?

**Comment by 1ucian0** [comment]
here they are:

```python
import qiskit

# Qiskit quantum circuits libraries
quantum_circuit = qiskit.circuit.library.QuantumVolume(5) 
quantum_circuit.draw()
```

```python
# prepare your circuit to run
provider = qiskit.IBMQ.enable_account(<API token>)
backend = provider.get_backend('ibmq_santiago')

optimized_circuit = qiskit.transpile(quantum_circuit, backend)
optimized_circuit.draw()
```

```python
# run in real hardware
service = IBMRuntimeService()
job = service.sample(circuits, backend)
retrieved_job = backend.retrieve_job(job.job_id())
result = retrieved_job.result() 
```

Note: This wont be valid until 2022.

**Comment by jyu00** [comment]
If we are basing the sample code on future `qiskit-ibm-runtime`, then the syntax should be

```
import qiskit

# Qiskit quantum circuits libraries
quantum_circuit = qiskit.circuit.library.QuantumVolume(5) 
quantum_circuit.draw()
```

```
# prepare your circuit to run
service = IBMRuntimeService(<API token>)
backend = service.get_backend('ibmq_santiago')

optimized_circuit = qiskit.transpile(quantum_circuit, backend)
optimized_circuit.draw()
```

```
# run in real hardware
job = service.sample(circuits, backend)
retrieved_job = backend.retrieve_job(job.job_id())
result = retrieved_job.result() 
```

**Comment by 1ucian0** [comment]
`retrieve_job` or `job`? @jyu00

**Comment by ismaelfaro** [comment]
> ```python
> # prepare your circuit to run
> service = IBMRuntimeService(<API token>)
> backend = service.get_backend('ibmq_santiago')
> 
> optimized_circuit = qiskit.transpile(quantum_circuit, backend)
> optimized_circuit.draw()
> ```

I prefer to highlight the transpilation in the comment
> # prepare your circuit, transpiling to optimize it to run

**Comment by JRussellHuffman** [comment]
Thanks for the update, this is very helpful.
For each section (Circuit library, Compiler, Run on real hardware), we have space for a call to action that links somewhere. Where would you like each of those sections to link? In earlier discussions, I believe it was said that there is a page for each of these sections in the Qiskit docs. Can you share the best links for each section?

**Comment by JRussellHuffman** [comment]
@ismaelfaro @1ucian0 @jyu00 Can you verify this correct based on the discussion above:
```import qiskit

# Qiskit quantum circuits libraries
quantum_circuit = qiskit.circuit.library.QuantumVolume(5) 
quantum_circuit.draw()

# prepare your circuit, transpiling to optimize it to run
service = IBMRuntimeService(<API token>)
backend = service.get_backend('ibmq_santiago')

optimized_circuit = qiskit.transpile(quantum_circuit, backend)
optimized_circuit.draw()

# run in real hardware
job = service.sample(circuits, backend)
retrieved_job = backend.job(job.job_id())
result = retrieved_job.result() ```

Also, can you please help with the call to action associated with each section?  Per screenshot below, we want to point users to more information about each of the 3 snippets. Is there a good page for each of these in documentation somewhere?
<img width="717" alt="Screen Shot 2021-12-02 at 12 52 08 PM" src="https://user-images.githubusercontent.com/7633881/144484832-8cb2fce8-3831-4645-9c12-e2b825851033.png">
.

**Comment by JRussellHuffman** [comment]
Also, can you please help with the call to action associated with each section?  Per screenshot below, we want to point users to more information about each of the 3 snippets. Is there a good page for each of these in documentation somewhere?
<img width="717" alt="Screen Shot 2021-12-02 at 12 52 08 PM" src="https://user-images.githubusercontent.com/7633881/144484832-8cb2fce8-3831-4645-9c12-e2b825851033.png">

**Comment by vabarbosa** [comment]
@JRussellHuffman @ismaelfaro @1ucian0 when clicking on "Open in Quantum Lab" link on the homepage the reader will be redirected to this notebook in Quantum Lab:

https://quantum-computing.ibm.com/lab/files/qiskit-textbook/getting-started/example.ipynb

is this what is expected/preferred? any additional information that should be included in this notebook?
