### ISSUE TITLE
Deployment of qiskit.org is failing

### ISSUE THREAD

**Issue by paulsearle** [Qiskit/qiskit.org#2011]
Originally added as: "Old event still showing as 'upcoming' on events page"

<img width="1360" alt="Screen Shot 2021-07-20 at 3 48 31 PM" src="https://user-images.githubusercontent.com/79483070/126405207-d7be3a6a-8540-47b1-8121-99f2b7074050.png">

**Comment by delapuente** [comment]
The merge of https://github.com/Qiskit/qiskit-terra/pull/6558 has removed and deployments are failing with:

```
Cloning into 'qiskit-terra'...
cp: cannot stat 'qiskit-terra/qiskit/schemas': No such file or directory
Error: Process completed with exit code 1.
```
