### ISSUE TITLE
Add Copy button to code cells

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2027]

**Comment by abdonrd** [comment]
The copy button from GitHub is open source:

https://twitter.com/koddsson/status/1392052108652945409

https://github.com/github/clipboard-copy-element

**Comment by JRussellHuffman** [comment]
Designs are a part of the code component file here: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=1365%3A3219
