### ISSUE TITLE
Investigate how to improve the performance of the kernel or coding experience

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#2028]

**Comment by vabarbosa** [comment]
the code cells are run using [Thebe](https://thebelab.readthedocs.io/en/latest/index.html) in conjunction with [Binder](https://mybinder.readthedocs.io/en/latest/):

- https://github.com/qiskit-community/platypus/blob/main/server/includes/thebe-config.html#L2-L6

Thebe turns the code into an interactive component allowing you to run the code and display the output. Thebe is configured to connect to Binder for the kernel to actually execute the code. the Binder service allows you to create custom computing environments that can be shared by many remote users (FYI, [Binder has a maximum current user of 100 for a given repo](https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html#maximum-concurrent-users-for-a-repository)).

when visiting a page it can take time to get the Binder environment initialized, kernel ready, and have the code cells executable. [detail on the operations of Binder](https://mybinder.readthedocs.io/en/latest/about/about.html?highlight=api#what-factors-influence-how-long-it-takes-a-binder-session-to-start) can provide insight to areas that impact startup performance:

some additional information on ways to improve the Binder launch time can be found here:

- https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956
- https://discourse.jupyter.org/t/tip-speed-up-binder-launches-by-pulling-github-content-in-a-binder-link-with-nbgitpuller/922

with that said, the wait time for starting a binder could potentially be decreased by:

1. [pre-building the Docker container so Binder does not need to build](https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2)
2. customizing the Docker image to be as lightweight (i.e., dependencies, etc.) as possible
3. accessing the Binder instance regularly to minimize how often Binder has to download

---

@y4izus here is the summary (and additional info) of the discussion we had initially started on the topic

**Comment by y4izus** [comment]
Thank you very much @vabarbosa !
