### ISSUE TITLE
Add tests to ensure text is always legible/readable

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2034]
Things to check
- [x] contrast - https://github.com/qiskit-community/platypus/pull/106
- [x] size of text - https://github.com/qiskit-community/platypus/pull/106
- [ ] ~no overlapping/overflowing text~ (see [comment](https://github.com/Qiskit/qiskit.org/issues/2034#issuecomment-898705430) )
- [ ] ~math equations render~ (see [comment](https://github.com/Qiskit/qiskit.org/issues/2034#issuecomment-898439952) below)

**Comment by abdonrd** [comment]
Maybe we can check some of this things with Lighthouse:

https://github.com/GoogleChrome/lighthouse

And maybe using this tool for the CI:

https://github.com/GoogleChrome/lighthouse-ci

**Comment by eddybrando** [comment]
I believe Lighthouse implements **axe-core**. But there is also a plugin to test accessibility with **axe-core** in **Cypress** directly: https://www.npmjs.com/package/cypress-axe

I think that for the purpose of these tests and given that we already have **Cypress** integrated in our CI, using **cypress-axe** might be the most straightforward way to go.

What do you think?

**Comment by abdonrd** [comment]
Yes, Lighthouse uses `axe-core` under the hood.

If for these tests `cypress-axe` is enough, go ahead!

But I think adding Lighthouse would bring us a lot of value (in more areas than accessibility tests). Maybe for another issue.

**Comment by eddybrando** [comment]
https://github.com/Qiskit/qiskit.org/issues/2062

**Comment by vabarbosa** [comment]
> Yes, Lighthouse uses `axe-core` under the hood.
> 
> If for these tests `cypress-axe` is enough, go ahead!
> 
> But I think adding Lighthouse would bring us a lot of value (in more areas than accessibility tests). Maybe for another issue.

in agreement here... definitely worth investigating Lighthouse and we can also throw into the mix the [IBM equal access toolkit](https://github.com/IBMa/equal-access) which includes a [cypress accessibility plugin](https://github.com/IBMa/equal-access/tree/master/cypress-accessibility-checker).

**Comment by vabarbosa** [comment]
@eddybrando i added one more item to this checklist for this issue. it has to do with checking for math equations that did not render. [for example](https://learn.qiskit.org/course/ch-applications/solving-combinatorial-optimization-problems-using-qaoa):

<img width="1637" alt="image" src="https://user-images.githubusercontent.com/13156555/129360040-6b8188b4-c770-41d6-bcb0-e5c4342865ac.png">

looking at the page you can see equations that fail rendering are contained in `mjx-error` node. we should hopefully be able to just query for that to know if any page has a problematic equation.

**Comment by eddybrando** [comment]
> @eddybrando i added one more item to this checklist for this issue. it has to do with checking for math equations that did not render. [...]

Thank you @vabarbosa 🙂 

Whilst I completely agree that this is important to test, according to the list of tests defined in https://github.com/Qiskit/qiskit.org/issues/1988#issuecomment-884203797, that would be part of the test "D" (Are equations being displayed properly?).

In this issue, we're only working on the test "C" (Is the text always readable?). So I believe it would be more appropriate to create another ticket for that one. 🙂

**Comment by eddybrando** [comment]
I submitted https://github.com/qiskit-community/platypus/pull/106, which covers the contrast and text size issues.

The overlapping / overflowing one was tricky and I'm afraid I couldn't find a reliable and performant method to test it yet. Still, in that PR is included a test for _visibility_, but I believe that would still pass even when less than 100% of the element is not covered by other element.

More details can be found in the PR's comment. 🙂
