### ISSUE TITLE
Support for India Week of Quantum

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2040]
**event name**
Qiskit | India week of quantum

**timeline** 
August 23 (more or less)

**Figma file**
https://www.figma.com/file/dSVvyrDi46feL7mwLCmkdz/India-week-of-quantum?node-id=2%3A2

**design needs**
- registration form (event brite) (Aug 10)
- generic flyer with some details (7 Aug)
    - good with the version we have. put on figma and they can comment
- day of details
    - will go into the attendee guide
- attendee guide
    - provide assets
- resource guide
    - provide assets
- feature book
    - provide assets

**Comment by thetronjohnson** [comment]
The box note containing the design needs https://ibm.box.com/s/0v0lc1dwcsxrhw1nnyzad77xatzfew1x

**Comment by y4izus** [comment]
This event already took place, so I think we can close this issue
