### ISSUE TITLE
Develop a better 404 page

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit.org#205]
Can we have a better page for 404 error.
This is the current one:
![Screen Shot 2019-08-29 at 9 36 55 AM](https://user-images.githubusercontent.com/11485594/63945182-e1694100-ca40-11e9-882f-485ea6d47769.png)
This error shows up when the website is being deployed with new changes and we visit Qiskit.org

Also, this error 
![Screen Shot 2019-08-29 at 10 11 37 AM](https://user-images.githubusercontent.com/11485594/63947774-8c7bf980-ca45-11e9-892f-75c897fcb2f4.png)
Shows up in documentation

**Comment by y4izus** [comment]
The `type:enhancement` label is going to [disappear](https://github.com/Qiskit/qiskit.org/issues/1041) . This enhancement is not related to the code quality but with a new feature, that's why I added the `type: feature request` label

**Comment by delapuente** [comment]
Fortunately, this is no longer this way although we still need to address #1093. Closing this one though.
