### ISSUE TITLE
Research about using Lighthouse

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/qiskit.org#2062]
Lighthouse is an open-source, automated tool for improving the quality of web pages. You can run it against any web page, public or requiring authentication. It has audits for performance, accessibility, progressive web apps, SEO and more.

https://github.com/GoogleChrome/lighthouse

Lighthouse CI is a suite of tools that make continuously running, saving, retrieving, and asserting against Lighthouse results as easy as possible.

https://github.com/GoogleChrome/lighthouse-ci

And it could also be interesting research about Web Vitals.

https://web.dev/vitals/

**Comment by abdonrd** [comment]
Current status:

- [WebPageTest report](https://www.webpagetest.org/result/210813_AiDcFS_6a820595b36eba163a985ece935a39b0/)
- [Lighthouse report](https://www.webpagetest.org/lighthouse.php?test=210813_AiDcFS_6a820595b36eba163a985ece935a39b0&run=2)
- [Lighthouse treemap report](https://googlechrome.github.io/lighthouse/treemap/?gzip=1#H4sIAAAAAAAAE41W247bNhD9FUMPfrIk3i8LGEGLvBRIFyi2WyQogoIiKS9j3SJRm3UW/vfSF6AbiW70KA3nzJnh4cy8JtVTn9y9Jr39OtrBW/PYV8ld8uR9N9zl+Vc37J3P2n6XJ5ukdI2q/u+AGo3zwwlv0L3rfOp7a2vVpUZ5dfrtTPCN2TaJd76ywfpwtq7+vFhX7y9WYy9erm3CmcfBmlXZ9qsrxkp1XTg06LYPEM1YVdeP927oKnX4vTUnaNcEn1p592zPkF656szWH7qTfcKoCV7B/Pdr0qja3ky6t0M79tr+evCn44gSjI6bmZNum8E2PvP9GOqc6bbOm9Y7bd/prbdX69q0tXLN1hX16cTa2xe/DR523em23Tu73vl6C9eDV95u//plrdux8f1h+/gwZyIhYJtkbMZQresvKCGOcTNNNthdfeJ3IqbCPR8CtyH7MuTPMC9L8+nDs/vju8X774Hhb/cf7/fs/lv3SX6oPupvbxxq1wSnORnMIYYzOoAgKSKETvk5nT21/ovqz5R0fvlIIRWMIBiCvBuet2weCULMyCQQBzCWdtWOJrvW+r8c8mJ0lcmLarS1e0l/nhvkgBAwCSkAYDIS9I14/mnGF5/D0pZA0CgyBYTCCTDiXIAlwFQVQtIyTpkBjKe3ASVbBMwJgZrZODASWE6AKUaxFzHDJSVAXBZR3JA1n5YYEoyj6jm3irfqqVszVnbIBCkVIAoypjguLS+1wPFwUAqGJvGYIHG1zuJ1vVXap64JH67ZpaW1plB6nxGkSFlCWGjNGdQKAazidSQUiGnCBAEUIzCrJNOh5OpGapLzCS5eplRqkBGA3BAUnZaLLhITMZohrONUKWFTrpJQtgRXllRiLeJkBSVTtnyZ9klBDNHxyuIgmelrlWDRhSkrLSxuvFUB5LQK4a0uogug4FiBW7h4hgsYX8S3pIXkMl4GANC0BcBFDUAjbBW8ITApBJ3SFQzjRdIVVOnQkeN8JZrLAdGQRWxWzvs34ZaUcUVQHjQxrUWYXlHkHzYE1evLVBoG66+bwnkah3mc8TSggnk4jvmsaRFKyE8eTBj/qd65ax8bcqqpMRyJy4AsK9Xb9DKR87AfuSo1YV8x9vY8RLMRACE/fj4ej5skZFm63YP1PjTG8/ZVtVqdVz/bpGGPCaf+BT1VZSiXCgAA)

**Comment by korgan00** [comment]
I think this is not a Decoration issue. It is not related to aesthetics.

**Comment by y4izus** [comment]
This issue is no relevant anymore, so I close it
