### ISSUE TITLE
Update mathigon styling to our styling

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2092]
Update the mathigon styling used in the in-line dropdowns to match our styling
(example: https://learn.qiskit.org/course/ch-states/the-atoms-of-computation)

Design component is specced out here: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=395%3A891

**Comment by muHashh** [comment]
hello there
