### ISSUE TITLE
Project Portal

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit.org#2101]
Create a website to hold details about all projects done by community members

Features it should have:
* Show what projects have been done, and what is ongoing;
* Allow projects to 'cite' each other, and track the citations.
* Provide guidance to get people started in a new project;
* Have some sort of seal of approval, so people can get validation for their project.

Part of the guidance would be to have example projects, which would need to have features like
* A published paper
* Tutorial blog/videos
* Easy to use source code

Additional eatures that might be good:
* Allow users to upvote each other projects;
* Allow users to comment on each other projects.

It should provide the same sense of achievement and validation that people used to get from getting a notebook added to the old (2018 era) Qiskit tutorials, but in a much more scalable way.

**Comment by eddybrando** [comment]
Closing now since it's a proposal from 2021, but we'll be keeping this in mind in case we want to plan it or something similar for the future.

Thanks a lot @quantumjim!

CC: @y4izus
