### ISSUE TITLE
Integrate accessibility CI tests to Qiskit.org

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2102]
In order to automate accessibility checks for Qiskit.org, we should integrate into our CI pipeline a tool like Cypress + [cypress-accessibility-checker](https://www.npmjs.com/package/cypress-accessibility-checker), Cypress + [cypress-axe](https://www.npmjs.com/package/cypress-axe) or [Lighthouse](https://developers.google.com/web/tools/lighthouse).

Also, we might want to use the same in Platypus and document what tools we use for what (here, for instance, what we use for a11y checks, in order to avoid redundant tests).

**Comment by korgan00** [comment]
I think this is not decoration. It is not related to aesthetics.

**Comment by y4izus** [comment]
This issue is no relevant anymore, so I close it
