### ISSUE TITLE
Create `.prettierrc` with rules

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2103]
For consistency and so that IDEs / text editors like VS Code's auto-lint functionality works as expected, creating a `.prettierrc` file might be helpful.

We could take as an example the one that comes with the newest Nuxt versions:

```json
{
  "semi": false,
  "singleQuote": true
}

```

**Comment by korgan00** [comment]
This is not decoration. It is not related to aesthetics. I think this is code-quality

**Comment by eddybrando** [comment]
We're using the "prettier/recommended" configuration already.
