### ISSUE TITLE
Update `.eslintrc.js`

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2104]
Newer Nuxt versions come with an ESLint configuration file similar to this:

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
  },
  extends: [
    '@nuxtjs/eslint-config-typescript',
    'prettier',
    'prettier/vue',
    'plugin:prettier/recommended',
    'plugin:nuxt/recommended',
  ],
  plugins: ['prettier'],
  // add your custom rules here
  rules: {},
}
```

It deviates a little from what we currently have and probably integrates Prettier better as we're currently doing it.

We should review this newer version and probably update our own file.

**Comment by korgan00** [comment]
This is not decoration. It is not related to aesthetics. I think this is code-quality

**Comment by eddybrando** [comment]
We already have ESLint configured.
