### ISSUE TITLE
Add page transitions

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2107]
When navigating between routes, Nuxt gives us the option to add transitions pretty easily: https://nuxtjs.org/docs/2.x/features/transitions

This is not only pretty (personal opinion) but also useful for the user to understand navigation changes with visual queues.

**Comment by eddybrando** [comment]
I'm adding the labels "ON HOLD" and "needs information" because of this comment: https://github.com/Qiskit/qiskit.org/pull/3461#issuecomment-1658151968

**Comment by y4izus** [comment]
Per offline conversation, we think this issue is not relevant anymore. We have different "internal" links and not all of them will have the transition, so all the effort we are doing for having an smooth UX between those projects will be losen.
