### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2108]
Given that our textbook supports multiple languages and we probably aim to do the same in the future for the qiskit.org page, we can start by setting up the [nuxt/i18n module](https://i18n.nuxtjs.org/) and basically have everything ready to support multiple languages in the future.

**Comment by korgan00** [comment]
This is not decoration. It is not related to aesthetics.

**Comment by y4izus** [comment]
This issue is no relevant anymore, so I close it
