### ISSUE TITLE
Procedural creation of the textbook landpage logo

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#2129]
We can create procedurally the logo on the [textbook](https://qiskit.org/textbook-beta/)

All the squares can be created procedurally and maybe we can create some kind of animation to appear.

- [ ] stretch goal to use quantum computing for generative header artwork

**Comment by JRussellHuffman** [comment]
Adding on to this one, Can we generate multiple options and have them randomly selected (or cycled through) as the header image when a user loads the page.
