### ISSUE TITLE
Summer School 2020 integration into textbook

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2143]

**Comment by lerongil** [comment]
@frankharkins Can this be closed out now?

**Comment by JRussellHuffman** [comment]
Looks like the PR is still open for this (https://github.com/Qiskit/qiskit.org/pull/2444). @eddybrando is there anything blocking merging this pull request?

**Comment by eddybrando** [comment]
> Looks like the PR is still open for this (#2444). @eddybrando is there anything blocking merging this pull request?

There are some changes that I requested in the code review.

**Comment by eddybrando** [comment]
I'll close this as duplicate because we're tracking the progress or the PR #2444 in https://github.com/Qiskit/qiskit.org/issues/2493.
