### ISSUE TITLE
Create new Overview page for Summer School

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2153]

**Comment by JRussellHuffman** [comment]
Design is here: https://www.figma.com/file/5Fq1Dbxvz7JTTcI5m5BzoS/2146-summer-school?node-id=12%3A3549

Everywhere that has non-placeholder text should be ready to go. Some text is still being finalized. The course pages are still being worked on, so those preview images are still in progress as well.

**Comment by JRussellHuffman** [comment]
The new card for the home page is [here](https://www.figma.com/file/5Fq1Dbxvz7JTTcI5m5BzoS/2146-summer-school?node-id=12%3A1335) as well. There is still some placeholder text, but that will be updated soon.

**Comment by muHashh** [comment]
hello
