### ISSUE TITLE
Update link hover text in textbook

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2158]
In the textbook, the hover style for links is still the default mathigon style. Instead, it should be treated like a regular link  with a standard hover state, for example, the "universal glossary" link on the empty state of "lesson notes.

Example problem:
<img width="427" alt="Screen Shot 2021-09-13 at 4 39 04 PM" src="https://user-images.githubusercontent.com/7633881/133160201-f3aeba2a-38f6-462b-9fc4-60809bda80e7.png">

example solution:
<img width="307" alt="Screen Shot 2021-09-13 at 4 41 22 PM" src="https://user-images.githubusercontent.com/7633881/133160226-e628938f-f72e-4176-baf1-9ac106c48dca.png">

**Comment by vabarbosa** [comment]
thanks @frankharkins for taking a look at this
