### ISSUE TITLE
Identify auth strategies for platypus

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#2161]
Related https://github.com/Qiskit/qiskit.org/issues/2053

**Comment by korgan00** [comment]
The Mathigon studio doesn't have an auth implementation or strategy right now. Phillip is working on an implementation of the auth with facebook, google and it should be easy to create an implementation with the IBM ID. 
If we dont use that implementation, Mathigon is built on top of express, and we can create the auth using it. There are a lot of tutorials about it. To identify the user we can use the IBM ID with SSO following the instructions [here](https://w3.ibm.com/tools/sso).
Mathigon Studio stores data in a [post request](https://github.com/mathigon/studio/blob/35b5711d309c628e38b95dbc072721482bbe25d9/server/app.ts#L261) using a storage object. We provide that [storage](https://github.com/qiskit-community/platypus/blob/main/server/storage.ts) object, so we can modify it easily.

**Comment by vabarbosa** [comment]
@korgan00 thank you! following our conversation, we should have the auth/login plugin within the next couple weeks
