### ISSUE TITLE
Extend PrerequisiteMaterialSection to be more reusable

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2167]
We have two components that are very similar, and they can be abstracted into a single component.

`components/textbook-beta/RelatedMaterialSection.vue`
`components/textbook-beta/PrerequisiteMaterialSection`

The task here is to refactor these into a single component.

**Comment by muHashh** [comment]
hi

**Comment by muHashh** [comment]
hello again
