### ISSUE TITLE
beta banner width

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2185]
On some breakpoints, the beta banner width doesn't stretch the full width of the to of the page, leaving a gap. The banner should take up 100% of the space of that container.
<img width="1456" alt="Screen Shot 2021-09-22 at 1 53 38 PM" src="https://user-images.githubusercontent.com/7633881/134404604-df3287d0-98c0-4e19-b62a-7e4a313b8ad7.png">

**Comment by techtolentino** [comment]
Closing this issue because it was [fixed with this PR](https://github.com/Qiskit/platypus/pull/949)
