### ISSUE TITLE
redirect textbook from qiskit.org/textbook to community.qiskit.org/textbook

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#219]
From https://github.com/qiskit-community/community.qiskit.org/issues/81#issue-492945165:
> In the same way that qiskit.org/education redirects to community.qiskit.org/education, qiskit.org/textbook should lead to community.qiskit.org/textbook.

**Comment by delapuente** [comment]
Redirections are happening because for technical limitations we need to host qiskit-related content under community.qiskit.org. This is planned to be removed and make everything to live under qiskit.org

Are we sure we want the textbook under qiskit.org? @jaygambetta @aasfaw

**Comment by jaygambetta** [comment]
I am good with them under qiskit.org

**Comment by aasfaw** [comment]
Under qiskit.org sounds good to me as well @delapuente
