### ISSUE TITLE
Update summer school events page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit.org#2209]
### Where is the problem?
https://qiskit.org/events/summer-school/

### What is the problem?
Some of the wording on the page makes it sound like you can still register for the summer school:
> Registration is now open! 

> submit an enquiry using the form below!

> Speakers will be announced soon! 

> [Register now](https://www.eventbrite.com/e/qiskit-global-summer-school-2021-quantum-machine-learning-tickets-150081538923)

### What would you expect?

Something like:

> The summer school has now ended, but don't worry; you can view all the lectures and labs online.
> [Check it out](https://qiskit.org/textbook-beta/summer-school/quantum-computing-and-quantum-learning-2021/)

**Comment by y4izus** [comment]
All the registration references were removed https://github.com/Qiskit/qiskit.org/pull/2849, so we can close this issue
