### ISSUE TITLE
As an educator, I want create my own online resource so I can share my expertise.

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit.org#2215]
We want to make it easy for other educators to adapt the textbook to get things online quickly. Some goals might be:
- [ ] Add ability (and guide) to fork the textbook and get something online (maybe with github pages) in 10 minutes
- [ ] Add guide on how to use all the cool features of the textbook

**Comment by lerongil** [comment]
This is a good user story. We should tie this into the #2266 and find out what professors/educators need in order to convert their content into online resources.

**Comment by lerongil** [comment]
We talked about this user story offline a bit, what do you think about the following:

As a professor, I have material that I want my students to access and I need an easy way to share it with them. 

Currently the next best alternative is to upload to some ELMS and notifying via email.

**Comment by frankharkins** [comment]
I think that's ok, but educators won't be able to use the textbook's teaching tools, and it won't encourage them to open up their content for students outside their courses. I think the latter point it quite important as it feeds back into the Qiskit community. Can we discuss at some point?

**Comment by frankharkins** [comment]
Closing as no longer relevant
