### ISSUE TITLE
[Proposal] Keep the events tabs in the mobile version

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/qiskit.org#2246]
When we are on desktop we have tabs:

<img width="1212" alt="Screenshot 2021-10-21 at 17 29 34" src="https://user-images.githubusercontent.com/1007051/138309868-6012499f-71cd-4993-b33e-2d66fc9cf3fb.png">

And when we are on mobile we have a dropdown:

<img width="612" alt="Screenshot 2021-10-21 at 17 29 42" src="https://user-images.githubusercontent.com/1007051/138309923-8027e598-ce12-4a24-8a1b-511366e6c8a0.png">

As we just have two tabs, maybe we can keep the tabs also in mobile?
And let the dropdowns just to the filters (location and types).

**Comment by JRussellHuffman** [comment]
Now that we have a third tab, I don't think this issue is relevant anymore
