### ISSUE TITLE
Updated graphics in Grover page

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2265]
Based on the conversation [here](https://github.com/qiskit-community/platypus/pull/185), there are a handful of new graphics that need to be created for the textbook.

**Comment by lerongil** [comment]
Per offline discussion, we need to have a design and content refactor focused on the basic interactions and visuals throughout the textbook. Probably worthy of a 2 week refactor.

**Comment by JRussellHuffman** [comment]
closing as stale
