### ISSUE TITLE
Enable the deployment for forks

### ISSUE THREAD

**Issue by Tansito** [Qiskit/qiskit.org#2276]
### What is the current behavior?

A PR opened from a fork doesn't have access to secrets so the deployment action doesn't work.

### What is the expected behavior?

Be able to have previews enable with forks too.

**Comment by Tansito** [comment]
As a summary of what I could investigate through GitHub Actions there is no a secure way to be able to guarantee access to the preview from a fork (more info [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). This problem seems to be very common in open-source (an example [here](https://github.com/lit/lit/blob/main/.github/workflows/tests.yml#L72) where some tests are disable from forks).

As a solution to this problem seems to be very common the use of github applications (examples of this use case can be [Netlify](https://github.com/apps/netlify) or the bot from [changesets](https://github.com/apps/changeset-bot)) but they are not as easy to configure as the github actions because you need to develop an application.

Taking into account these points I would say that a middle work effort could be to avoid the github action for forks (like the lit team is doing [here](https://github.com/lit/lit/blob/main/.github/workflows/tests.yml#L74)) to avoid the error from the PR meanwhile we try to prioritise the development of the github app.

**Comment by vabarbosa** [comment]
summary of discussion ... for now we can
- disable previews for forks
- disable previews for draft PRs
- review/update contribution guidelines (regarding previews)
