### ISSUE TITLE
Video link doesn't work

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/qiskit.org#2286]
### Steps to reproduce the problem

1. Go to https://qiskit.org/learn/intro-qc-qh/
2. Click on `Lecture Video` link from Lecture 21

### What is the current behavior?

The video link doesn't work.

### What is the expected behavior?

Change this:
https://youtu.be/ruFzh1NpNF4?list=PLOFEBzvs-VvrXTMy5Y2IqmSaUjfnhvBHR

To this:
https://youtu.be/_IpCwMvc0dA?list=PLOFEBzvs-VvrXTMy5Y2IqmSaUjfnhvBHR

**Comment by Aheal** [comment]
Hi! I wasn't able to self-assign this ticket. I created a PR for it, thanks!

**Comment by eddybrando** [comment]
Thank you very much for your contribution, @Aheal!
