### ISSUE TITLE
Fix the `README.md` problem at experiments during building

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#230]
Although successfull, the [build process in Travis](https://travis-ci.com/qiskit-community/community.qiskit.org/builds/131399369) throws an error related to the `README.md` at `~/content/experiments/`, probably related to trying to parse it as an actual experiment.

**Comment by lerongil** [comment]
@delapuente Is this still a bug?

**Comment by delapuente** [comment]
Yes. It continues giving a warning though it is not breaking the build right now.
