### ISSUE TITLE
Exporting data flow

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2309]
Per GDPR, users have the ability to request whatever data we store on them. This task is to begin listing off user needs that relate to a user exporting their own data.

- [ ] a user should be able to request data
- [ ] a user should be able to see if data has been requested
- [ ] user will receive data

**Comment by JRussellHuffman** [comment]
Working design files are here: https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=618%3A4555

**Comment by JRussellHuffman** [comment]
Final designs are here: https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=666%3A7632
