### ISSUE TITLE
Add theme (light / dark mode) switcher to user dropdown

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2310]

**Comment by JRussellHuffman** [comment]
The design for this is included in the user profile figma file, located here: https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=615%3A4580

The design includes a toggle for light, dark, and system modes.

**Comment by vabarbosa** [comment]
the initial PR (using system preferences): https://github.com/qiskit-community/platypus/pull/143

**Comment by Eric-Arellano** [comment]
When adding dark mode support, see https://github.com/Qiskit/qiskit_sphinx_theme/issues/273 for how to add it to documentation too via the Furo Sphinx theme. We will want to have the toggle live in a generic part of qiskit.org, like the top nav bar. But we can leverage Furo's support for dark mode like it's Sass setup.

**Comment by y4izus** [comment]
We decided to not implement the dark mode, so I close this issue. If at some point we decide to do it, we can create a new issue
