### ISSUE TITLE
[ISSUE-69] Fix nuxt-link navegation between pages

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#232]
Fixes #69

Nuxt-link navegation was broken because function `deepLoadCardToc` is being executed in every page to load its content.

When this happens, there is a markdown import based on `section.collections[aCollection]`, which is an array of strings, that saves its content inside `section.collections[aCollection]` so it becomes into an array of objects.
The problem comes the user comes back to the same path and the import happens again but `section.collections[aCollection]` is no longer an array of strings but an array of objects instead.

That's why I added a condition for the import to only happen if `section.collections[aCollection]` is an array of strings.

Anyways, I still believe that the whole file needs a refactor in the future. The actual import is a bit too difficult.

**Comment by lerongil** [comment]
@delapuente same question here, is this still a problem?

**Comment by delapuente** [comment]
Actually, this issue seems like a PR, probably something we inherited from the previous repo. Closing.
