### ISSUE TITLE
Image asset for a Qiskit Blog

### ISSUE THREAD

**Issue by ryanfmandelbaum** [Qiskit/qiskit.org#2328]
We're writing a Qiskit year-in-review blog and were planning on Working with Russel on large image asset for it.

**Comment by JRussellHuffman** [comment]
Go live date for the blog is set for Dec 15th

**Comment by y4izus** [comment]
This issue seems outdated, @JRussellHuffman , @ryanfmandelbaum , could we close it?

**Comment by techtolentino** [comment]
@y4izus we should definitely close this issue
