### ISSUE TITLE
As a potential attendee, I want to know more about the upcoming events to be aware of what Qiskit community is doing.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#233]
Part of #289

**Comment by lerongil** [comment]
This might be included in this issue #289. If true, let's close this one out.

**Comment by delapuente** [comment]
I changed the wording of the title not to refer to a specific solution but to the value it provides to the user. Don't you prefer to link to #289 instead of closing it?

**Comment by lerongil** [comment]
Sure this works. Thanks.
