### ISSUE TITLE
broken links to labs

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2332]
### Steps to reproduce the problem

1. Go to 'https://qiskit.org/textbook-beta/'
2. Click on the mega menu dropdown
3. Click on any lab
4. get to 404 page

### What is the current behavior?
It looks like the URLs are incorrect. For example
The wrong URL is: https://learn.qiskit.org/course/ch-labs/lab-7-quantum-simulation-as-a-search-algorithm
The right URL is : https://learn.qiskit.org/course/ch-labs/lab-7-grovers-search-with-an-unknown-number-of-solutions

### What is the expected behavior?
The mega menu on the home page should be the same as the mega menu on the content pages

### Screenshots (optional but very helpful)
incorrect link
<img width="1370" alt="Screen Shot 2021-11-30 at 9 34 22 AM" src="https://user-images.githubusercontent.com/7633881/144079511-a373ca98-abb5-46f3-8dd7-9adea2f76cc0.png">

correct link
<img width="1650" alt="Screen Shot 2021-11-30 at 9 35 13 AM" src="https://user-images.githubusercontent.com/7633881/144079537-d5a0c7fe-68e6-4cec-8d31-4a9166990552.png">

### Environment (optional but very helpful)
 - all

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by vabarbosa** [comment]
`qiskit.org` PR: https://github.com/Qiskit/qiskit.org/pull/2337

`textbook` PR: https://github.com/qiskit-community/platypus/pull/217
