### ISSUE TITLE
Homepage: Implement scroll component for "What Can Qiskit Do" section

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2334]
Designs can be found [here](https://www.figma.com/file/ndskBjmtWzjhdPCRrwMGBi/2009-home-page-key-features?node-id=119%3A11778)

**Comment by vabarbosa** [comment]
Closing as #2361 has been merged.
please re-open if necessary

**Comment by techtolentino** [comment]
This can be closed, however there's a larger issue that's preventing the effect from showing. We're tracking that issue [here](https://github.com/Qiskit/qiskit.org/issues/2411)
