### ISSUE TITLE
Homepage: Open code snippet in "What Can Qiskit Do" section in Quantum Lab

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2336]
- [x] create the notebook w/ the code snippet
    - https://github.com/qiskit-community/platypus/blob/stable/notebooks/getting-started/example.ipynb
- [x] coordinate w/ Quantum Lab team to upload notebook 
- [x] link to the uploaded notebook
    - https://quantum-computing.ibm.com/lab/files/qiskit-textbook/getting-started/example.ipynb

**Comment by vabarbosa** [comment]
is there  a preference for where this notebook would reside and should be surfaced?

currently, [notebooks from original textbook repo](https://github.com/qiskit-community/qiskit-textbook/tree/stable/content) are available within QL at https://quantum-computing.ibm.com/lab/files/qiskit-textbook/content

one option is to just add the notebook into the original textbook repo and it gets surfaced by default alongside the existing notebooks. this would be the quickest approach, but probably not ideal.

i think it makes more sense for this code snippet notebook to reside in the [platypus repo](https://github.com/qiskit-community/platypus/tree/main/notebooks). it can then be made available alongside the existing notebooks in QL (i.e., `qiskit-textbook/content`) or at a different location, e.g., `qiskit-textbook/intro`. this approach does require coordination with QL team.

any comments, feedback, or preference is appreciated.

CC: @frankharkins @JRussellHuffman @lerongil

**Comment by JRussellHuffman** [comment]
Would it be feasible to do the more ideal version before end of year? What can actually be done might be the main driver here.

**Comment by vabarbosa** [comment]
@JRussellHuffman speaking with QL team, they will try to get it working this week.
i have the [notebook is currently here](https://github.com/qiskit-community/platypus/blob/stable/notebooks/getting-started/example.ipynb) let me know if anything needs to be updated/changed in the notebook.

**Comment by vabarbosa** [comment]
@JRussellHuffman FYI, the update to make the notebook/code snippet available in QL has been completed by the QL team. can you confirm the [notebook/code snippet](https://github.com/qiskit-community/platypus/blob/stable/notebooks/getting-started/example.ipynb) is as expected? after that i can request the QL update be pushed to production.

once pushed to production the notebook will be available in QL at this URL: 

- https://quantum-computing.ibm.com/lab/files/qiskit-textbook/getting-started/example.ipynb


CC @techtolentino, this is the URL you will need for the `Open in Quantum Lab` CTA

**Comment by JRussellHuffman** [comment]
@vabarbosa the code snippet is finalized here: https://github.com/Qiskit/qiskit.org/issues/2009#issuecomment-984905531

I will add it to Figma file, but reference that github issue as the "source of truth", in case anything changes in the discussion there.

**Comment by vabarbosa** [comment]
the code snippet is available in Quantum Lab:

- https://quantum-computing.ibm.com/lab/files/qiskit-textbook/getting-started/example.ipynb

any additional changes to the notebook should be done here:

- https://github.com/qiskit-community/platypus/blob/stable/notebooks/getting-started/example.ipynb

and then a new PR should be submitted to QL team to rebuild image
