### ISSUE TITLE
Unify the Qiskit Digital projects under Qiskit organization

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/qiskit.org#2363]
We started managing the Qiskit Digital sprints in a [GitHub Project from `Qiskit/qiskit.org`](https://github.com/Qiskit/qiskit.org/projects/10).

But currently we have more repositories in other organization:

- [Qiskit/qiskit.org](https://github.com/Qiskit/qiskit.org)
- [qiskit-community/platypus](https://github.com/qiskit-community/platypus)
- [qiskit-community/web-components](https://github.com/qiskit-community/web-components)
- [qiskit-community/qiskit-vue](https://github.com/qiskit-community/qiskit-vue)

#### Issue

Since we cannot link issues/PRs from repositories of other organizations in the GitHub Project, we have been forced to duplicate many issues in the `qiskit.org` repository, which makes it much more difficult for us to manage.

#### Proposed solution

After having discussed it in the Qiskit Digital team, we want to create a [GitHub Project in the organization](https://github.com/orgs/Qiskit/projects/2) (instead of in the repository), where we can manage everything more easily. With this, each repository can have its own issues linked in the organization's project.

## First step

Now we have two teams in the Qiskit organization:

- [github.com/orgs/Qiskit/teams/qiskit-digital](https://github.com/orgs/Qiskit/teams/qiskit-digital)
- [github.com/orgs/Qiskit/teams/qiskit-digital-devs](https://github.com/orgs/Qiskit/teams/qiskit-digital-devs)

And both with `Qiskit/qiskit.org` repo:

- [github.com/orgs/Qiskit/teams/qiskit-digital/repositories](https://github.com/orgs/Qiskit/teams/qiskit-digital/repositories)
- [github.com/orgs/Qiskit/teams/qiskit-digital-devs/repositories](https://github.com/orgs/Qiskit/teams/qiskit-digital-devs/repositories)

Thanks @vabarbosa for this! 👏🏻 

## Next steps

- [x] Transfer [qiskit-community/platypus](https://github.com/qiskit-community/platypus) to Qiskit organization [[link to transfer it](https://github.com/qiskit-community/platypus/settings#danger-zone)]
  - [x] Merge https://github.com/qiskit-community/platypus/pull/183
- [x] Transfer [qiskit-community/web-components](https://github.com/qiskit-community/web-components) to Qiskit organization [[link to transfer it](https://github.com/qiskit-community/web-components/settings#danger-zone)]
  - [x] Merge https://github.com/qiskit-community/web-components/pull/54
- [ ] ~~Transfer [qiskit-community/qiskit-vue](https://github.com/qiskit-community/qiskit-vue) to Qiskit organization? [[link to transfer it](https://github.com/qiskit-community/qiskit-vue/settings#danger-zone)]~~ Discontinued soon?
- [x] Add repositories to the Qiskit Digital teams:
  - [x] [`qiskit-digital` team](https://github.com/orgs/Qiskit/teams/qiskit-digital/repositories) with **Triage** permission level?
    _Can read and clone this repository. Can also manage issues and pull requests._
  - [x] [`qiskit-digital-devs` team](https://github.com/orgs/Qiskit/teams/qiskit-digital-devs/repositories) with **Maintain** permission level?
    _Can read, clone, and push to this repository. They can also manage issues, pull requests, and some repository settings._
- [x] Enable Projects in the Qiskit organization. [[link to do it](https://github.com/organizations/Qiskit/settings/projects)]
- [x] Create a new project in the Qiskit organization. [[link to create it](https://github.com/orgs/Qiskit/projects)]

## Final step

- [ ] Start using the new project for the sprints 🎉 
  - https://github.com/orgs/Qiskit/projects/2

---

Related: https://github.com/qiskit-community/platypus/issues/182

**Comment by lerongil** [comment]
This looks like a good plan to me. Thanks for setting it up Va and Abdon.

**Comment by abdonrd** [comment]
I just added the references to:

- https://github.com/qiskit-community/platypus/pull/183
- https://github.com/qiskit-community/qiskit-web-components/pull/54

**Comment by abdonrd** [comment]
Now we also can start transferring issues from Qiskit/qiskit.org to Qiksit/platypus

We can find them filtering by:
- label: https://github.com/Qiskit/qiskit.org/issues?q=is%3Aissue+label%3A%22project%3A+textbook+beta%22+
- keyword: https://github.com/Qiskit/qiskit.org/issues?q=is%3Aissue+platypus+
