### ISSUE TITLE
Create a reusable GitHub Action to deploy to IBM Container Registry

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2398]
Currently we have a couple of projects that deploy to IBM Code Engine and use the IBM Container Registry.

For this, we're duplicating some code for the GitHub CI/CD workflows in each repository, which could be reused if available as a GitHub Action.

We should DRY this by creating a reusable GitHub Action.

**Comment by abdonrd** [comment]
We still need to reuse the cleanup workflow.
