### ISSUE TITLE
[Deployments] IBM Cloud Code Engine random timeouts

### ISSUE THREAD

**Issue by Tansito** [Qiskit/qiskit.org#2406]
### What is the current behaviour?

Currently IBM Cloud Code Engine returns from time to time random timeouts that are difficult to recognise from another errors.

### What is the expected behaviour?

It's difficult to avoid this situation due to the external tool but we can try to reduce the impact or the number of these errors through some retries and another solutions in the workflow.

### Screenshots (optional but very helpful)

![image](https://user-images.githubusercontent.com/9059044/148521578-2868a8f0-6032-4c8c-9444-e6b427d932a6.png)

### Additional context (optional)

Issue related with: #2395

**Comment by vabarbosa** [comment]
perhaps we can try to set/increase the [`--wait-timeout` flag](https://cloud.ibm.com/docs/codeengine?topic=codeengine-cli#cli-application-update) for the CE CLI. otherwise, we could take a look at the [retry step action](https://github.com/marketplace/actions/retry-step).

**Comment by y4izus** [comment]
It looks like we stopped having this issue, so I will close it. If we experience this again, we can reopen the issue

**Comment by Tansito** [comment]
Just FYI @vabarbosa I was talking with @y4izus if we can close this issue or not. My impression is that the deployment process looks more stable and we didn't have this error anymore so we saw it fine close it by now.
