### ISSUE TITLE
the `scrollBetweenSections` mixin is no longer working

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2411]
### Steps to reproduce the problem

1. Go to qiskit.org/overview or qiskit.org/metal
2. Scroll down the page
4. See that the scroll effect isn't working

### What is the current behavior?

The `scrollBetweenSections` mixin used to produce an effect, where as the user scrolls up/down the page, corresponding sections would become active. 

Currently, there is no corresponding interaction.

### What is the expected behavior?

For the `/overview` page, when the user scrolls, we should see the _'page list of contents'_ activate other sections, starting with `Applications`, then `Algorithms`, and so forth.

For the `/metal` page, underneath the section called "Our vision", the images on the right should change, as the user scrolls up/down.

### Screenshots (optional but very helpful)

https://user-images.githubusercontent.com/6276074/148957131-bf89960e-48da-44d5-8743-1ffca9043c37.mov

https://user-images.githubusercontent.com/6276074/148957170-487f99ca-84a9-4f1d-8faf-7837e3ae5583.mov

**Comment by vabarbosa** [comment]
@abdonrd this looks like it is related to running `nuxt generate` (& target static). do you happen to know why the `scrollBetweenSections` mixin would work when you run `nuxt run dev` but does not work with `nuxt generate`?

**Comment by vabarbosa** [comment]
Resolved by https://github.com/Qiskit/qiskit.org/pull/2427
