### ISSUE TITLE
As an Event organizer, I want to be able to request a new event, and see a list of published events

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2413]

**Comment by lerongil** [comment]
@techtolentino can you share some more context on the request a new event ask? Does this current page offer an appropriate solution for the "see a list of published events": www.qiskit.org/events

**Comment by techtolentino** [comment]
@lerongil - I wrote this story as a placeholder for Alberto (not sure of his GitHub username). I'll tag him in this issue (via Slack), and let him expand on what he was envisioning.

**Comment by techtolentino** [comment]
I think this is solved for: case in point, we recently were able to create a new event based on a request from @justjosie (Summer School 2022).

Closing for now.
