### ISSUE TITLE
Transfer issues from Qiskit/qiskit.org to Qiskit/platypus

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/qiskit.org#2415]
After:
- https://github.com/Qiskit/qiskit.org/issues/2363

---

From https://github.com/Qiskit/qiskit.org/issues/2363#issuecomment-1007371210:

> Now we also can start transferring issues from Qiskit/qiskit.org to Qiksit/platypus
> 
> We can find them filtering by:
> - label: https://github.com/Qiskit/qiskit.org/issues?q=is%3Aissue+label%3A%22project%3A+textbook+beta%22+
> - keyword: https://github.com/Qiskit/qiskit.org/issues?q=is%3Aissue+platypus+
>

**Comment by abdonrd** [comment]
Also related with this: https://github.com/Qiskit/qiskit.org/issues/2426

**Comment by eddybrando** [comment]
Transferred all issues from **Qiskit/qiskit.org** that had the Textbook labels to **Qiskit/platypus**.
