### ISSUE TITLE
Temporarily remove new homepage scroll highlighting styling

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2419]
Currently, the `scrollBetweenSections` mixin isn't working as expected. To give the the team the ability to still ship new homepage updates, we can remove the styling for _section highlighting_, for now.

- [x] remove scroll-based styling/highlighting on the new homepage
- [x] the PR should be made into the `feature/new-homepage` branch

Note: the issue with the mixin is part of a bigger issue that's being worked on in #2411. Once the mixin is working, we can create a new issue and reintroduce the section highlighting.

**Comment by abdonrd** [comment]
Closed by https://github.com/Qiskit/qiskit.org/pull/2420
