### ISSUE TITLE
Onboarding document

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2435]

**Comment by pandasa123** [comment]
@JRussellHuffman, is this for which questions we should ask during onboarding? If so, [here's a link with questions](https://ibm.ent.box.com/notes/908067118687) from Fang

**Comment by JRussellHuffman** [comment]
Awesome, I didn't know that document existed, thanks for sharing. It's meant a little more broadly as an on-boarding document. I believe there are a handful of boilerplate on-boarding docs floating around, but we have a few folks joining soon, so it would be good to prep one of those on-boarding docs for the new members.

**Comment by pandasa123** [comment]
Ah got it! I'll create a separate issue for the onboarding user story

**Comment by techtolentino** [comment]
This is no longer a part of qiskit org work. Closing.
