### ISSUE TITLE
As a learner, I want the best learning experience on the phase kickback page, so that I can understand the concepts as thoroughly as possible.

### ISSUE THREAD

**Issue by sderakhshandeh** [Qiskit/qiskit.org#2437]
# Phase Kickback

### Interactive components
- [ ] eigenstate component
  - [x] how to make interactive
  - [x] visual design ([figma file](https://www.figma.com/file/0TXUEi2TimMttJH7KUwRti/Algorithms-course?node-id=190%3A4558))
  - [x] implementation https://github.com/Qiskit/platypus/issues/699
  - [ ] use component in chapter(s)
- [ ] phase kickback component
  - [x] how to make interactive
  - [x] visual design ([figma file](https://www.figma.com/file/0TXUEi2TimMttJH7KUwRti/Algorithms-course?node-id=299%3A5308))
  - [x] implementation
  - [ ] use component in chapter(s)

### Basic components (check off when component is used)
- [ ] math annotations
- [ ] vocab annotations
- [ ] redraw circuit to match colors, etc
- [ ] rewrite content

**Comment by JRussellHuffman** [comment]
Updating the scope of this user story to reflect just the phase kickback component. After this is complete, the next items should be
- [ ] Fourier Transform 
- [ ] Phase Estimation

**Comment by JRussellHuffman** [comment]
@eddybrando did you mean to reopen this issue?
