### ISSUE TITLE
Default layout CSS is bleeding to other layouts not inheriting from it

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#245]
It seems to be related to https://github.com/nuxt/nuxt.js/issues/3877 Keep open until we can provide a permanent solution.

**Comment by lerongil** [comment]
Is this still an issue?

**Comment by delapuente** [comment]
It is. Also related to #271

**Comment by delapuente** [comment]
Should take a look at https://github.com/nuxt/nuxt.js/issues/3877#issuecomment-669501682 in case it fixes it.

**Comment by delapuente** [comment]
We partially addressed this using BEM. Closing although the issue could reappear.
