### ISSUE TITLE
No Response to "Run" 

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/qiskit.org#2463]
### Steps to reproduce the problem

1.  go to https://learn.qiskit.org/course/ch-labs/lab-6-scalable-shors-algorithm
2. Click on the first "Run" for Lab 6 Scalable Shore's Algorithm
2. See lack of response

### What is the current behavior?

When one attempts to run the code, the page doesn't respond.

### What is the expected behavior?

When should be able to run the code.

### Environment (optional but very helpful)
 - Device: MacBook Pro
 - OS: OSX
 - Browser: Safari

**Comment by jackoconnordev** [comment]
This page no longer exists so this issue should be closed right?
