### ISSUE TITLE
Link in "Overview" page gets redirected to another page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2464]
### Steps to reproduce the problem

1. Go to https://qiskit.org/overview/#applications
2. Open the "Finance" tab
3. Click on the link "Perform Option Pricing with qGans"
4. See how the page gets redirected from https://qiskit.org/documentation/tutorials/finance/10_qgan_option_pricing.html to https://qiskit.org/documentation/finance/tutorials/index.html

### What is the current behavior?

The link to an specific tutorial gets redirected to the index of tutorials.

### What is the expected behavior?

When clicking the user should land on the specific tutorial.

### Screenshots (optional but very helpful)

![image](https://user-images.githubusercontent.com/22047320/151399854-5135c691-80bf-43e8-b5c8-42467a643f8c.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser: Chrome

**Comment by techtolentino** [comment]
This was also resolved with https://github.com/Qiskit/qiskit.org/pull/2508

You can see the new links at https://qiskit.org/overview/#applications
