### ISSUE TITLE
"Name Error" in Code Cell

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/qiskit.org#2465]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-labs/lab-2-single-qubit-gates
2. Click on Run for # Plot blochshere
3. See "NameError: name 'backend' is not defined"

### What is the current behavior?

When the user clicks Run for any of the 6 # Plot blochshere cells,  NameError: name 'backend' is not defined pops up.

### What is the expected behavior?

When the user clicks Run for any of the 6 # Plot blochshere the code should run without error.

### Screenshots (optional but very helpful)
<img width="701" alt="Screen Shot 2022-01-27 at 11 29 07 AM" src="https://user-images.githubusercontent.com/89415444/151401446-0c3e2629-5b29-4912-a6b5-38870c13caf4.png">
<img width="710" alt="Screen Shot 2022-01-27 at 11 29 16 AM" src="https://user-images.githubusercontent.com/89415444/151401450-56432bb2-79f0-42e4-bd95-440acb8efc99.png">

If applicable, please add screenshots or video captures to help explain the problem.

### Environment (optional but very helpful)
 - Device: MacBook Pro
 - OS: OSX
 - Browser: Safari

**Comment by eddybrando** [comment]
Cannot reproduce this bug anymore.
