### ISSUE TITLE
Broken links on qiskit.org overview page

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2480]
### Steps to reproduce the problem

1. Go to https://qiskit.org/overview
2A. Click on "see docs" under Research Applications
2B. Click on "see docs" under Collection of Algorithms

### What is the current behavior?

both links are 404

### What is the expected behavior?

Link to appropriate pages in docs, which may need to be new links altogether. let's discuss.

### Environment (optional but very helpful)
 - all

### Additional context (optional)

This probably happened when aqua and terra were deprecated. This may be more than relinking.

**Comment by JRussellHuffman** [comment]
Found more:

- all links under Collection of Algorithms, include Grovers, VQE, QAOA, QSVM

**Comment by eddybrando** [comment]
Related to https://github.com/Qiskit/qiskit.org/issues/2464

**Comment by eddybrando** [comment]
Related to https://github.com/Qiskit/qiskit.org/issues/2462

**Comment by techtolentino** [comment]
Didn't see this issue, but this was resolved by https://github.com/Qiskit/qiskit.org/pull/2508

You can see the fixes on https://qiskit.org/overview 

Closing 👏🏽
