### ISSUE TITLE
Sass division deprecation warnings

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2482]
### Steps to reproduce the problem

1. Build the app in your local terminal
2. See warnings

### What is the current behavior?

When building the application locally, we see the deprecated warnings in the console

### What is the expected behavior?

We shouldn't see these warnings anymore

### Screenshots (example of sass warnings)
![Screen Shot 2022-02-08 at 7 00 49 AM (2)](https://user-images.githubusercontent.com/6276074/153015344-c81b69a1-78a5-435e-8e57-ae8e3ae32de4.png)

**Comment by eddybrando** [comment]
The deprecation warning isn't there any more. This was probably solved with another update.

![Screenshot 2022-02-21 at 14 56 06](https://user-images.githubusercontent.com/22047320/154969432-fafbe5ba-28ae-48b5-8fc7-80aec6279e1a.png)

**Comment by techtolentino** [comment]
FYI, platypus saw new warnings when upgrading to `sass-mq v 6.0.1`. If/when this repo upgrades it's sass-mq package, we'll probably see warnings here too.
