### ISSUE TITLE
Broken links on Overview page

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2496]
There are several broken links on the overview page, with the recent aqua deprecation. 

The fixes are mostly updated links, but for clarity, I put everything in a figma file: https://www.figma.com/file/vxmMO1ii3qEQdYmohkmlC9/overview-page-update?node-id=0%3A1

Below is the recommended new links from Stefan Worner:

> 1. Fist shows broken link
>
> 2. Shows the new or new links
> 
> Applications
> 
> https://qiskit.org/documentation/apidoc/aqua.html
> https://qiskit.org/documentation/machine-learning/
> https://qiskit.org/documentation/nature/
> https://qiskit.org/documentation/finance/
> https://qiskit.org/documentation/optimization/
> 
> https://github.com/Qiskit/qiskit-aqua#creating-your-first-optimization-programming-experiment-in-qiskit
> https://qiskit.org/documentation/optimization/tutorials/01_quadratic_program.html
> 
> https://qiskit.org/documentation/tutorials/finance/10_qgan_option_pricing.html
> https://qiskit.org/documentation/finance/tutorials/10_qgan_option_pricing.html
> 
> https://github.com/Qiskit/qiskit-aqua#creating-your-first-machine-learning-programming-experiment-in-qiskit
> https://qiskit.org/documentation/machine-learning/tutorials/01_neural_networks.html
> 
> https://github.com/Qiskit/qiskit-aqua#creating-your-first-chemistry-programming-experiment-in-qiskit
> https://qiskit.org/documentation/nature/tutorials/01_electronic_structure.html
> 
> 
> Algorithms
> 
> https://qiskit.org/documentation/apidoc/qiskit.aqua.algorithms.html#algorithms-qiskit-aqua-algorithms
> https://qiskit.org/documentation/apidoc/algorithms.html
> 
> https://qiskit.org/documentation/stubs/qiskit.aqua.algorithms.Grover.html#qiskit.aqua.algorithms.Grover
> https://qiskit.org/documentation/stubs/qiskit.algorithms.Grover.html#qiskit.algorithms.Grover
> 
> https://qiskit.org/documentation/stubs/qiskit.aqua.algorithms.VQE.html#qiskit.aqua.algorithms.VQE
> https://qiskit.org/documentation/stubs/qiskit.algorithms.VQE.html#qiskit.algorithms.VQE
> 
> https://qiskit.org/documentation/stubs/qiskit.aqua.algorithms.QAOA.html#qiskit.aqua.algorithms.QAOA
> https://qiskit.org/documentation/stubs/qiskit.algorithms.QAOA.html#qiskit.algorithms.QAOA
> 
> https://qiskit.org/documentation/apidoc/qiskit.aqua.algorithms.html#classifiers
> https://qiskit.org/documentation/machine-learning/apidocs/qiskit_machine_learning.algorithms.html#classifiers

**Comment by JRussellHuffman** [comment]
Given the above, we now need to include 4 links under "research applications".

We may want to update some of the language on the page, given the updates.
For example, we could update "Research Applications" to just "Applications". And we could change "QSVM" (the last link) to "classifiers" because the link seems more general now. However, we would probably need to update the text too, so maybe this one is best staying as is. 
@lerongil what do you think?

**Comment by eddybrando** [comment]
@frankharkins there might be some content changes needed here. Could you help us out with this, please? 🙂

**Comment by frankharkins** [comment]
This is https://qiskit.org/overview/? Looks ok to me
