### ISSUE TITLE
As a developer, I want to understand the entire qiskit ecosystem so that I can take advantage of everything that is offered

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2503]
Related to https://github.com/Qiskit/qiskit.org/pull/2258

acceptance criteria:
- [ ] finalize designs based off draft created by Abby Mitchell in the above PR
- [ ] determine page location and navigation within Qiskit.org

**Comment by JRussellHuffman** [comment]
Designs can be found here: https://www.figma.com/file/N34caXM86bY1778Whk1c31/2503-ecosystem-page?node-id=64%3A5897

**Comment by eddybrando** [comment]
@JRussellHuffman is this a user story? If so, we should probably change the status to "User story" and create individual issues for each of the tasks described by the acceptance criteria.

**Comment by JRussellHuffman** [comment]
Yes, we probably should, but most of the development effort is being taken care of by Abby Mitchell (not sure her github handle to tag her) and @y4izus. 

It's still worth breaking out into tasks, because this page should link off of the community tab in our header.

**Comment by 1ucian0** [comment]
Is this still pending?

**Comment by JRussellHuffman** [comment]
Nope. This was the story to track the design and the design is done. Closing.
