### ISSUE TITLE
 As the Qiskit team, we want to have better control over the blog

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#251]

**Comment by lerongil** [comment]
This is missing an action. One suggested action: 

As the Qiskit team, we want to have better control over the blog so that we can provide them for free to all users.

**Comment by delapuente** [comment]
I think the point of having it integrated in community.qiskit.org is that we can control every aspect of it, from UI to the metrics we are tracking.

**Comment by lerongil** [comment]
I don't think there is anything wrong with the UI and metrics as they stand. The main issue right now is that Medium has changed their policies around reading blogs and have implemented a pay wall: https://help.medium.com/hc/en-us/articles/360018834314-Stories-that-are-part-of-the-metered-paywall

**Comment by delapuente** [comment]
Leron, if the pay wall is a problem but we are happy with everything else, would you mind changing the name of the issue or close it completely?

**Comment by delapuente** [comment]
Pinging @marinaaisa before closing the issue since this was something brought to the table by her. Perhaps she has a more compelling argument for leaving it open.

**Comment by lerongil** [comment]
@CatherineKlauss will also have thoughts on this.

**Comment by CatherineKlauss** [comment]
several reasons for internal blog over medium blog:
> so that visitors to website see recent blog posts
> reader stats on blog indicate that only ~10% of readers come from medium, most come from IBM websites and qiskit.org, (if and only if blog post is posted there, which usually, it is not, so we can infer that putting blog posts on qiskit.org will dramatically increase readership)
> medium has at times deleted content, backdated posts, and more, when blogs are scheduled to post next day.

**Comment by CatherineKlauss** [comment]
I'd also like to have more options about how we can format a blog post. Medium has limited style and format options. And we don't have the option to suggest to readers at the end of a blog post the next blog post or two that might interest them.

**Comment by delapuente** [comment]
Integrating blog capabilities in the site is feasible and challenging. We should consider this like an epic and list the problems we try to solve before considering integrating it in the site, in case a more simple solution and specific solution (like Workdpress) is available.

**Comment by CatherineKlauss** [comment]
I agree that it should be an epic and that more thought should be put into what are the capabilities we want on an internal blog. 

This past week medium hit an issue embedding youtube videos and still hasnt fixed it. Id prefer to move in house, or atleast integrate a more customizable blog format into our website. Wordpress integrated into the website would be great.

**Comment by lerongil** [comment]
Agreed on this possibly being an epic vs as an issue. I will connect with Catherine to weigh our options.
