### ISSUE TITLE
Investigate ways of speeding up development experience

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2515]
One of the points brought up during our retro meeting on March 4th 2022 was the speed of development, which has been slowing down recently.

There are many factors out of our control (more complex tasks, less resources) but there might certainly also still be ways to improve the developer experience to increment our delivery velocity.

We need to investigate some ways of improving in this regards and create other action items to implement them.

**Comment by y4izus** [comment]
@eddybrando , I think we can close this issue. If you agree, please, close it

**Comment by y4izus** [comment]
Per offline conversation, we can close this issue
