### ISSUE TITLE
Example code in the main page has unrelated comments

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2517]
### Where is the problem?

In the main page, there the code example has comments that make no sense in that context:

<img width="694" alt="Screenshot 2022-03-08 at 17 29 41" src="https://user-images.githubusercontent.com/766693/157282728-29c62dd1-9e64-4923-abfe-d1a31f50dade.png">

### What is the problem?

When I suggested the snippets in https://github.com/Qiskit/qiskit.org/issues/2009#issuecomment-896101956 for the main page, I was adding `#N` as a way to refer to the `N` line. That was not supposed to be part of the thing :P 

### What would you expect?

Remove the comments from the code:

```
import qiskit
 
# Qiskit quantum circuits libraries
quantum_circuit = qiskit.circuit.library.QuantumVolume(5)
quantum_circuit.measure_all()
quantum_circuit.draw()
```
```
# prepare your circuit to run
from qiskit import IBMQ 
IBMQ.save_account("YOUR TOKEN")  # Get the API token in https://quantum-computing.ibm.com/
 
provider = IBMQ.load_account()
backend = provider.get_backend('ibmq_quito')
 
optimized_circuit = qiskit.transpile(quantum_circuit, backend) 
optimized_circuit.draw()
```
```
# run in real hardware
job = backend.run(optimized_circuit)
retrieved_job = backend.retrieve_job(job.job_id())
result = retrieved_job.result()
print(result.get_counts())
```

**Comment by techtolentino** [comment]
The unnecessary code comments were removed as a part of [this PR](https://github.com/Qiskit/qiskit.org/pull/2626)
