### ISSUE TITLE
As a designer, developer, or product manager, I want to restructure our existing platform, so that our product gets easier to maintain and extend.

### ISSUE THREAD

**Issue by AGFQ** [Qiskit/qiskit.org#2523]
In order to start the refactor sprint, we should add issues to the backlog and vote on them by 5/8. If the issue is something you believe is important add a  👍 and if it's something you want to work on, add a ❤️. Each person has 3 👍 and 3 ❤️. May the best code quality issues win! 

Acceptance Criteria:

- [ ] At least 80% of the defined list

**Comment by pandasa123** [comment]
From a Product perspective, we have a few QoL issues that slow us down:

- We have a "[pitchdeck](https://ibm.ent.box.com/file/928921885254)", but we need a better single document to communicate these features asynchronously
- We need to figure out who we're talking to next into a [pipeline](https://airtable.com/appWWn73vHQHQCC2k/tblrAlvPnFWjqswgl/viwTKYeXslf9S0NEG?blocks=hide)
- Let's revisit the roadmap as well...do we feel that Professors have everything they _need_ for Fall semester?

**Comment by JRussellHuffman** [comment]
From the design side, we need to

- organizing all visual assets into the correct box folders
- rebuild qiskit figma components with the new carbon components
- move brand book to final asset folder

**Comment by lerongil** [comment]
Great work everyone! Awesome refactor sprint.
