### ISSUE TITLE
As a product stakeholder, I want to set measurable goals so that I can assess how new products are performing.

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit.org#2536]
This story is to help product owners to account for users needs and behaviors when creating success metrics for new or existing products.

**Acceptance Criteria:**

For documentation:

- [x] Need to create an estimate for how many users are visiting the documentation page to set as a baseline.
- [ ] Needs to instrument basic tracking to that we can track page views and basic metrics over time as new features and changes are released. -> added [here](https://github.com/Qiskit/qiskit_sphinx_theme/issues/60)

**Comment by y4izus** [comment]
Hey @agebbie , it looks like the two tasks you mentioned on your comment are completed, could we say this issue is finished and close it?

**Comment by y4izus** [comment]
Per offline conversations, we can close this issue
