### ISSUE TITLE
Site visitors have a consisten experience on all webpages.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#254]
For instance, standarize the headers of qiskit.org-related websites

**Comment by lerongil** [comment]
Where are the headers not standard currently?

**Comment by delapuente** [comment]
Right now, the header of https://qiskit.org, https://community.qiskit.org and https://qiskit.org/documentation are different although those from https://qiskit.org and https://community.qiskit.org looks identical.

**Comment by delapuente** [comment]
This will be completely mitigated after merging #258 and https://github.com/Qiskit/qiskit/pull/662

**Comment by delapuente** [comment]
#258 is done, there is now no difference among headers.
