### ISSUE TITLE
Qiskit Global Summer School design support

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2545]
The 2022 Qiskit Global Summer School is coming up, and they have requested support in creating a look and feel for the event, which includes:
- [x] certificates
- [x] hero image
- [x] wordmark
- [x] 3 icon sized things for different assets (footers, headers, etc)
- [ ] nice to have
    - [ ] wallpapers
    - [ ] emojis
 - [x] Cover slide

This year's emphasis is on quantum simulation

**Comment by y4izus** [comment]
We are on 2023 🎉 , so I think this issue is outdated. @JRussellHuffman , can we close it?

**Comment by JRussellHuffman** [comment]
yes indeed, closing!
