### ISSUE TITLE
Contributors Flow Chart

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/qiskit.org#2547]
a flow chart guide visualizing different options a user can take in order to get involved with contributing to Qiskit

https://www.figma.com/file/LImIi3eBtPNfCap76aX2xb/Contributors-Flow-Chart?node-id=0%3A1

**Comment by JRussellHuffman** [comment]
it looks like this, but I'm not sure what we ended up doing with it. We can reopen if the need arises again.
