### ISSUE TITLE
Qiskit Metal design support

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2549]
This issue is to track the design work happening for Qiskit Metal as a side project. We recently finished a design thinking workshop to understand their design needs. Based on those findings, we will be working through the UI and UX of Qiskit Metal.

**Comment by JRussellHuffman** [comment]
Figma file: https://www.figma.com/file/11vZ7xpd6MGikgvotUTAbZ/2549-Qiskit-metal-UX?node-id=0%3A1

**Comment by techtolentino** [comment]
Update:

Today we had a playback with the Metal team, to share some design work that we've been doing:
- UI components in Figma
- UX improvements to two pain-points uncovered in the design thinking workshop
- Research plan

We'll be revisiting some of the designs and components, based off of feedback from the team. Once we have research findings, we'll package up the work for the Metal team.

**Comment by techtolentino** [comment]
Since we've delivered the final Qiskit Metal Design Guidelines to the Metal team, I'm marking this as closed. 

If there are any questions regarding the deliverables, please reach out.

🎉

**Comment by JRussellHuffman** [comment]
Thanks for all the hard work and commitment on this Randy. There is a lot to be proud of in what was delivered.
