### ISSUE TITLE
Users have a better user experience on the website 

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#255]
See the redesign on-going effort.

**Comment by lerongil** [comment]
This seems too vague. Let's close this or edit to be more specific.

**Comment by delapuente** [comment]
I exect this will start to grow as soon as we start the redesign effort. Anyways, more than a user story, I see this as an epic. What do you think?

**Comment by lerongil** [comment]
yes I would agree but it should grow into different issues

**Comment by delapuente** [comment]
Ok, let's close it then.
