### ISSUE TITLE
Admins want to make informed decisions based on site metrics

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#256]
Integrate with analytics for providing better metrics.

**Comment by francabrera** [comment]
so two things would be required:
- [ ] Make sure all titles are correctly sent. In some pages the title sent with the events is not the right one (like for example `title: 'index'`).
- [ ] Include an alternative `name` to the page that we can use for the charts as an unique identifier, independent of any URL or Title changes over time.
