### ISSUE TITLE
Update course overview pages header background

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2577]
The Course Overview page component should not have a grid in its header background.

This issue is to create or modify page templates so that the overview page headers do not have a grid.

[Designs shown here](https://www.figma.com/file/X9p7omJAZncvDpg2IJLS6J/407-learn-page-migration?node-id=184%3A775)

**Comment by eddybrando** [comment]
Closes with https://github.com/Qiskit/qiskit.org/pull/2604
