### ISSUE TITLE
Quantum Scouts Design Support

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/qiskit.org#2578]
The Quantum Scouts program (a modular learning initiative primarily for women and girls in India and Asia West new to quantum) is this summer. Design support is needed in the following areas

- [ ] Locked learning path
- [ ] badges
- [ ] check list 
- [ ] printable guides

- Quantum Scouts Mural: https://app.mural.co/invitation/mural/indiacommunity0177/1646322933818?sender=ue019fe251218d27e8a5f6405&key=a4cb6bef-9c53-4217-9e3b-1221b2dbe647
- Quantum Scouts Planning Document: https://ibm.ent.box.com/notes/927651502692
- Quantum Scouts MVP: https://ibm.ent.box.com/notes/938590404014
- Algo Queen Information: https://ibm.ent.box.com/notes/927650451546

**Comment by y4izus** [comment]
This issue is outdated, so I close it
