### ISSUE TITLE
Update External Recommended Readings for consistency

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2580]
After a team discussion, we'll need to update the `ExternalRecommendedReadings` component to adhere to the following conventions:

The task here is to go through all the `ExternalRecommendedReadings` for each Course or Summer School page, and ensure that they're consistently implemented.

**Guidelines**
- the readings will be provided in an ordered list
- `Author. Title of reading (Chapter x). Year.`
- if a link exists, link the entire recommendation 
- if more than one author exists, use `et al`.
- if a piece of the information does not exist, leave it out
<br>

**Examples:**
1. Author. Title of reading. Year.
2. Author, et al. Title of reading. Year.
3. Author. Title of reading (Chapter x). Year.
4. Author. Title of reading (Chapters x - xx). Year.
5. [Author, et al. Title of reading (Chapter x). Year.](https://example.com)
6. [Author, et al. Title of reading (Chapters x - xx). Year](https://example.com)
7. [Author. Title of reading.](https://example.com)
8. [Author, et al. Title of reading (Chapters x - xx)](https://example.com)

<br>

**Screenshot of example**
<img width="1124" alt="Screen Shot 2022-05-11 at 10 01 54 AM" src="https://user-images.githubusercontent.com/6276074/167886044-d91f3df0-3a6c-4e8d-b2f7-2d3eef36a7c1.png">

**Comment by chrsfshr** [comment]
I'll take care of this @techtolentino

**Comment by techtolentino** [comment]
Nice work @chrsfshr 🚀
