### ISSUE TITLE
Disambiguate navigation events sent to segment

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#259]
Part of #256

It seems the navigation events are sent with all the same information. Each site should send its own specific information.

**Comment by y4izus** [comment]
This issue is locked until #291 is resolved

**Comment by y4izus** [comment]
- [ ] Disambiguate in community.qiskit.org
- [ ] Disambiguate in qiskit.org

*Disambiguate in community.qiskit.org*
- [ ] index
- [ ] advocates
- [ ] education
- [ ] events
- [ ] experiments

**Comment by delapuente** [comment]
This issue is no longer blocked by #291 but qiskit.org is being rejected by CORS. We need [to authorize qiskit.org](https://github.ibm.com/Bluemix/Bluemix.Analytics/pull/1486) before closing the issue.

**Comment by delapuente** [comment]
Still waiting for CORS errors to get away.

**Comment by delapuente** [comment]
According to several conversations, metrics seems to be working and the remaining malfunctions should be fixed with the new release of Bluemix Analytics. Closing. 🎉
