### ISSUE TITLE
Separate Courses from Chapters

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2598]
As part of the Learn content migration, we'll need to separate between Courses and Chapters, [shown in the design here](https://www.figma.com/file/X9p7omJAZncvDpg2IJLS6J/407-learn-page-migration?node-id=10%3A332)

![Screen Shot 2022-05-16 at 7 29 21 AM](https://user-images.githubusercontent.com/6276074/168616456-5213106a-3d34-4ca2-a812-b5c06f1d7e8c.png)

**Comment by eddybrando** [comment]
Closed with https://github.com/Qiskit/qiskit.org/pull/2601
