### ISSUE TITLE
As an executive, I want to understand how the Qiskit textbook is contributing to hardware executions to understand the textbook's impact on hardware adoption

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit.org#2603]
This story is to help bring visibility to the textbook's contribution to north star OKRs.

Acceptance Criteria:

- [x] Need to have a clear and direct method for measuring what the textbook's impact is on hardware executions.
- [x] Need to have reporting which measures the textbook's impact which is accessible to executives and product owners.

Dependencies:

- [x] Customize client field within job object to reflect when job is being run from the textbook via code cells. Currently client field is only reflecting if the job is run via composer, quantum labs, notebook, or locally.
- [x] If using hardware will need to have hubs and backends determined for this use case.
- [x] Will need to have method for monitoring hardware access access and usage via run button and scratch pad to prevent long queue times.

**Comment by lerongil** [comment]
This one is completed! Great work Anne!
