### ISSUE TITLE
Change description of qiskit.org/ecosystem page

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit.org#2637]
### Feature description

Right now the description of https://qiskit.org/ecosystem/ follows the home page (see https://github.com/Qiskit/qiskit.org/issues/2634). I think it would be great to update the description to match the individual pages.

Suggested description

> The Ecosystem consists of projects, tools, utilities, libraries and tutorials from a broad community of developers and researchers. The goal of the Ecosystem is to celebrate, support and accelerate development of quantum technologies using Qiskit.

**Comment by eddybrando** [comment]
> Yes I think so. The most important use case for me is for sharing on social (Slack, Twitter, LinkedIn): https://moz.com/learn/seo/meta-description (Meta descriptions in social shares section) Sorry I don't know the exact term for it :D

Don't worry, it's exactly what you meant. And it makes total sense. PR #2651 is ready 🙂

Thanks for the contribution!
