### ISSUE TITLE
Bug: Ecosystem page label inconsistency

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2638]
### Where does the issue happen?

https://qiskit.org/ecosystem

### What is the content issue?

On the Ecosystem page, the filter labels and the actual card tags have inconsistent casing. This issue would be to fix them so that there's a consistency.

Issues:
- Filters use capital casing
- some tag labels are in ALL CAPS
- at least one has both `prototypes` and `PROTOTYPES`

### Screenshots

<img width="1569" alt="Screen Shot 2022-05-31 at 10 41 56 AM" src="https://user-images.githubusercontent.com/6276074/171251049-e4d9ab59-0ab7-4f5d-9539-fcacc30f531d.png">

### Additional information

question:
some of the cards have tag labels that are not filterable... should all tag labels be in the filters list? 🤔 

e.g.
- hardware
- chemistry
- design

**Comment by eddybrando** [comment]
Correct me if I'm wrong, but I believe the "tier" options are not related to the labels in the cards. @javabster, is that the case?

If so, this wouldn't be a bug (not as described here at least), but it might be a UX issue indeed for which we might want to open a new issue.

**Comment by javabster** [comment]
heya yep I can clarify:

the 'tier' filter options relate to which ecosystem tier a repo belongs to (i.e. what value does it have for `member.tier` in the json we pull in from the ecosystem repo. The labels as they appear on each card is a concatenated array of `members.tier` and `members.labels` (`label ` data comes from literal github labels attached to that given repo). We wanted to have both the github labels and the tiers represented on the app cards and I was trying to work within the bounds of the structure we already have in place with the `AppCard` which sets all the card labels the same purple colour. So I decided to leave the tier labels in all caps (which is how they come straight from the json object) just as a way to differentiate from the other labels

**Comment by javabster** [comment]
so basically @techtolentino this was meant to be a feature not a bug 😉

**Comment by javabster** [comment]
I guess options would be:

a) leave as is
b) switch the tier filters to all upper case
c) switch the tier card labels to title case
d) adjust the AppCard component to allow different styling of labels and convert the tier labels to a different colour
e) other

I don't have a strong preference, open to other ideas too :)

**Comment by techtolentino** [comment]
@eddybrando @javabster -- good to know! I'm okay with leaving as is; and since I'm not the user, let's not file it as a UX bug yet.

(We can revisit if this becomes an issue for anyone else, going fwd.)
