### ISSUE TITLE
As an organizer, I want to host a Challenge as part of the Qiskit Summer School

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2643]
- https://github.com/Qiskit/qiskit.org/issues/2689
- https://github.com/Qiskit/qiskit.org/issues/2690
- https://github.com/Qiskit/qiskit.org/issues/2691

**Comment by lerongil** [comment]
Closing this one out @techtolentino . Feel free to reopen if it should be closed.
