### ISSUE TITLE
Bug: feature branch mega-menu-dropdown is outdated

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2645]
### Steps to reproduce the problem

1. Go to https://qiskit-org-pr-2574.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/
2. See the Browse all content menu is using outdated styles

### What is the current behavior?

The styles for the Browse all content menu / `MegaMenuDropdown` have been updated in the web-components package. This project needs to update the dependency.

### What is the expected behavior?

The feature branch styles should match what is currently live on qiskit.org/textbook-beta

### Screenshots
![mega-menu-dropdown-style-issues](https://user-images.githubusercontent.com/6276074/171852067-03714c69-0993-4e28-a730-30ef5789952c.png)

**Comment by eddybrando** [comment]
Fixed with #2646
