### ISSUE TITLE
same events need to show time

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2676]
### Feature description

There is not way to attach a time to events in https://qiskit.org/events/

**Comment by y4izus** [comment]
Waiting for the update of the airtable

**Comment by y4izus** [comment]
The airtable has been updated. 

Info for devs:
- The new column name is "Start Time (UTC)"
- Design idea: Adds the info below the date
- Design idea: Adds a clock as icon
- The airtable already has data, so you should see the new info immediately if you execute `npm run generate` in local and then run the app

**Comment by y4izus** [comment]
After an offline conversation, some things changed so I need to update the info for devs. Adding the ON HOLD label until I finish to update the issue :)

**Comment by y4izus** [comment]
Description updated 👆
