### ISSUE TITLE
As a developer advocate, I want to be able to understand documentation usage, so that we can do better redesign decisitions

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2688]
### Background

Historically, documentation was a section without any form of tracking. However, this makes decisions about documentation hard to support.

### Goal

The goal is to introduce some for of analytics in the documentation subsection. Being able to know bounce rates, or even which are the popular pages, would allow us to make better decisions in the documentation.

### Tasks

Some of the subtasks:

- [ ] https://github.com/Qiskit/qiskit_sphinx_theme/issues/61
- [ ] https://github.com/Qiskit/qiskit_sphinx_theme/issues/60

**Comment by y4izus** [comment]
Documentation has been moved, so we can close this issue
