### ISSUE TITLE
Automate Provisioning Code for Challenges

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit.org#2692]
### Feature description

Would like to request to automate the user provisioning code for challenges to remove the need for challenge lead to manually run the code locally. Removing this step will help move the challenges toward becoming more independently managed by the events team, and lower some of the drain on time resource. Additionally we would like to be able to have the challenges rely more heavily on running on hardware, to do this we will need to be able to provide more scalable process for this component.

**Comment by y4izus** [comment]
This issue doesn't belongs to this repository, so I close it. In case this is still needed, please contact @vabarbosa
