### ISSUE TITLE
As an event organizer, I want the events to be "subscribable", so that user can stay up-to-date

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2696]
### Background

Currently, there is no way to get subscribe to the events in the [event subpage](https://qiskit.org/events/). Users rely on Slack workflows to get notification like "New event starts in 5 mins". In addition, when one instance of an event series is cancelled, many points need to be updated (the website, the slack workflow, etc). Similar miscoordination happen when DST.

### Goal

The subpage is pulling data from AirTable, which [generates a shareable calendar view link](https://support.airtable.com/hc/en-us/articles/225050348-Integrating-Airtable-with-external-calendar-applications).

Additionally, AirTable allows for [Slack reminders](https://support.airtable.com/hc/en-us/articles/360059480513-How-to-create-a-simple-reminder) via authomatization. I never used the feature and I'm not sure what is fully capable of. However, it would be great if different events (maybe based on the category or in a custom field in the table?) can be send to different channels. For example, the DemoDay to `#qiskit-dev` and the YouTube seminar series, to `#general`.

### Acceptance criteria

- [x] A public link to subscribe to events from the event subpage (DevRels team => link. Devs team => the rest)
- [ ] A bot to remind user on Slack than an event is going to happen in 5 mins. (DevRels team)
- [x] A single point to submit a new event. (DevRels team)

**Comment by javabster** [comment]
As a first version for this issue, we could add [this airtable calendar view](https://airtable.com/shrzmTpiOo1Ye8Nrs) into the events page. We could either just add a button with the calendar link or airtable provides an embeddable iframe option too. 

When users view this calendar they can filter by event type if they e.g. just want to see the Open Source events.

The airtable calendar view also has an option for users to download an iCal, or we could add a calendar sync link (however neither of these options allow for filtering of events, so they would get calendar info for all events on the events page)

**Comment by y4izus** [comment]
Per offline conversation, the dev team will divide this user story in two tasks:

- [ ] https://github.com/Qiskit/qiskit.org/issues/2922
- [ ] https://github.com/Qiskit/qiskit.org/issues/2924

**Comment by 1ucian0** [comment]
The task  `A bot to remind user on Slack than an event is going to happen in 5 mins. (DevRels team)` can be handled out of this repo. The rest of the tasks are done.
