### ISSUE TITLE
As a new or existing user of Qiskit, I want to have useful and well organised documentation links in the main navigation bar, so that I can understand how to navigate within the documentation and get where I need to go seamlessly.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#2702]
### Background

Right now, the top menu under qiskit.org changes between the home page and the documentation page. In addition, inside the documentation page, the top menu changes 12 times. We need to have just one top menu in order to improve the UX and also the maintainability (just one place to update instead of 13).

### Goal

To shorten the time for users to get where they need to go within documentation by implementing a unified top menu.

Goal is to ease the pain point mentioned by many users, one example:

"IMHO, in a textbook you’re looking for easy-to-following and engaging content to make the learning process enjoyable. On the other hand, in documentation, you want to find what you’re looking for as quickly as possible. You’re typically doing something else, and want to avoid any distractions."

### Acceptance criteria

- [x] The "Documentation" link in the navbar is now a dropdown that shows various links to documentation pages
- [x] The documentation links shown are the ones specified in the [design file](https://www.figma.com/file/xc1jekL6jga6NyRH64k1mV/documentation-redesign?node-id=136%3A1821)
- [x] The _documentation_ dropdown looks and behaves as specified in the [design file](https://www.figma.com/file/xc1jekL6jga6NyRH64k1mV/documentation-redesign?node-id=136%3A1821) for all viewports
- [x] The new navbar is implemented in the _Qiskit.org_ project
- [x] The new navbar is implemented in the _Platypus_ project
- [x] The new navbar is implemented in the _Saiba_ project

### Out of scope

- Changes to the navigation bar in the documentation pages (https://qiskit.org/documentation/)
- Segment instrumentation

### Future of feature

After implementing the changes to the navigation bar, we should start planing the Segment instrumentation.

Also, we could start planing what to do with the current navigation bar in the documentation pages (https://qiskit.org/documentation/).

### Resources

- Design: https://www.figma.com/file/xc1jekL6jga6NyRH64k1mV/documentation-redesign?node-id=136%3A1821
- Prototype: https://www.figma.com/proto/xc1jekL6jga6NyRH64k1mV/documentation-redesign?page-id=152%3A1426&node-id=179%3A1819&viewport=335%2C-122%2C0.34&scaling=min-zoom&starting-point-node-id=179%3A1819&show-proto-sidebar=1

#### Design

- [x] Create a prototype for the top menu

#### Development

- [x] https://github.com/Qiskit/saiba/issues/134
- [x] https://github.com/Qiskit/web-components/issues/100
- [x] https://github.com/Qiskit/web-components/issues/141
- [x] https://github.com/Qiskit/qiskit.org/issues/2762
- [x] https://github.com/Qiskit/platypus/issues/1478
- [x] https://github.com/Qiskit/saiba/issues/107

**Comment by 1ucian0** [comment]
> Rewriting the home page of documentation, using upcoming blog post as a guide

Here is the blogpost: https://qisk.it/3J3csKu

**Comment by agebbie** [comment]
Broke up this user story so that we can fit it into one sprint, for the home page related tasks, this is now covered this this [user story](https://github.com/Qiskit/qiskit.org/issues/2761)

**Comment by javabster** [comment]
Hey just wanted to bring up a conversation we had a while ago that I think may have gotten lost as I don't see any changes in the design file. We mentioned that there are a few docs pages that are relevant to all repos and so should probably be featured in the documentation dropdown under a new heading, something like this:

```
Contributing
- Contributor Guide
- Deprecation Policy
- Maintainer Guide
```

Can we have these added to the dropdown please?

These are the urls:
- https://qiskit.org/documentation/contributing_to_qiskit.html
- https://qiskit.org/documentation/maintainers_guide.html
- https://qiskit.org/documentation/deprecation_policy.html

**Comment by JRussellHuffman** [comment]
It looks like this is done. Is there anything else to be done before closing out the story?

**Comment by agebbie** [comment]
Confirming its done!
