### ISSUE TITLE
As a learner beginning with an advanced undergraduate course, I want to learn the basic information of multiple systems, so that I have the foundation for multiple systems.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#2704]
### Background
Improve single systems lesson to provide learners with information regarding classical and quantum operations. 

### Goal
Release lesson 2 for multiple systems 

Acceptance Criteria: 

- [x]  Implement base level interactions including at least 2 MPC questions, 1 Autograder question.
- [x]  Add math and vocab notations
- [x]  Include snippets of Qiskit code that coincide with the lessons
- [ ]  User test the single systems page 
- [x]  Create slides and scripts for video lectures
- [x]  Consolidate existing material with new lecture to release first lesson as a "chapter"
- [x]  Record 1 lecture

**Comment by JRussellHuffman** [comment]
Both the written and video aspects of this are live. Closing
