### ISSUE TITLE
Cookie Banner Update

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit.org#2716]
### Feature description

This feature request is to serve as a HOLD to track recent conversations regarding our cookies pop up modal, and whether we will be transitioning toward the cookies banner being used across IBM domains via this same solution.

We are still scoping the potential paths for this, and once a path is determined we will update this feature request with the more formalized details.

**Comment by y4izus** [comment]
Per offline conversations, we can close this issue
