### ISSUE TITLE
Old docs version still indexing and reachable

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#2718]
### Steps to reproduce the problem

1. Go to Duck Duck Go
2. Search Qiskit Docs
3. Scroll down to 2nd result
4. See https://qiskit-test.readthedocs.io/en/latest/

### What is the current behavior?

We see old version of qiskit.org/documentation

### What is the expected behavior?

we should see the latest version and it should either redirect or not be indexable at all

**Comment by SooluThomas** [comment]
I have removed the project from my readthedocs account which was from over 3 years ago. Apologies. The link above now gives a 404.

**Comment by techtolentino** [comment]
Thank you @SooluThomas - hopefully this works, though I imagine it might take some time for Google indexing to catch up.

At the same time, a couple of other approaches to note:

1. [Using robots.txt and disallow](https://searchfacts.com/robots-txt-allow-disallow-all/#:~:text=The%20%E2%80%9CUser%2Dagent%3A%20*,access%20or%20crawl%20your%20site.)
2. [Using the noindex meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing#:~:text=noindex%20is%20a%20rule%20set,noindex%20rule%2C%20such%20as%20Google.)

**Comment by y4izus** [comment]
> At the same time, a couple of other approaches to note:
> [Using robots.txt and disallow](https://searchfacts.com/robots-txt-allow-disallow-all/#:~:text=The%20%E2%80%9CUser%2Dagent%3A%20*,access%20or%20crawl%20your%20site.)
> [Using the noindex meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing#:~:text=noindex%20is%20a%20rule%20set,noindex%20rule%2C%20such%20as%20Google.)

Those options are useful when we own the repo. In this case, as Soolu is the owner of the repo and she already deleted it, we can close the issue because there are no other thing we can do on our side.

Thank you very much @SooluThomas and @techtolentino !!!
