### ISSUE TITLE
Improve the way we write media-queries in our SCSS so it becomes more maintainable

### ISSUE THREAD

**Issue by marinaaisa** [Qiskit/qiskit.org#272]
Improve the way we write media-queries in our code so it's more maintainable

For this I suggest to use [sass-mq](https://sass-mq.github.io/sass-mq/), a library with SCSS mixins to improve and make easier to add media-queries in our code since we are using SCSS.

An example of how they work could be this one:

Normal SCSS without sass-mq:
```
.prueba {
  background-color: red
}
@media (min-width: 600px) {
  .prueba {
    background-color: blue
  }
}
```

Using sass-mq ✨:
```
.prueba {
  background-color: red

  @include mq($from: sm) {
     background-color: blue
   }
}
```

This is good because:
- It's more declarative and easier to read, since `$from` is easier to read than `min-width`
- Setting fixed breakpoints as `sm` would be make the code more consistent.
- This allow us to insert media queries inside the class instead of separating media queries as classic CSS does.

**Comment by delapuente** [comment]
What about media queries on `height`. It does not seem covered by the original version of `sass-mq`. We use it to make [section menus of the landing pages static](https://github.com/qiskit-community/community.qiskit.org/blob/master/pages/education/index.vue#L256) when the screen is too short.

I saw there is an [advanced version of `sass-mq`](https://github.com/mcaskill/sass-mq) but I'm not convinced to use it for an isolated usecase, so I think I will refactor the code to extract those cases and encapsulate them in the `InnerNavigation` component.
