### ISSUE TITLE
Bug: Advocate page locations filter "Australia" should be "Oceania"

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit.org#2733]
### Where does the issue happen?

https://qiskit.org/advocates

### What is the content issue?

Previously we label advocates location as `Australia`, but we recently changed it to `Oceania` on airtable because the rest of the locations are all continents. 

Can we change the front end to reflect that as well?

### Screenshots

<img width="202" alt="image" src="https://user-images.githubusercontent.com/7631333/182787081-d96821cf-9929-4c7b-869a-b037533f6c3a.png">

**Comment by techtolentino** [comment]
Thanks for opening this, @HuangJunye - 

I've cleared the assignees in hopes that we can get one of our interns, to help with this. @danielleodigie has expressed interest in helping the team, so maybe she can take this?

**Comment by techtolentino** [comment]
(assigning myself to signify that I'll be pairing w/ @danielleodigie)
