### ISSUE TITLE
[Advocates Filter] Ordering of the locations on advocates page is arbitrary

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit.org#2736]
### Where does the issue happen?

https://qiskit.org/advocates/

### What is the content issue?

After filing https://github.com/Qiskit/qiskit.org/issues/2733, I thought about the ordering of the locations. I am not sure if there were any reasons behind the ordering of the locations in the way it is now:

- North America
- South America
- Oceania
- Africa
- Europe
- Asia

I propose the change to alphabetical order (for N&S America, which uses America to rank):

- Africa
- North America
- South America
- Asia
- Europe
- Oceania

### Screenshots

![Screen Shot 2022-08-05 at 10 25 40](https://user-images.githubusercontent.com/7631333/183035994-75802664-5d38-4c38-b2c6-cbdf969a72ff.png)

**Comment by HuangJunye** [comment]
Sorry for filling this as a separate issue from #2733 as I only thought about this afterwards. Thanks for the quick fix for that one! 

I would also like to bring this to the advocate squad for discussion first. Please put this on hold for the time being. Thanks.

**Comment by y4izus** [comment]
I have removed the bug label since it's not a bug a new request

**Comment by HuangJunye** [comment]
@GemmaDawson agrees with your suggestions.

- Africa
- America (North)
- America (South)
- Asia
- Europe
- Oceania

We can remove the `ON HOLD` label.
