### ISSUE TITLE
As an instructor of quantum computing, I want to create a private experience, so that I can have a consistent representation of my brand throughout the learning experience of my private content.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#2741]
### Acceptance criteria

- [ ]  Size private experience for Dec 16 MVP timeline (pending other exploration of timelines)  
- [ ]  Explore options for timeline of content migration
- [ ]  Break up agreed MVP into development tasks  
- [ ]  Prioritize and assign issues within development team

**Comment by y4izus** [comment]
@JRussellHuffman , @AGFQ , it looks like this issue talks about saiba. Since it's an ongoing project, I think we can close this issue. Do you agree?

**Comment by JRussellHuffman** [comment]
Yes, let's close. This is taken care of in various other issue.
