### ISSUE TITLE
Update Header Image on Documentation Landing Page

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit.org#2744]
### Feature description

Looking to update the header image on the [Documentation home page](https://qiskit.org/documentation/) to be more reflective of the current Qiskit brand identity. 

### Additional context

I think there is a header image already developed for this change, just needs to be implemented!

**Comment by y4izus** [comment]
It looks like this issue is fixed by https://github.com/Qiskit/qiskit/pull/1593, so I close it
