### ISSUE TITLE
Bug: Quantum Explorers event not showing on Events page

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2746]
### Steps to reproduce the problem

1. Go to https://qiskit.org/events
2. See that the Quantum Explorers event is not listed 

### What is the current behavior?

See that the Quantum Explorers event is not listed 

### What is the expected behavior?

The Quantum Explorers event should be listed.

The event runs from Aug 1, 2022 - Feb 28, 2023.

**Comment by eddybrando** [comment]
I can confirm that it's currently in the Airtable database, so we need to check the problem on our end.

**Comment by anamariarojas123** [comment]
@eddybrando @techtolentino any update on this?

**Comment by techtolentino** [comment]
@anamariarojas123 - we discussed this in our dev backlog sync this morning... I believe @eddybrando is going to give it a look.

Thank you for following up
