### ISSUE TITLE
As a new or existing user of qiskit, I want to understand the overview of qiskit, so that I know where to visit within the documentation

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit.org#2761]
### Background

Need to have a home page within the documentation to serve as an anchor which both communicates to users what Qiskit is, and gives users enough context so they can property route themselves on where they need to go.

### Goal

Success metric not yet determined

### Acceptance criteria

- [x] [Replace header image](https://github.com/Qiskit/qiskit.org/issues/2744)
- [x] [Re-write about Qiskit section on homepage using the "What is Qiskit" blog as a guide](https://github.com/Qiskit/qiskit/issues/1646)
- [ ]  Link out to / embed survey to collect user feedback to validate user pain points and prioritize improvements
- [x]  Build a baseline for user traffic
    - [x]  ~Investigate paying for our own temporary hotjar license~. We will replace Hotjar
    - [ ] [Scope out temporary solution (ie: embedding bitly links throughout documentation page) vs longterm solution (instrumenting segment)]
- [x]  Build a 3 month roadmap for the Documentation, beginning with the home page

### Out of scope

-Instrumenting Segment

### Resources

Updated header image
Updated home page copy
Survey

**Comment by y4izus** [comment]
per offline conversations, we can close this issue
