### ISSUE TITLE
Add tabs to Learn page

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2769]
### Feature description

To begin building the curated syllabi experience, we'll need to update the [Qiskit org Learn page](https://qiskit.org/learn) with tab components.

Acceptance criteria
- implement tabs and tab views, using the Carbon vue tab component ( [cv-tab](https://vue.carbondesignsystem.com/?path=/story/components-cvtabs--default) )
- the Learn page will now have two tab views: one for `Learn`, and one for `Teach`
- add new Teach view 
  - Curated syllabi section title
  - curated syllabi section description
  - curated syllabi cards 
  
  
![Screen Shot 2022-09-02 at 1 13 44 PM](https://user-images.githubusercontent.com/6276074/188229453-fbd34690-8aa1-4059-aecd-14379d4df3d6.png)

### Additional context

- For design questions or guidance, please reach out to @gracelindsell 
- this PR should be merged in coordination w/ the Platypus [Curated Syllabi milestone](https://github.com/Qiskit/platypus/milestone/16)

#### Note
(Design and acceptance criteria are subject to change, prior to sprint planning)

**Comment by eddybrando** [comment]
I believe this was closed with https://github.com/Qiskit/qiskit.org/pull/2834.
