### ISSUE TITLE
rolling updates on webpage

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#277]
user needs to see small updates on qiskit.org. updates include small updates to qiskit software and new qiskit videos / blogs . Currently we dont have a space for these small updates that don't need to be highlighted for very long, and therefore users have trouble seeing what all we are up to unless they routinely check our github + twitter + medium + youtube + community pages

A possible solution is to have section with the latest announcements which includes qiskit updates, new features, and content updates.

**Comment by lerongil** [comment]
Is this section not already in place right under the getting started? It seems like this might be more of a need for an automated way of pulling updates to there.

**Comment by CatherineKlauss** [comment]
the comment, which came from a stakeholder, was that we couldn't on that day see that there had been an update to qiskit. 

expanding on that: The section just under getting started isn't updated very frequently, and it's only two sections large, hence the hesitancy to put more frequent updates. For example, a frequent update would be a new episode for coding with qiskit. But the space we have right now is more optimal for a steady post, eg, the whole coding with qiskit series.

 It would be useful to have an update area with more sections so that even smaller updates (eg, new video, new blog post, click here for next event info) can be put on the front page but not given a lot of weight.
