### ISSUE TITLE
Sunset deprecated pages

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2785]
### Feature description

After internal team discussions, the following pages can be sunset:

- Blockbuster page https://qiskit.org/blockbuster
- Qiskit Camp Africa https://qiskit.org/events/africa/
- Qiskit Camp Europe https://qiskit.org/events/europe/
- Qiskit Camp Asia https://qiskit.org/events/asia/
- Physics of Computation Conference https://qiskit.org/events/physics-of-computation/
- Qiskit India Week of Quantum https://qiskit.org/events/india-week-of-women-in-quantum/

Acceptance criteria
- [x] remove pages
- [x] remove any unused assets 
- [x] remove any unused code, components, or links that point to a sunsetted page

**Comment by y4izus** [comment]
sorry for opening this discussion again but, maybe is interesting to save the templates for the events, just in case we need to create another similar page

**Comment by y4izus** [comment]
We should also decided if we want to redirect the pages we delete
