### ISSUE TITLE
Summer School graphic for textbook

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2821]
This issue is to create a version of the quantum simulation graphic in the style that fits in the Qiskit textbook. See Franks comment below for more information.

**Comment by frankharkins** [comment]
We've added the quantum simulation summer school to the textbook, and we need a graphic for the card thumbnail, and a for the overview page header (in the past we've used the same image for both).

[Here's a link to a preview with a stand-in image](https://qiskit-org-pr-2798.dcq4xc5i083.us-south.codeengine.appdomain.cloud/learn/) (see "summer schools -> Quantum Simulations (2022)").

**Comment by eddybrando** [comment]
This is currently in "To do". Is this right? Or is this done?

**Comment by JRussellHuffman** [comment]
Also done. thanks.
