### ISSUE TITLE
Bug: Quantum feature maps and kernels broken link

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2824]
### Where does the issue happen?

https://qiskit.org/learn

### What is the content issue?

In the mega menu dropdown, the link for Quantum feature maps and kernels is broken.

**Related** https://github.com/Qiskit/platypus/pull/1605

### Screenshots

https://user-images.githubusercontent.com/6276074/193870274-6c10dbb1-314e-47b9-852e-500341c0c8f6.mov

**Comment by psschwei** [comment]
I was able to access the link just now:

https://user-images.githubusercontent.com/44698588/195659164-611e01e7-1a5e-4636-8fea-01a495d57d28.mp4

**Comment by techtolentino** [comment]
@psschwei - thanks for pointing this out!

Looks like it was fixed with https://github.com/Qiskit/qiskit.org/pull/2826/files
