### ISSUE TITLE
more consistent documentation tabs

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit.org#2827]
### Feature description

I think it's confusing how inconsistent the documentation menu at [qiskit.org](http://qiskit.org/) is with the top bar of https://qiskit.org/documentation/. for example, the former has Partners listed with a few other things under Providers, and Experiments under Extensions, but the latter just has them at the top level, omitting the other items.

![image](https://user-images.githubusercontent.com/4296166/194102304-859f196d-cb8d-4f9d-8afc-485feee7a284.png)
![image](https://user-images.githubusercontent.com/4296166/194102391-21d23e80-4ed9-48ac-9e54-6144f3c98d1d.png)

I suggest making both menus the same.

**Comment by javabster** [comment]
Hey Kevin, the qiskit.org top bar component is a new redesign to better organise the navigation to various docs pages. I agree the qiskit.org and qiskit.org/documentation pages should have a consistent structure (they have never actually been unified), but each qiskit repo builds their own documentation sites, hence the inconsistencies. 

We are currently working on updating the `qiskit_sphinx_theme` (the package responsible for the styling of the docs websites) to start using the new qiskit.org top bar component, then if each qiskit repo updates their docs to use the new version of the theme they will start pulling in the new top bar component (as well as some other improvements as well).

If repos don't want to wait for an updated theme package they can always start using the new top bar component straight away by adding it directly to their `layout.html` file in their docs directory (but in future we want to discourage having custom `layout.html` files as this overwrites the `layout.html` coming from the theme
