### ISSUE TITLE
Landing Page UX design

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#284]
user has issue with "get started" going to installation docs without first informing user what qiskit is, how it works, and how to interact with it first. 

Front page needs to explain what qiskit is, how users can interact with it, and how what qiskit's applications are before asking user to download qiskit.

**Comment by lerongil** [comment]
Move to documentation issues.

**Comment by delapuente** [comment]
From the Qiskit side, we can link to [Getting Started](https://qiskit.org/documentation/getting_started.html) section too. @lerongil what do you think?

**Comment by CatherineKlauss** [comment]
Possible solution would be a link  walk through a jupyter notebook example in which user sets up an account, develops a ciruit and runs it in a simulator and then plots results. Afterwards can take user to install docs.
