### ISSUE TITLE
Bug: Clicking 'copy code' on homepage copies code all on one line

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#2846]
### Steps to reproduce the problem

I'm opening this issue on behalf of a user who reported this to me and would prefer to remain anonymous

1. Go to https://qiskit.org/
2. Click on 'copy code' under the 'what can qiskit do' section
3. paste the code into your code editor of choice
4. See all the code pasted onto a single line, so the code runs into the comment line

### What is the current behavior?

All the code is pasted onto a single line so the user has to scroll off page and add the line breaks themselves, which isn't a great user experience

<img width="1001" alt="Screenshot 2022-10-18 at 11 10 17 AM" src="https://user-images.githubusercontent.com/23662430/196470314-6cfc91b4-ada8-4981-bc8c-87ab62726a4f.png">

### What is the expected behavior?

It would be great if the copy paste could include the line breaks, so pasted code would look like this:

<img width="673" alt="Screenshot 2022-10-18 at 11 11 34 AM" src="https://user-images.githubusercontent.com/23662430/196470608-6a297d34-524f-4b36-b1a0-31c0375dd523.png">

**Comment by 1ucian0** [comment]
As a reference, the "copy code" this issue refers to is this one. Selecting the code of the box and copy/paste it, works as expected.

![screencapture-qiskit-org-2022-10-20-16_12_42](https://user-images.githubusercontent.com/766693/196973161-ef47f1a6-45d2-46c3-8df4-2a9722d6235b.png)
