### ISSUE TITLE
Bug: App Card labels overlap title

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2852]
### Steps to reproduce the problem

1. Go to the [Ecosystem page](https://qiskit.org/ecosystem)
2. Scroll down to the bottom and find `QuantumCircuits.jl`
4. On desktop, see how the labels almost collide with the title 

### What is the current behavior?

On desktop, see how the labels almost collide with the title 

### What is the expected behavior?

It'd be an improvement if the title showed fully, with spacing, while the labels wrapped to the next line

### Screenshots

![Screen Shot 2022-10-19 at 8 01 30 AM](https://user-images.githubusercontent.com/6276074/196728674-4776dd7e-648f-4c01-99e2-de30d051f124.png)

### Browser

desktop

### Additional information

**Initially seen on LinkedIn**
<img width="1082" alt="Screen Shot 2022-10-19 at 7 57 08 AM" src="https://user-images.githubusercontent.com/6276074/196728491-1b726c40-3f93-4451-a48e-2fb3fdec3657.png">

**Comment by eddybrando** [comment]
![Screenshot 2023-04-14 at 17 26 27](https://user-images.githubusercontent.com/22047320/232087318-a57523cc-028b-427e-897a-ffa12822731e.png)

That specific issue has been fixed. The labels now are shown bellow the title.

Nevertheless, spacing of the labels doesn't look ideal. I'll work on that.

**Comment by techtolentino** [comment]
how about on desktop or LG breakpoints and up? mine is showing this:

![Screenshot 2023-04-14 at 8 49 59 AM (2)](https://user-images.githubusercontent.com/6276074/232092992-635dff98-1dbd-421e-b3cb-d36190aaa161.png)

**Comment by mariacloehb** [comment]
@techtolentino And myself were discussing on a few things regarding this issue, and we'd like to suggest considering having the card tags in their own row, under the card title, and having them left aligned. The original layout didn't take into account the possibility of having multiple tags on the tip right corner, making the tags overline with the title. 

Here are some proposals:
· all tags would be in its own row below the card title
· we could update the purple color for the tags with the light purple shown in the [Carbon Tag Component](https://web-components.carbondesignsystem.com/?path=/story/components-tag--default).

these proposals would also work nicely with the other cards (Events, Advocates)
@y4izus @JRussellHuffman

**Comment by y4izus** [comment]
I think moving always the tags to a new row would leave a lot of space on the right corner and it could be weird when we have just one tag. Said that, this is another proposal:
- Main tags on the right corner with the color they have right now. By main tags I mean the tags that match the first block of filters on the left side of the page
- Secondary tags on a new line, below the title and with this light purple you suggested

What do you think? @JRussellHuffman , @techtolentino , @mariacloehb

**Comment by y4izus** [comment]
My proposal suggested the labels in reverse: Community on the top right corner (Community is one of the filters on the left sidebar) and the rest on the second line.

**Comment by techtolentino** [comment]
![Screenshot 2023-05-12 at 6 33 00 AM](https://github.com/Qiskit/qiskit.org/assets/6276074/b02665ad-8be2-4d47-9330-7882e5552432)

(just mocking using inspect element)

this is way more scalable... makes me wonder if the upper right one (Community, or Extension) even needs to be a tag...

**Comment by y4izus** [comment]
I suggested the colors in reverse 😅 , the main label (the one on the corner) on dark purple and the rest on the row in light purple

**Comment by techtolentino** [comment]
Okay this is the last time I'm trying this 😅 

![Screenshot 2023-05-12 at 6 47 19 AM](https://github.com/Qiskit/qiskit.org/assets/6276074/7acee085-8b57-4e58-b7e9-7f65e08fde8a)

**Comment by y4izus** [comment]
that's it!! :D

**Comment by JRussellHuffman** [comment]
My only issue with the above is that the user might not understand the difference between the two types of tags. I'm not sure I know the difference. 

I don't oppose the above solution, but for the sake of conversation, I'm going to throw out one more idea.

Have the tags always right aligned within their own container. The container has a certain margin from the title, something like 32px. The title container should have a max width too. If a tag reaches the edge of the container, it wraps below and starts a new line from the right. I feel like this would solve the problem and we would have only one kind of tag.

<img width="978" alt="Screenshot 2023-05-12 at 9 40 38 AM" src="https://github.com/Qiskit/qiskit.org/assets/7633881/5a0217c0-2918-41d0-8544-ed483f29a179">

**Comment by JRussellHuffman** [comment]
We could also consider setting a character limit for the name, and a tag limit. so this edge case doesn't come up.

**Comment by techtolentino** [comment]
Quick mock using inspect element, of Russell's suggestion:

![Screenshot 2023-05-12 at 8 11 48 AM](https://github.com/Qiskit/qiskit.org/assets/6276074/110135a7-ced4-4819-8322-ac712cf39843)

**Comment by y4izus** [comment]
I think is confused having all the tags with the same style and together when the filter is only related with one of the tags... 😕

**Comment by JRussellHuffman** [comment]
So we basically already have two different types of tags - ones that are used to filter and ones that are not? I didn't realize that either. If that's the case, visually having two types of tags makes sense.

**Comment by JRussellHuffman** [comment]
Good to know. then I'm on board with the first proposal of visually different cards. 

Is there a chance that there will be multiple of those tags and a long title, and so we end up with the same problem again?
