### ISSUE TITLE
"Quick Start" should be more hardware agnostic

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2856]
### Where does the issue happen?

Landing page

### What is the content issue?

The _Quick Start_ in the landing page is very IBM Quantum centric. The website needs to highlight the possibility to connect with hardware and simulators.

### Screenshots

I suggest something like this. [Figma link](https://www.figma.com/file/2eIjxTEmZWPPwzX308Hoa6/2856-quick-start?node-id=1%3A671&t=3uJbuH4sqDFYTGrB-1).

<img width="1142" alt="Screenshot 2022-10-26 at 11 44 48" src="https://user-images.githubusercontent.com/766693/197993883-843e8607-3545-4e5a-ba2a-967accf1a164.png">

### Additional information

I think the "unstable" section can be removed. Typical, the information to install dev version is in the GitHub README file.

**Comment by 1ucian0** [comment]
Currently, the supported backends are:

Simualtors:
- https://github.com/Qiskit/qiskit-aer/
- https://github.com/cda-tum/ddsim

QPU:
- https://github.com/Qiskit/qiskit-ibmq-provider
- https://github.com/Qiskit-Partners/qiskit-ionq
- https://github.com/Qiskit-Partners/qiskit-aqt-provider
- https://github.com/qiskit-community/qiskit-quantinuum-provider
- https://github.com/rigetti/qiskit-rigetti

Multiprovider:
 - https://github.com/qiskit-community/qiskit-braket-provider

**Comment by 1ucian0** [comment]
Other candidates (thanks @mtreinish !):
 - https://github.com/iqm-finland/qiskit-on-iqm 
 - https://github.com/pnnl/NWQ-Sim
 - https://github.com/SupertechLabs/qiskit-superstaq
 - https://github.com/qcware/qiskit_qcware
 - https://github.com/gaqqie/gaqqie-door
 - https://github.com/0tt3r/QuaC-qiskit

**Comment by mtreinish** [comment]
The other thing we should do if we make a page like this is document how someone should be able to add themselves to the list (and the criteria for being on the list). Having maintained lists like this in the past people sometimes care quite a bit about being advertised on a project's website.

**Comment by 1ucian0** [comment]
Fully agree. Maybe we can isolate the code and running as part of the ecosystem check ups. Mocking might be hard.

Other options is to go for a very arbitrary GH start minimum or months since the last release.

**Comment by frankharkins** [comment]
@JRussellHuffman do you have thoughts on the design?

**Comment by JRussellHuffman** [comment]
This would basically be updated the component on the homepage of qiskit.org, right? Would it mean removing the "start online" CTA that goes to Quantum Lab? There is another code cell directly below the current version of this component on qiskit.org that might visually conflict (although it might be okay). Does that section, the "What Can Qiskit Do" section need to be reworked too, or is that out of scope for now?

**Comment by JRussellHuffman** [comment]
@1ucian0 I took a quick pass at cleaning up the design file at the top of the thread [here](https://www.figma.com/file/2eIjxTEmZWPPwzX308Hoa6/2856-quick-start?node-id=1%3A671&t=3uJbuH4sqDFYTGrB-1), but I think we should meet to discuss it briefly to make sure it scales up well, especially if there are going to be a lot of circuit libraries and providers.

Let me know when you have some time and we can discuss it in detail.

**Comment by JRussellHuffman** [comment]
Also FYI, I updated the figma link in the description. I started a new file because I think the other wasn't a part of our workspace in figma

**Comment by y4izus** [comment]
This issue is done on this [PR](https://github.com/Qiskit/qiskit.org/pull/3044), so we can close it
