### ISSUE TITLE
Bug: Quick Start for unstable installation needs update

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2857]
### Where does the issue happen?

Landing page - Quick Start www.qiskit.org

### What is the content issue?

The current Quick Start for Unstable installation, refers to repo that should not be there for the following reasons:
 * R1 - an antiquate understanding of Qiskit
 * R2 - packages unnecessary to run the exposed example
 * R3 - unmaintained code

I suggest to remove the following ones:
 * `git+https://github.com/Qiskit/qiskit-aer` because reasons R1 and R2
 *  `git+https://github.com/Qiskit/qiskit-ignis` because reasons R1, R2, and R3
 *  `git+https://github.com/Qiskit/qiskit-aqua` because reasons R1, R2, and R3

At the moment `git+https://github.com/Qiskit/qiskit-ibmq-provider` can stay, because it is necessary to run the exposed example. However, I suggest to have [a more general approach in the long run](https://github.com/Qiskit/qiskit.org/issues/2856). 

### Screenshots

<img width="543" alt="Screenshot 2022-10-26 at 11 57 03" src="https://user-images.githubusercontent.com/766693/197998394-31aa7f91-95b4-4997-8a43-f560eed667f1.png">

**Comment by javabster** [comment]
for this issue if we remove the ibmq provider then don't we also need to update the code example later on that also uses the provider?

<img width="695" alt="Screenshot 2023-01-10 at 4 48 40 PM" src="https://user-images.githubusercontent.com/23662430/211582738-3e6f833e-ea21-4012-9d79-686a69477d2b.png">

**Comment by javabster** [comment]
I suggest this code block using the BasicAer simulator:

```
import qiskit
 
# create circuit with Qiskit quantum circuits libraries
quantum_circuit = qiskit.circuit.library.QuantumVolume(5)
quantum_circuit.measure_all()
quantum_circuit.draw()

# select simulator backend
from qiskit import BasicAer

backend = BasicAer.get_backend('qasm_simulator')

# prepare your circuit to run on the simulator
optimized_circuit = qiskit.transpile(quantum_circuit, backend)
optimized_circuit.draw()

# run on simulator
job = backend.run(optimized_circuit)
result = job.result()
print(result.get_counts())
```
