### ISSUE TITLE
user confused by "watch it" link

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#286]
user confused that "watch it" takes them to youtbe, an external site. 

two solutions:
(1) change link to an IBM website with embedded youtube videos
(2) (preferred) change link text to "watch on youtube"

**Comment by lerongil** [comment]
This seems to be less of a user story and more of a UX issue. Removing the label for now.

**Comment by lerongil** [comment]
Let's move forward with option 2
