### ISSUE TITLE
Q301 Lesson 2 Animations

### ISSUE THREAD

**Issue by joshluna** [Qiskit/qiskit.org#2867]
Create Animations for Q301 Lesson 2 and deliver to video team

**Comment by JavaFXpert** [comment]
Can't wait to see these animations, Josh!

**Comment by joshluna** [comment]
Thanks James! Happy to hear it 😊

From: James Weaver ***@***.***>
Date: Monday, November 14, 2022 at 9:35 AM
To: Qiskit/qiskit.org ***@***.***>
Cc: Josh Luna ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [Qiskit/qiskit.org] Q301 Lesson 2 Animations (Issue #2867)
Can't wait to see these animations, Josh! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned. Message ID: <Qiskit/qiskit. org/issues/2867/1314131022@ github. com> ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Can't wait to see these animations, Josh!
