### ISSUE TITLE
design b/t iqx and qiskit too different

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#287]
internal users want qiskit and iqx design to look like siblings

external users want to understand the difference between iqx and qiskit

**Comment by lerongil** [comment]
This needs to be scoped down a bit. My recommendation is to scope this down to the documentation between IQX and Qiskit.

**Comment by CatherineKlauss** [comment]
At the same time, we don't want Qiskit to look too IBM-y or corporate
