### ISSUE TITLE
Bug: [ecosystem] projects with many labels break.

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2878]
### Steps to reproduce the problem

1. Go to qiskit.org/ecosystem

### What is the current behavior?

<img width="574" alt="Screenshot 2022-11-22 at 15 26 00" src="https://user-images.githubusercontent.com/766693/203339687-67412f35-82a9-49d0-bf87-cec022200296.png">

### What is the expected behavior?

either show less labels or show them nicely :)

**Comment by techtolentino** [comment]
Possible duplicate @1ucian0 ?

https://github.com/Qiskit/qiskit.org/issues/2852

**Comment by 1ucian0** [comment]
It is indeed! Thanks!
