### ISSUE TITLE
education should be own tab

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#288]
internal users want education to be own tab, separate from community. 

possible solution: UX paths from front page could be (1) learning paths (2) education resources (3) community

**Comment by CatherineKlauss** [comment]
sponsored user research adds a user story to this issue:

while users liked the content they found under community, they expected community to mean a calendar of events, a blog, announcements, and a forum to talk to other users.

**Comment by delapuente** [comment]
Related to #349
