### ISSUE TITLE
user has issue finding qiskit event from online search

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#289]
specific issues: 
> googling "qiskit camp" will take you to old qiskit camp webpages, not useful for users attending other camps
> need to keep old webpages up so that attendees can look up location/dates/name afterwards for CVs and resumes

possible solution: a landing page for all qiskit camp events, past (in a list down low) and future (promoted at top)

specific issue:
> unclear which events should get webpages

possible solution: qiskit "owned" events, which has an IBM event briefing, are mostly funded by qiskit, and that we assume liability should have a webpage. qiskit "sponsored" events, in which we partially pay for the event but are hands-off in planning, do not have an IBM event briefing, and we do not assume liability, should not have a webpage. These events will likely have webpages created by the host.  But should we separately list "qiskit sponsored events" with links to external webpages, if they exist?

**Comment by lerongil** [comment]
@delapuente can you add the requirements list to this issue?

**Comment by delapuente** [comment]
- Video up top, using footage from several camps, students explain what is qiskit camp
- Links to upcoming qiskit camp pages (prominently displayed, with images)
- Need easy-to-fill template for all event pages 
- GitHub process works well
- Link to event blog recaps (with small previews of 2-3 latest posts)
- Calendar of all events, filtering options for date and geography, includes conferences, small hackathons, large camps
- Map of events, past and future, color-coding and filtering similar to calendar
- Copy: list of different event types
- Event Submission Form (apply to host an event)
- Event Query Form (or just email)

**Comment by lerongil** [comment]
Related #381 #383

**Comment by delapuente** [comment]
The site qiskit.camp no longer points to the old event but to the 2020 edition. Nevertheless, I agree this should be pointint to the relation of all events.
