### ISSUE TITLE
Bug: [Learn page] tab position is incorrect

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2891]
### Steps to reproduce the problem

1. Go to qiskit.org/learn
4. See that the Teach / Learn tabs aren't in the correct layout position

### What is the current behavior?

These tabs are left-aligned

### What is the expected behavior?

Originally, they should be right-aligned 

### Additional information

Related, original PR: 

https://github.com/Qiskit/qiskit.org/pull/2834

**Comment by y4izus** [comment]
For more context:

- How it is right now

![Captura de pantalla 2023-01-02 a las 16 20 22](https://user-images.githubusercontent.com/17231966/210250666-224bc335-4b9e-4051-a366-d4c1d7e8d9a7.png)

- How it should be

![Captura de pantalla 2023-01-02 a las 16 21 04](https://user-images.githubusercontent.com/17231966/210250744-dc972c49-4874-474f-885f-eeb1ae1439da.png)

Check the [Figma file](https://www.figma.com/file/TqhAqhKlyzVKMdWKas0lKI/1260-Curated-Syllabus?node-id=31%3A1877&t=ahBjzV3LqQayM837-0) if needed
