### ISSUE TITLE
Bug: profile pictures for advocates are not being displayed

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#2893]
### Steps to reproduce the problem

1. go to https://qiskit.org/advocates/
2. advocates profile pictures are not being displayed

### What is the current behavior?

the profile pictures for the advocates are retrieved from Airtable.
attachment/image URLs retrieved from Airtable expire after a few hours thus images become unable to be displayed

https://support.airtable.com/docs/changes-to-airtable-attachments

### What is the expected behavior?

advocate profile picutres should be displayed

### Screenshots

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/13156555/206368277-921ff9df-3de0-4c54-a2f5-d365b64a54b0.png">

### Device

Laptop

### OS

Mac OS v12.6

### Browser

Firefox 107.0.1

### Additional information

until this can be properly addressed, consider temporarily opting out of expiring URLs: https://support.airtable.com/docs/changes-to-airtable-attachments#temporary-opt-out-instructions

**Comment by eddybrando** [comment]
Thanks a lot for working on this @vabarbosa and @techtolentino!

We've temporarily opted out of expiring URLs, fixing this issue.

We'll open a new issue to work on a more robust fix that allow us to keep the expiring URLs.
