### ISSUE TITLE
Download and store advocate's photos from Airtable during build

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2894]
### Feature description

Airtable recently implemented a change to make the URLs of attachments (like the advocate's photos) expire after a couple of hours:

> On November 8, 2022, Airtable will improve the security of our attachment URLs by incorporating an expiring links functionality across our product surface areas. That means when you share attachments stored in Airtable via URL with external colleagues the link you provide them will expire after a couple of hours. Read on to learn more about how to prepare for the upcoming changes.
>
> **Source:** https://support.airtable.com/docs/changes-to-airtable-attachments

This caused the following bug in our advocates page (https://qiskit.org/advocates/):

- https://github.com/Qiskit/qiskit.org/issues/2893

In order to quickly solve that issue, we've temporarily opted out of the expiring URLs. But this option will be removed on February 8th, 2023.

As recommended by Airtable, we need to download the files during the API fetch and store them on our end so that they remain accessible.

### Additional context

- Airtable information about the change: https://support.airtable.com/docs/changes-to-airtable-attachments
- Advocates' Airtable base: https://airtable.com/app8koO4BZifGFhCV/tblAATp37ybjFZtO3/viwdqD6xFc5JvpQrB?blocks=bipWydYrrs5oss3UF
- API documentation for the Advocates' Airtable base: https://airtable.com/app8koO4BZifGFhCV/api/docs

**Comment by eddybrando** [comment]
Here is a simple outline to have a very general idea of how we could achieve this:

```typescript
import Airtable from 'airtable';

// Initialize the Airtable API client
const base = new Airtable({ apiKey: 'YOUR_API_KEY' }).base('app8koO4BZifGFhCV');

// Fetch the attachment from the specified base
base('Table1').find('Attachment1', (err, record) => {
  if (err) {
    console.error(err);
    return;
  }

  // The attachment is stored in the "url" field of the record
  const attachmentUrl = record.get('url');

  // You can then use the URL to download the image using the Node.js fs module, for example
  const fs = require('fs');
  fs.writeFile('image.jpg', attachmentUrl, err => {
    if (err) {
      console.error(err);
    } else {
      console.log('Image downloaded successfully');
    }
  });
});
```

**Comment by vabarbosa** [comment]
> Should we do the same with the events photos?

it would depend on how it is currently being stored/retrieved, but i believe the answer is yes. we probably would want the same approach for both to keep things consistent.
