### ISSUE TITLE
[Events]: Add new `Open source` event type

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2895]
### Feature description

In a request from @javabster:

There's a new event `Type` that we'd like to see get added to the `/events` listing: **Open source**

These events would include:
- Qiskit DemoDays
- Qiskit Office hours

**Screenshot:** (possible preview of what this could look like)
<img width="894" alt="Screenshot 2022-12-12 at 10 02 23 AM" src="https://user-images.githubusercontent.com/6276074/207121159-d3ec2914-0476-4ebb-9817-3dd4d3dbc90c.png">

(made via Chrome Dev Tolls)

### Additional context

CC: @JRussellHuffman 

Tagging you for visibility/awareness

**Comment by JRussellHuffman** [comment]
Refactored to be automatic would be awesome at some point, but for now I think adding "Open Source" as an option will work just fine.
