### ISSUE TITLE
[Events] Add event description to event tile

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#2902]
### Feature description

It would be great if the event tiles on qiskit.org/events had a 1 sentence description for what the events are. 

### Additional context

The tiles on qiskit.org/ecosystem page uses a version of the same tile component as the events page but it does have space for a description, so we could probably use the same component with a similar implementation

**Comment by y4izus** [comment]
Note for devs:
- We are already using the component `EventCard` that is prepared for having a description (see [here](https://qiskit.org/events/summer-school/#:~:text=The%20Qiskit%20Global%20Summer%20School%20returns%20as%20a%20two%2Dweek%20intensive%20course%20focused%20on%20Quantum%20Simulations%20and%20more!))
- We need to pull the event description from the Airtable and show it on the card 
- The column name is "Event Description"
- The Airtable already have content, so running `npm run generate` on local will pull info to check on your machine how it will look
