### ISSUE TITLE
As a user interested in ecosystem, I want to know where to find more information about the ecosystem without joining so that I can decide if i want to join without pressure

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#2909]
### Background

@woodsp-ibm from the applications team pointed out that on the ecosystem website the only CTA is for "join the ecosystem" but some users might want to just learn more about what it takes to join the ecosystem before actually joining it. The existing join button redirects the user to the github readme for the ecosystem where the user can get more information, but the button text maybe is a bit too aggressive and puts people off. There are also other pieces of content about how to join the ecosystem (e.g. [this youtube series](https://www.youtube.com/playlist?list=PLOFEBzvs-VvqKza-VLSYzWxnUMp-nO_aS)) which might be nice to incorporate somehow into the page itself

### Goal

Make it easier for users visiting the ecosystem page to "learn more" about how to join the existing, before they commit to joining it.

### Acceptance criteria

minimum:
[] rewording the button text on qiskit.org/ecosystem from "join the ecosystem" to something more appropriate, like "learn more" or similar

nice to have:
[] include some other supporting content on what it takes to join the qiskit ecosystem directly in the ecosystem page

**Comment by y4izus** [comment]
The ecosystem page has been removed, so we can close this issue
