### ISSUE TITLE
Provide the information for disambiguating the events sended to segment

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#291]
The issue #259 is blocked due to lack of information. 

Metrics needs a convention but the doc with the steps to follow is not finished yet (but it's coming soon). The conversation about this could be found [here](https://github.ibm.com/IBM-Q-Software/om-digital-planning/issues/284)

There are two possible solutions:
- Wait for the document to be ready
- Resolve issue #259 with temporary information and replace with the final one when the document is ready

In both cases information is needed in order to close the #259

**Comment by lerongil** [comment]
@francabrera Do you have an update on the design doc for us? Thanks for putting it together!

**Comment by francabrera** [comment]
@lerongil the issue has been updated with a design-doc of the instrumentation requirements for our devs. Not sure if there will be other blockings, besides that document, or requirements for this task to continue.

**Comment by lerongil** [comment]
Thanks Fran. 

@y4izus can you take a look [here](https://github.ibm.com/IBM-Q-Software/design-docs/blob/master/analytics/Segment-Dev-Instrumentation.md) and see if this will allow us to proceed?

**Comment by lerongil** [comment]
@y4izus is this still on hold?

**Comment by y4izus** [comment]
No, I'm working on it! I remove the "on hold" tag

**Comment by delapuente** [comment]
This is done after merging #361
