### ISSUE TITLE
[events] Add a link to subscribe to the event's calendar 

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#2922]
### Feature description

The DevReal team created a calendar with the events we have. Airtable allows the users to suscribe to that calendar, so the idea is to share that link on the events page.

-----
Part of: https://github.com/Qiskit/qiskit.org/issues/2696

### Additional context

Contact @javabster to get the link

**Comment by y4izus** [comment]
Per offline conversations, @techtolentino will be the contact person for design on this issue

**Comment by techtolentino** [comment]
The design part of this is done. 
[Figma file here](https://www.figma.com/file/YTYDopstugJbJIzJrVPFwx/qiskit.org-event-subscribe?node-id=4742%3A11137&t=VpumwAvcIK2Cm6fU-4)



![Image](https://user-images.githubusercontent.com/6276074/215820388-c08923f4-cf03-4ac3-9565-debeb75e7111.png)

**Comment by y4izus** [comment]
Awesome! Thank you!
