### ISSUE TITLE
Refactor Tab styling across the site

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2932]
### Feature description

Currently, we use the Carbon Tab web component across the site on various pages: 

- Events
- Learn page
- Summer School
- Qiskit Fall Fest
- India Week of Women in Quantum 

In terms of style overrides, this has amounted to several instances of duplicate SCSS. 

Proposing this `code quality` issue to potentially refactor the code so that we're not copying/pasting styles across several pages.

**Comment by eddybrando** [comment]
This is an old issue. We don't have this problem anymore. This issue can be closed.
