### ISSUE TITLE
Bug: Links to "Join Event" are not responsive

### ISSUE THREAD

**Issue by paulsearle** [Qiskit/qiskit.org#2933]
### Steps to reproduce the problem

1. Go to ... https://qiskit.org/events/seminar-series/
2. Click on ... Join event
3. See error ... nothing happens

### What is the current behavior?

seems like the links are broken or not being triggered for some reason, not sure when it started but someone noticed 1/24/23

### What is the expected behavior?

the corresponding youtube event would load

### Screenshots

![Screenshot 2023-01-24 at 2 24 15 PM](https://user-images.githubusercontent.com/79483070/214434750-a15d0222-a196-4e21-82b5-53288ba12cca.png)

### Device

MacBook Pro

### OS

macOS Ventura 13.1

### Browser

Chrome Version 109.0.5414.87 (Official Build) (arm64) & Safari Version 16.2 (18614.3.7.1.5)

**Comment by y4izus** [comment]
This issue cannot be reproduced, so I'm gonna close it

**Comment by paulsearle** [comment]
Thanks Yaiza!

--

Thanks,

Paul
