### ISSUE TITLE
Fix warnings on Build and Deploy gh-actions

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#2942]
The [Build and Deploy](https://github.com/Qiskit/qiskit.org/blob/main/.github/workflows/deploy.yml) gh-action [shows several warnings](https://github.com/Qiskit/qiskit.org/actions/runs/4041781403) because we are using deprecated commands and a deprecated version of Node.

We should update the gh-action to stop using deprecated things

**Comment by jackoconnordev** [comment]
This issue seems to be fixed now, should it be moved out of backlog?

Recent Build and Deploy no warnings: https://github.com/Qiskit/qiskit.org/actions/runs/5518335795

![Image](https://github.com/Qiskit/qiskit.org/assets/134723582/42875948-6f64-49c4-ab58-46f3eb1626ed)

**Comment by eddybrando** [comment]
We still have a warning showing.

![Screenshot 2023-07-28 at 12 49 32](https://github.com/Qiskit/qiskit.org/assets/22047320/cca73019-4a5c-44b8-9b49-68a2272e4de3)
