### ISSUE TITLE
Replace Slack invite link to https://qisk.it/join-slack

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit.org#2959]
### Feature description

The current Slack invite link https://ibm.co/joinqiskitslack is being replaced by https://qisk.it/join-slack to use the Qiskit brand name. We should use the new link for qiskit.org.

Related to https://github.com/Qiskit/web-components/issues/200

cc: @paulsearle

**Comment by HuangJunye** [comment]
A quick search found the old link in five places: https://github.com/Qiskit/qiskit.org/search?q=https://ibm.co/joinqiskitslack

**Comment by woodsp-ibm** [comment]
I will note that the link also appears in many of the repo readme files in their contribution guidelines overview e.g. https://github.com/Qiskit/qiskit-terra#contribution-guidelines
