### ISSUE TITLE
Bug: small typo on Events page empty state Card

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2962]
### Where does the issue happen?

https://qiskit.org/events/

### What is the content issue?

- Click on the `Workshop` filter
- see empty state Card read _"Trying doing a wider search criteria, or consider starting your own event."_
- should be _"Try doing a wider search..."_

### Screenshots

![Screenshot 2023-02-06 at 9 45 34 AM](https://user-images.githubusercontent.com/6276074/217046605-b3c2625c-e76f-4156-8f08-291114c36d3f.png)

**Comment by ryanrrogers** [comment]
I can take care of this.
