### ISSUE TITLE
Change the copy of `Qiskit Community` section to something related to social media.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#297]
Part of #278

**Comment by delapuente** [comment]
@CatherineKlauss what would it be a good copy for this?

**Comment by CatherineKlauss** [comment]
Through connecting, contributing and collaborating, our diverse community of Qiskitters propels Qiskit to new forefronts and fields. In our commitment to open this quantum computing community to people of all backgrounds, we span across several platforms. Start connecting and contributing today!

**Comment by CatherineKlauss** [comment]
> Through connecting, contributing and collaborating, our diverse community of Qiskitters propels Qiskit to new forefronts and fields. In our commitment to open this quantum computing community to people of all backgrounds, we span across several platforms. Find us today to start connecting and contributing! 

(changed last sentence to match title change made in #308 )
