### ISSUE TITLE
Simplify and DRY code of learn course pages

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2983]
### Feature description

After the refactor to Nuxt 3, our learn course pages (**pages/learn/course/**) are only using the **CourseOverviewPage** component in their templates.

As @y4izus pointed out in https://github.com/Qiskit/qiskit.org/pull/2980#discussion_r1108274756, we might want to reconsider this structure and change if to one singular component **(pages/learn/course/[course])** that leverages [Nuxt Content](https://content.nuxtjs.org/).

**Comment by y4izus** [comment]
Learn pages have been removed, so we can close this issue
