### ISSUE TITLE
As a open source quantum developer,  I want to understand what a provider is and how to become one,  so that I can more easily develop my own open source provide

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#2987]
### Background

As part of the new narrative for Qiskit, Providers takes a stronger importance.

### Goal

We need a place where people that what to become a Provider could see all the information they need

### Acceptance criteria

- [x] a how-to document in the qiskit documentation detailing how to create your own provider

### Tasks

- [x] #2988
- [x] #2989
- [x] #2990
- [x] #2991

**Comment by HuangJunye** [comment]
Thanks for creating this user story! @1ucian0 and I had discussions about the guide. I think the content can be largely come from ["Write a New Provider" section](https://qiskit.org/documentation/apidoc/providers.html#writing-a-new-provider) of the documentation. We can split it out to make it into a how-to guide or a tutorial in qiskit-terra. If that is the approach we will take, I will work on converting the content (#2989) and the UI (#2989) will be the qiskit documentation and no need to code a special page (#2991) for the guide.

It's possible that you have more up-to-date info from a meeting that I was not in. In that case, I would like to find out more about the discussion outcome :D

**Comment by y4izus** [comment]
All the tasks on this issue are done and can be checked on the [feature branch](https://github.com/Qiskit/qiskit.org/pull/3044), so we can close this issue
