### ISSUE TITLE
Review the items in the menu, sections and subsections for the footer.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#299]
Part of #275

**Comment by lerongil** [comment]
Is this an issue or something to discuss?

**Comment by delapuente** [comment]
We can convert it into a discussion and disconnect from #275.

**Comment by marinaaisa** [comment]
This is a business discussion, who should be involved on it?
cc / @delapuente @lerongil @CatherineKlauss

**Comment by lerongil** [comment]
This should be designed in a way that allows us to make the footer 'modular', meaning if we would like to add a new item it can be slotted in. We should discuss what we would like to start with.

**Comment by delapuente** [comment]
I'm going to open a new issue for the technical part, providing a similar solution to #298 but for the footer, and move this out of the sprint backlog.

**Comment by lerongil** [comment]
This looks like it can be closed. Do you agree @delapuente ?

**Comment by delapuente** [comment]
Let's close it.
