### ISSUE TITLE
Internal users want a mailing list to provide important information to Qiskit Users

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#300]

**Comment by y4izus** [comment]
To have a mailing list could be very helpful for announcements. For example, we add a new project to the qiskit projects page and we want to notify all the users around the world. If we use twitter, half of the world could be sleeping and they couldn't read the tweet. If we send this information via email, we asure that all the people see that we have new info in the web.
I have talked only about projects as an example, but we can extend it to notify about new articles on medium, new videos on youtube, when the advocates application is open, the winners of qiskit camps, the new release of qiskit, news about IBM Quantum, ...

**Comment by y4izus** [comment]
This issue is no longer relevant, so I close it
