### ISSUE TITLE
Implement the new Quick Start section

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3005]
### Feature description

The [Quick Start section](https://qiskit.org/#:~:text=Get%20started-,Quick%20Start,-When%20you%20are) has been [redesigned](https://www.figma.com/file/2eIjxTEmZWPPwzX308Hoa6/2856-quick-start?node-id=35%3A1515&t=fiIwqYieLSLN6VH2-1) , so we need to implement the new version

**Comment by techtolentino** [comment]
@JRussellHuffman 

Just wanted to bring to your attention something that @y4izus flagged earlier.

In the [mobile designs for the Algorithms tabs](https://www.figma.com/file/2eIjxTEmZWPPwzX308Hoa6/2856-quick-start?node-id=43%3A2237&t=6FIZgOuqOQzQJOSl-4), the designs call for an arrow button, that would allow the user to see the other algorithms.

However, the way the [component is built](https://www.ibm.com/standards/carbon/carbon-web-components/?path=/story/components-tabs--default&knob-Direction%20(direction%20in%20%3Cbx-tooltip-body%3E)=bottom&knob-Open%20(open)=true&knob-Tooltip%20alignment%20to%20trigger%20button%20(alignment)=end), in mobile views, the tabs turn into a dropdown.




https://user-images.githubusercontent.com/6276074/223512155-7a957be0-7fb1-40bc-ac8b-1169cc0582fc.mov



What are your thoughts on going with what the component offers, as its first pass? I still think, functionally, it does it's job by allowing users to pick what algorithm they want to view...

**Comment by JRussellHuffman** [comment]
Interesting. What component is being used for the tabs on the [event page](https://qiskit.org/events/)? Those switch to an arrow.

**Comment by techtolentino** [comment]
Okay, I was able to get some clarification from the Carbon team.

Seems like the latest implementation should follow the designs the [Carbon website shows](https://carbondesignsystem.com/components/tabs/usage/#live-demo) (which uses the arrow buttons to handle the overflow). 

In this case, the Carbon Web Components package has yet to sync w/ Carbon React v 11.

My recommendation is to (maybe) still leverage the Carbon Vue component, until we can fully rely on the Carbon Web Components library.

What do you think @y4izus?
