### ISSUE TITLE
Coding with Qiskit Copy

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#302]
> Last (current) sentence is incomplete thought
> should not name individuals without explaining who they are

**Comment by lerongil** [comment]
Thanks for adding these. Will you update these copy issues with proposals when you have them?

**Comment by CatherineKlauss** [comment]
Now you can learn to program a quantum computer on YouTube. From installing Qiskit, through programming your first circuit, and all the way to making your first contribution, we’ve got videos to help you every step of the way.

**Comment by CatherineKlauss** [comment]
I believe this is a seperate issue, but "Watch It" link following this copy should be changed to "Watch on YouTube"
