### ISSUE TITLE
IQX section -- copy

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#303]
Better differentiate what user can do on IQX vs with Qiskit

From stakeholder: IQX is a cloud service. Qiskit is a software that uses that cloud service

**Comment by CatherineKlauss** [comment]
> Hesitant to install? Then try Qiskit on the IBM Q Experience, a quantum computing cloud service where no installation is required and free tutorials are available. Your work is saved in the cloud and automatically updated with each Qiskit release. The perfect way to try it before you buy it — figuratively, of course, as Qiskit will always be free. 

^ needs stakeholder review

**Comment by CatherineKlauss** [comment]
update on this -- stakeholder pushing that we not say "qiskit on the cloud", which is currently on our website. so let's push to change this copy sooner rather than later @lerongil

**Comment by delapuente** [comment]
Pinging on this @lerongil @CatherineKlauss how important is this?

**Comment by lerongil** [comment]
Do we have approval for this: 

> Hesitant to install? Then try Qiskit on the IBM Q Experience, a quantum computing cloud service where no installation is required and free tutorials are available. Your work is saved in the cloud and automatically updated with each Qiskit release. The perfect way to try it before you buy it — figuratively, of course, as Qiskit will always be free.

If so, I would simplify it to this and ship it: 

> Hesitant to install? Then try Qiskit on the IBM Q Experience, a quantum computing cloud service where no installation is required and free tutorials are available. Your work is saved in the cloud and automatically updated with each Qiskit release.

**Comment by CatherineKlauss** [comment]
I like Leron's simplified version. We dont have approval yet. I'll ask Paul

**Comment by CatherineKlauss** [comment]
it approved. changing label now
