### ISSUE TITLE
As a qiskit docs user, I want a more informative qiskit.org/documentation page, so that I can easily understand what is qiskit (and what is not qiskit) and how to find what I need

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3031]
### Background

Now that we have formalised the narrative around what is Qiskit and what is the Qiskit Ecosystem, we need to make this clearer when users go to qiskit.org/documentation what they will be able to find here.

### Goal

Users who come to qiskit.org/documentation should understand what is available in Qiskit (i.e. terra) and what they would need to go to the ecosystem docs pages for

### Acceptance criteria

- [ ] Design: a new documentation landing page 
        - should still be implementable in sphinx (so maintain the left sidebar, copyright footer etc.)
- [ ] implement the new design in the sphinx theme

**Comment by 1ucian0** [comment]
Blocked on moving it to `qiskit-terra` https://github.com/Qiskit/qiskit-metapackage/issues/1722

**Comment by y4izus** [comment]
This issue doesn't belong to this repo and @1ucian0 told me that it's already [tracked on the correct repo](https://github.com/Qiskit/qiskit/issues/10600), so I close it
