### ISSUE TITLE
As a qiskit.org user, I want to quickly see how to get started using qiskit for different use cases with multiple providers, so that I can get going quickly with integrating qiskit into my preferred workflow

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3034]
### Acceptance criteria

a new quick start component on the home page that includes:
- [x] installation steps for different providers
- [x] implementation steps for different qiskit circuits/algorithms
- [x] have an easy way to update the code, providers list and algorithm list (via a json file, for example) https://github.com/Qiskit/qiskit.org/issues/3049

**Comment by 1ucian0** [comment]
Fixed by https://github.com/Qiskit/qiskit.org/pull/3044
