### ISSUE TITLE
As a Qiskit project maintainer, I want the sphinx theme feedback buttons to also have a text input, so that I can see why users are voting thumbs up/down

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3035]
### Background

in the qiskit sphinx theme we currently have a basic HTML/jquery component that allows users to give us feedback on each documentation page: 
<img width="493" alt="Screenshot 2023-03-17 at 11 04 53 AM" src="https://user-images.githubusercontent.com/23662430/225793474-10fd4f4a-65f4-4a11-b69b-f6f649e76851.png">

We currently only collect yes/no feedback using segment, but it would be great if we could enable users to optionally submit some written feedback about why they voted yes/no.

### Goal

Enable us to see why users are voting yes/no for how helpful a specific page is, so that we can make those pages better

### Acceptance criteria

- [ ] a web component that includes a thumbs up/down like the current implementation, but also includes a text box where users can give written feedback
- [ ] the component should be able to store the results in amplitude like the current version can
- [ ] the new component is implemented in the sphinx theme

**Comment by y4izus** [comment]
this is no relevant anymore
