### ISSUE TITLE
deploy Qiskit Ecosystem Main tier documentation to qiskit.org/ecosystem

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3038]
Epic: https://github.com/Qiskit/qiskit.org/issues/3054

The current non-Qiskit projects that are hosting their documentation in qiskit.org/documentation/ should be moved to qiskit.org/ecosystem/

- [x] Aer https://github.com/Qiskit/qiskit-aer/pull/1748
- [x] Rustworkx https://github.com/Qiskit/rustworkx/pull/843
- [x] IonQ provider: https://github.com/Qiskit-Partners/qiskit-ionq/pull/117
- [x] AQT provider: https://github.com/Qiskit-Partners/qiskit-aqt-provider/pull/54
- [x] IBM provider https://github.com/Qiskit/qiskit-ibm-provider/pull/544
- [x] IBM experiment https://github.com/Qiskit/qiskit-ibm-experiment/pull/61
- [x] IBM Runtime https://github.com/Qiskit/qiskit-ibm-runtime/pull/759
- [x] Experiments https://github.com/Qiskit/qiskit-experiments/pull/1096
- [x] Nature https://github.com/Qiskit/qiskit-nature/pull/1103
- [x] Optimization https://github.com/Qiskit/qiskit-optimization/pull/483
- [x] Machine Learning https://github.com/Qiskit/qiskit-machine-learning/pull/581
- [x] Finance https://github.com/Qiskit/qiskit-finance/pull/249
- [x] MThree https://github.com/Qiskit-Partners/mthree/pull/151
- [x] qiskit-neko https://github.com/Qiskit/qiskit-neko/pull/24
- [x] qiskit-metal https://github.com/Qiskit/qiskit-metal/pull/937
- [x] qiskit-dynamics https://github.com/Qiskit/qiskit-dynamics/pull/219

**Comment by Eric-Arellano** [comment]
@1ucian0, you're missing two projects:

* https://github.com/Qiskit/qiskit-neko
* https://github.com/Qiskit/qiskit-metal

**Comment by 1ucian0** [comment]
Removing the deployment in /documentation

- [ ] Aer https://github.com/Qiskit/qiskit-aer/pull/1891
- [ ] Rustworkx https://github.com/Qiskit/rustworkx/pull/964
- [ ] IonQ provider https://github.com/qiskit-community/qiskit-ionq/pull/139
- [x] AQT provider (no need) 
- [ ] IBM provider https://github.com/Qiskit/qiskit-ibm-provider/pull/702
- [ ] IBM experiment https://github.com/Qiskit-Extensions/qiskit-ibm-experiment/pull/78
- [ ] IBM Runtime https://github.com/Qiskit/qiskit-ibm-runtime/pull/1014
- [ ] Experiments 
- [ ] Nature 
- [ ] Optimization 
- [ ] Machine Learning 
- [ ] Finance 
- [ ] MThree 
- [ ] qiskit-neko 
- [ ] qiskit-metal 
- [ ] qiskit-dynamics

**Comment by y4izus** [comment]
@1ucian0 , could we close this issue?

**Comment by 1ucian0** [comment]
yeap
