### ISSUE TITLE
[Providers] Update Quick Start widget installation content

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3047]
### Feature description

After reviewing with @1ucian0, we need to make a couple of updates to the homepage Quick Start feature. 

Currently, the Installation that is shown in the Providers Quick Start, is a single line, but should be updated to multiline

#### How it currently renders
![Screenshot 2023-03-22 at 9 19 20 AM](https://user-images.githubusercontent.com/6276074/226970319-5098405f-556c-40d2-b42f-6f24d6d2693e.png)

#### How it should render (two lines)
```
pip install 
qiskit-ibm-provider
```

### Acceptance criteria
- [x] This should be updated to render as two lines
- [x] For this task, we can update our local json files. 
    - [Example of installation code location ](https://github.com/Qiskit/qiskit.org/blob/feat/providers/content/providers/cloud-simulators.json#L10-L12) for the Provider page data
    - [Example of installation code location ](https://github.com/Qiskit/qiskit.org/blob/feat/providers/content/providers/quick-start.json#L6-L8) for the Provider homepage Quick Start widget
    - Please note that there are multiple instances of these, across several files within `/content/providers/*.json`

### Additional context

Going forward, this should be updated on @HuangJunye's scripts that generates these installation code lines

**Comment by 1ucian0** [comment]
The box should render:
```
pip install qiskit 
pip install qiskit-ibm-provider
```

The first `pip install qiskit` should always be there. While it is not technically necessary, I think it helps to drive the point that this box is about installing qiskit *with* something.
