### ISSUE TITLE
UX : Application explanations

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#305]
UX design to explain Qiskit applications (applications currently stated on website are research, education and business) 

needed because we are removing the copy that states the applications in favor of showing rather than telling

**Comment by CatherineKlauss** [comment]
#https://github.com/Qiskit/qiskit.org/issues/304

**Comment by lerongil** [comment]
This is related to #284 and #304 which needs improvement in order to provide a more thoughtful getting started experience.

**Comment by CatherineKlauss** [comment]
sponsored user research confirmed this need with user story:

users expected to find more information on how to use qiskit, eg, "when to use" and "why to use"
