### ISSUE TITLE
Update the What Can Qiskit Do section deprecated content

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3050]
## Quick note
Depends on [the Providers feature branch](https://github.com/Qiskit/qiskit.org/pull/3044) merging first

<br/>

### Where does the issue happen?

https://qiskit.org/

### What is the content issue?

In the "What can Qiskit Do" section some of the content needs refreshing due to certain parts being deprecated:

### Updated content

> Feature 1
> **Title**: Circuit Library
> **Description**: Qiskit includes a comprehensive set of quantum gates and a variety of pre-built circuits so users at all levels can use Qiskit for research and application development.
> **Learn more link**: https://qiskit.org/documentation/apidoc/circuit_library.html

> Feature 2
> **Title**: Transpiler
> **Description**: The transpiler translates Qiskit code into an optimized circuit using a backend’s native gate set, allowing users to program for any quantum processor or processor architecture with minimal inputs.
> **Learn more link**: https://qiskit.org/documentation/apidoc/transpiler.html

> Feature 3
> **Title**: Transpile to any hardware
> **Description**: Qiskit helps users run and schedule quantum programs for a variety of local simulators and cloud-based quantum processors. It supports several quantum hardware designs, such as superconducting qubits and trapped ions.
> **Learn more link**: /providers

> Feature 4
> **Title**: Try it yourself
> **Description**: Ready to explore Qiskit’s capabilities for yourself? Check out how to run Qiskit on the cloud or locally in your local Python environment.
> **Learn more link**: https://qiskit.org/documentation/getting_started.html

### Screenshots (updated design w/ new layout)

![Screenshot 2023-03-29 at 6 05 13 AM (2)](https://user-images.githubusercontent.com/6276074/229876249-28c4832f-2769-485a-aba3-a11abfdf05a8.png)

**Comment by 1ucian0** [comment]
What do you think about the following:

**Title**: Compile to any target

**Paragraph**: Qiskit compiles quantum programs that can be run on a variety of local or cloud-based quantum processors, including simulators and QPUs. It supports several hardware designs, such as superconducting qubits and trapped ions.

**Learn more link**: https://qiskit.org/providers/

**Comment by techtolentino** [comment]
This would work nicely... @JRussellHuffman - thoughts?

Also, question for @1ucian0 

Do we want to have 4 features here? only 3? 

Asking because depending on what the content will be, the design could potentially take different directions...

**Comment by 1ucian0** [comment]
**Title**: Try it yourself

**Paragraph**: Ready to explore Qiskit’s capabilities for yourself? Check out how to run Qiskit on the cloud or locally in your local Python environment.

**Learn more link**: https://qiskit.org/documentation/getting_started.html

**Comment by JRussellHuffman** [comment]
That works for me.

**Comment by techtolentino** [comment]
@1ucian0 one question I had:

I know we're going to remove the Code example from the "What Can Qiskit Do" section, and move it up into the Providers Quick Start widget, under its own tab... 

Is there a specific Tab name that we should use? And which provider should it appear with?

**Comment by 1ucian0** [comment]
Thanks to some @kdk suggestions, I updated https://github.com/Qiskit/qiskit.org/issues/3050#issuecomment-1485412692

> Is there a specific Tab name that we should use? And which provider should it appear with?

@HuangJunye suggested "Transpiling".

**Comment by HuangJunye** [comment]
> What do you think about the following:
> 
> **Title**: Compile to any hardware
> 
> **Paragraph**: Qiskit helps users run and schedule quantum programs for a variety of local simulators and cloud-based quantum processors. It supports several quantum hardware designs, such as superconducting qubits and trapped ions.
> 
> **Learn more link**: https://qiskit.org/providers/

Should we change to "Transpile to any hardware" here?

**Comment by techtolentino** [comment]
Question for the thread:

Since we're in this process of redefining card content, I think I should update this issue so that the outcome would be finalized content of the 4 features.

```
Feature 1
Title: Lorem ipsum title
Description: Lorem ipsum description
Learn more link: https://lorem-ipsum
```

```
Feature 2
Title: Lorem ipsum title
Description: Lorem ipsum description
Learn more link: https://lorem-ipsum
```

```
Feature 3
Title: Lorem ipsum title
Description: Lorem ipsum description
Learn more link: https://lorem-ipsum
```

```
Feature 4
Title: Lorem ipsum title
Description: Lorem ipsum description
Learn more link: https://lorem-ipsum
```

This would make it very clear what changes we're making, and easier for our intern to pick up and deliver.

**Comment by 1ucian0** [comment]
plus the removal of the codebox and the two buttons at the end of it. 
<img width="697" alt="Screenshot 2023-04-04 at 15 47 49" src="https://user-images.githubusercontent.com/766693/229813731-b774f9d0-e976-473d-b43c-7284e82680b5.png">

**Comment by techtolentino** [comment]
@1ucian0 - updated the issue description

Please let us know if the content in the description is good to go, or you can also edit away as you see fit.

Thank you

**Comment by javabster** [comment]
I have a few suggestions/questions for the copy in this component:

Feature 2:
 - Is there a way that this could be rephrased to focus on what the _user_ can do with the transpiler? I think it's important to explain what the transpiler is, but maybe there is a way to add some emphasis about how users can configure the transpiler themselves?

Feature 3:
- for the title, is "transpile to" the right grammar? Should it rather be "transpile for"? I'm not really sure about this tbh but "transpile to" feels weird. 
- Also maybe we should drop the transpile from this title entirely, because we already have another title called "Transpiler" so it feels a bit repetitive
- instead of "run and schedule" should it be "schedule and run"? It sounds a bit more fluent to put it in chronological order

Feature 4:
- more fluent: "Learn how to run Qiskit in the cloud or your local Python environment."
