### ISSUE TITLE
As a qiskit.org user, I want to read the header blocks on the Advocate page, so that I can better understand the goals and benefits of the Qiskit Advocate program

### ISSUE THREAD

**Issue by GemmaDawson** [Qiskit/qiskit.org#3058]
### Background

The current text blocks do not accurately reflect the goal and benefits of the current Advocate program, and need to be updated.

### Goal

Use this header to better reflect the Qiskit Advocate program as it stands in 2023.

### Acceptance criteria

- [ ] New text matches provided text
- [ ] Visually looks beautiful and fits the current aesthetic standard
- [ ] Any required links work as expected

### Resources

Copy to be discussed & provided when user story is accepted

**Comment by techtolentino** [comment]
@GemmaDawson - did you want to hand the content updates over to us, or were you planning on making a PR yourself? (Either way is fine for us)

Thank you

**Comment by techtolentino** [comment]
FYI:

- removed the `story` label so we can use this as an actionable task for dev to work on. 
- added the `content` label since this is mostly a content update
- sizing at a `medium` while we work to gather finalized content, plus the time it takes to get feedback/reviews

**Comment by y4izus** [comment]
We are not gonna add more features to this repo so we can close this issue
