### ISSUE TITLE
👍 As dev team we want to have one only markup for menu on Qiskit so it's easier to maintain

### ISSUE THREAD

**Issue by marinaaisa** [Qiskit/qiskit.org#312]
Right now on `QiskitOrgMenu.vue` there is two HTML markups with the same content: one for desktop and another one for mobile.
This could be reduced to only one and change its responsiveness using CSS, in special CSS Grid.

**Comment by y4izus** [comment]
We are now using the `qiskit-ui-shell` component from [our web components library](https://github.com/Qiskit/web-components), so we can close this issue
