### ISSUE TITLE
seperate code of conduct page for events

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#313]
Right now the long code of conduct is at the bottom of every event page, which is a weird way to end the event page. The code of conduct is the same for every event. So this text should be on its own page and each event page should link users to code of conduct page to read the long text.

**Comment by lerongil** [comment]
Related to issue #327

**Comment by lerongil** [comment]
@marinaaisa Can we close this issue with the work you have done for issue #327 ?
