### ISSUE TITLE
Bug: Providers YAML has invalid link type

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3146]
### Steps to reproduce the problem

This is a code issue.

### What is the current behavior?

https://github.com/Qiskit/qiskit.org/blob/main/content/providers/list/1.primitives.yaml#L76 has an object `websiteCta` that is typed as `GeneralLink`, but an object with that type requires a string `label` attribute and a string `url` attribute. The file mentioned defines both of them as `null`.

This is related to this _FIX_ comment: https://github.com/Qiskit/qiskit.org/blob/main/components/providers/ProvidersAccordionLayout.vue#L45

### What is the expected behavior?

- The data in the YAML file(s) need to conform with the defined types.
- We might need to introduce stricter testing as well to avoid content in the wrong format.
- https://github.com/Qiskit/qiskit.org/blob/main/components/providers/ProvidersAccordionLayout.vue#L45 needs to be fixed. The type check should occur ideally in TypeScript or during automated testing to avoid redundant checking.

**Comment by y4izus** [comment]
Providers page has been removed, so this issue is no longer relevant. I close it
