### ISSUE TITLE
As a qiskit.org user, I want a different learn button in the top menu, so that I can easily understand that learning quantum computing is different to learning qiskit

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3167]
### Background

Feedback from users at the DevForum indicated that there was confusion about how to use qiskit.org for learning quantum computing. Some were confused about the difference between learning qiskit and learning quantum computing. Others would look at qiskit docs and want some extra info about the quantum concepts close to hand. Others would search for something on google and get redirected to the qiskit docs when they actually needed the textbook or vice versa. 

Given this a few user needs were established:
1. clearer indication the the qiskit textbook (soon to be IBM Quantum learning platform) is for learning quantum computing, and qiskit.org is for learning qiskit
2. users need to be able to easily switch between learning quantum computing and learning qiskit when they are on a given page

### Goal

Users should still be able to access the textbook/QLP content from qiskit.org via the top menu, but the top menu should make it clear that 
a) the learning referred to here is for learning quantum computing not qiskit
b) by clicking the button they are being redirected away from qiskit.org

### Acceptance criteria

- The learn button should redirect to the new learning platform (at some point?)
- The learn button should be rephrased to "Learn Quantum Computing" or similar
- The learn button should clearly indicate that a user is being sent out of qiskit.org

**Comment by y4izus** [comment]
This issue is no longer relevant, so I close it
