### ISSUE TITLE
As a qiskit.org user, I want and updated community dropdown, so that I can more easily find relevant community links

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3168]
### Background

The Ecosystem link is currently "hidden" in the community dropdown of the top menu. It is a popular page that we want to promote more, and users sometimes struggle to intuitively find it under the community tab. Additionally, the footer lists different things under "community" so it would be good if they could match

### Acceptance criteria

- [ ] Ecosystem button should be moved from the "community" dropdown to the root of the top menu
- [ ] Code of Conduct link should be added to "Community" dropdown

**Comment by y4izus** [comment]
This issue is no longer relevant, so I close it
