### ISSUE TITLE
As a user interested in ecosystem, I want a link to a project's docs/website, so that I can more easily get to the information i need

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3170]
### Background

There are plans to remove the documentation links of ecosystem projects from the top menu (see https://github.com/Qiskit/qiskit.org/issues/3169). These updates will make it more difficult for users to access documentation for main tier qiskit projects, so we should somehow incorporate them into the ecosystem page instead. Currently on the ecosystem tiles we only have a link to the github, but some projects have main websites or documentation pages that are also useful

### Acceptance criteria

- Setup ecosystem backend to include a "website" attribute in the `members.json`
- Add a button/link/external link to tiles on qiskit.org/ecosystem

**Comment by 1ucian0** [comment]
on the json side: https://github.com/qiskit-community/ecosystem/pull/370

**Comment by y4izus** [comment]
I've removed the `story` task because this is not a group of tasks, just a task
