### ISSUE TITLE
Improve SEO for Qiskit documentation

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit.org#3177]
A user explained today that they frequently use Google/DuckDuckGo to search Qiskit docs. Their main issue is that we usually take them to the older versions of the docs.

This issue is to investigate how we can better improve our SEO.

**Comment by javabster** [comment]
closing this as we have scoped out the SEO work separately in this milestone: https://github.com/Qiskit/qiskit.org/milestone/26
