### ISSUE TITLE
Integrate more Qiskit content from other sources into qiskit.org

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3178]
### Feature description

We have a lot of great Qiskit content on the Qiskit YouTube and the Qiskit Medium that it would be great to integrate into qiskit.org itself. We've also seen feedback from users who would like to see more videos/visuals in qiskit.org.

I'm opening this issue to start collecting specific ideas for where we could add specific pieces of content. Feel free to add comments with other suggestions!

### Qiskit Releases
we have release notes, release planning wiki, [medium blog posts](https://medium.com/qiskit/release-news-qiskit-v0-40-is-here-cdcdc8d400d4) and youtube [breaking changes videos](https://youtu.be/v-s83q9t9Nw). Perhaps there is a way to highlight this somewhere on qiskit.org? Maybe a new section on the landing page?

### Events
- [Brian's annual events roundup video](https://youtu.be/fdaco0gFGMk) could be added to the events page

### Ecosystem
- [why you should open source your quantum cod](https://youtu.be/_Skul_R7eFY)e video, or any other ecosystem video might be a good fit for this page

### Miscellaneous
- the [what is qiskit video ](https://youtu.be/P5cGeDKOIP0) could be added to the landing page
- a specific section somewhere with the best 3 medium stories for a student / new to Qiskit?
- a specific section somewhere with the best 3 videos for a student / new to Qiskit?

### Additional context
there are also plenty of options for integrating content into documentation, those ideas are tracked here: https://github.com/Qiskit/qiskit_sphinx_theme/issues/289

**Comment by y4izus** [comment]
This issue is no relevant anymore for this repo. Nevertheless, I'm gonna tag @lerongil (couldn't find Jules and Tushar slack usernames) just in case they wanted to have this in mind for the new Qiskit page
