### ISSUE TITLE
As a qiskit user, I want to be able to search all qiskit.org pages, so that I can get the results I need regardless of where I am in qiskit.org

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3179]
### Goal

Improve discoverability of qiskit docs and enable users of all levels to work with the documentation in an intuitive way. We have a lot of good quality content, but we have gotten feedback time and again that people are struggling to find what is relevant to them. a proper search interface could go a long way to solving this issue.

Main open question: what content should be indexed in qiskit.org search?
- qiskit (terra) docs - yes
- general qiskit.org pages - yes
- qiskit ecosystem project docs - ?
- qiskit textbook - ?
- IBM quantum learning platform content - ?
- non-qiskit.org qiskit content (e.g. medium, youtube, twitter) - ?

### Acceptance criteria

- [ ] a search box component in the top menu
- [ ] search results compiled from qiskit documentation and qiskit.org pages

**Comment by y4izus** [comment]
this is not relevant anymore, so I close it
