### ISSUE TITLE
As a qiskit.org search user, I want well organised search results, so that I can more easily find the content that is relevant for me

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3180]
### Background

currently the search results that are available on qiskit.org/documentation are not well displayed, making it almost useless for most users. The way that we display search results is just as important as the information that is being shown.

### Goal

This issue still needs more discussion and scoping but it would be good if users could know the following when given a list of search results:

- is a specific result for qiskit or an ecosystem project?
- is a result from an api ref, how tutotiral, how-to, or explanation?
- what is the difficult level of a certain piece of content?
- is a result for learning qiskit or learning quantum computing?
- is this content qiskit.org or IBM quantum or something else?
- can I filter by content type or source? e.g. I only want to see content results from the qiskit nature tutorials

### Acceptance criteria

- [ ] some form of filtering of search results
- [ ] some tagging/labelling of search results
- [ ] fuzzy matching

**Comment by y4izus** [comment]
this is not relevant anymore, so I close it
