### ISSUE TITLE
As a qiskit.org user, I want a landing page crafted to my needs, so that I can get to the content I need easily

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3181]
### Background

It has been brought up by users that when you first get to the qiskit.org landing page you may have very different needs depending on what type of user you are. 

For example you might need one of the following:
- to learn the basics of quantum computing (qiskit textbook/learning platform)
- specific code implementation (api reference, tutorials, release details)
- applications research stuff (ecosystem, applications modules)

### Goal

Create some way for users of different backgrounds/interests to find a content list or learning path that is most relevant to them. This could include a short question modal asking for a users interests, or sections of the landing page with content organised by interests (e.g. [aws splits things by indsutry, solution and product ](https://aws.amazon.com/)). We already have something similar with the "what can qiskit do?" section, but I think we are missing some things like applications, learning quantum computing, ecosystem etc. I think it is still valuable to have this type of signposting even if it pushes people to other platforms. I think we could more clearly signpost to people "if you want qiskit info stay here, if you want ecosystem/learning content go there"

### Acceptance criteria

this needs more discussion and scoping

**Comment by y4izus** [comment]
This issue is no relevant anymore for this repo. Nevertheless, I'm gonna tag @lerongil (couldn't find Jules and Tushar slack usernames) just in case they wanted to have this in mind for the new Qiskit page
