### ISSUE TITLE
As a new user, I want clearer signposting on the landing page about what qiskit is, so that I understand where to go to learn quantum computing versus learning qiskit

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3182]
### Background

Many users conflate the concept of learning quantum computing with learning qiskit. We need to make it clear to users who come to qiskit.org that they should stay here for qiskit specific stuff, but if they want more general learning resources about quantum computing they need to go elsewhere

### Acceptance criteria

needs more discussion and scoping

**Comment by y4izus** [comment]
This issue is no relevant anymore for this repo. Nevertheless, I'm gonna tag @lerongil (couldn't find Jules and Tushar slack usernames) just in case they wanted to have this in mind for the new Qiskit page
