### ISSUE TITLE
SEO: Optimise titles and descriptions for all pages

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3188]
### Feature description

We should review the title and descriptions tags for all pages and optimise them.

For most pages, the title is already defined but the description is not.

### Additional context

- Meta descriptions according to Google: https://developers.google.com/search/docs/appearance/snippet#meta-descriptions
- Influencing your title links in search results: https://developers.google.com/search/docs/appearance/title-link

**Comment by paaragon** [comment]
Pages with description:

- [x] /advocates
- [x] /ecosystem
- [x] /index
- [x] /metal
- [x] /providers
- [x] /events
- [ ] /events/fall-fest
- [x] /events/seminar-series
- [ ] /events/summer-school-2022 -> different method of setting description
- [x] /events/summer-school-2023
- [ ] /learn
- [ ] /learn/course/algorithm-design
- [ ] /learn/course/basics-quantum-information
- [ ] /learn/course/fundamentals-quantum-algorithms
- [ ] /learn/course/games-and-demos
- [ ] /learn/course/introduction-course
- [ ] /learn/course/legacy-content
- [ ] /learn/course/machine-learning-course
- [ ] /learn/course/multiple-qubits-and-entanglement
- [ ] /learn/course/prerequisites
- [ ] /learn/course/quantum-algorithms-for-applications
- [ ] /learn/course/quantum-computing-labs
- [ ] /learn/course/quantum-hardware-circuits
- [ ] /learn/course/quantum-hardware-pulses
- [ ] /learn/course/quantum-protocols-and-quantum-algorithms
- [ ] /learn/course/quantum-states-and-qubits
- [ ] /learn/summer-school/introduction-to-quantum-computing-and-quantum-hardware-2020
- [ ] /learn/summer-school/quantum-computing-and-quantum-learning-2021
- [ ] /learn/summer-school/quantum-simulation-summer-school-2022

**Comment by paaragon** [comment]
I think we should take advantage of this issue to decide what method of setting the headers for SEO we want and what attributes we set.

The most used method to set SEO headers in the project is to use the `useSeoMeta` composable. Some pages like `/events/fall-fest` use `useHead` to set the meta headers. I think `useSeoMeta` is better solution.

The most used meta atributes are:
- title
- ogTitle
- description
- ogDescription
- ogImage
- ogUrl

The pages where the meta headers are setted by `useHead` also include these headers:
- twitter:title
- twitter:description
- twitter:image
- twitter:image:alt
- og:iamge:secure_url
- og:image:alt

In total there are 12 headers and only 3 distinct vaules (title, description and image). I think we can facilitate the setting of these headers if we create a composable as a wrapper of `useSeoMeta` (for example `useQiskitSeoMeta`) that receives only the three values we use and sets all possible headers.
