### ISSUE TITLE
SEO: Optimise images for speed

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3191]
### Feature description

We need to review and optimise all of our images for speed as recommended by Google Search Central in https://developers.google.com/search/docs/appearance/google-images#optimize-for-speed.

### Additional context

- Image optimisation: https://web.dev/fast/#optimize-your-images
- Responsive images: https://developers.google.com/search/docs/appearance/google-images#responsive-images
- Responsive image techniques: https://web.dev/learn/design/
- Why does speed matter?: https://web.dev/why-speed-matters/

**Comment by y4izus** [comment]
This issue is no relevant anymore, so I close it
