### ISSUE TITLE
[Advocates] Research "Get info from a Relational DB on Airtable"

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3193]
The structure of the Airtable we have to use for the QAMP page is a relational one, meaning that the info on some columns points to another table. We will need to access all the info, so we need to check how to access it

**Acceptance criteria**
- [x] Find out how to get info from a relational airtable. You can share how to do it here or on our slack channel

Note: If you need to see the airtable, please contact me

----

Part of https://github.com/Qiskit/qiskit.org/issues/3055

**Comment by eddybrando** [comment]
Research is done. We need to fetch the data from the "Cohorts" and "Participants" tables first and then we can use that data to replace the references to those tables in the "Projects" table, when we fetch that data.

This has been implemented in https://github.com/Qiskit/qiskit.org/pull/3244
