### ISSUE TITLE
SEO: Analyse and optimise Performance Metrics (incl. Core Web Vitals)

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3195]
### Feature description

We need to analyse our Performance Metrics and optimise them as suggested by the Google Search Central (https://developers.google.com/search/docs/appearance/core-web-vitals).

### Additional context

To analyse the metrics we can use a tool like Unlighthouse: https://unlighthouse.dev/

**Comment by y4izus** [comment]
This issue is no relevant anymore, so I close it
