### ISSUE TITLE
Footer links are not sized appropriately

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3198]
### Feature description

A Lighthouse reporte showed that the footer links don’t have enough space around them, so that they could be easy to tap without overlapping.

We need to improve the layout of the footer.

This issue affects the UX, accessibility and SEO.

**Comment by eddybrando** [comment]
> @eddybrando Let me know if it's fine or not.

Hi @tarunsamanta2k20, thanks for the contribution.

It's hard to tell just from the image. I believe that we might need to run Lighthouse on it to be sure. It can be done from inside Chrome as well in the dev tools.

**Comment by tarunsamanta2k20** [comment]
@eddybrando do you want me to open a PR for this issue?

**Comment by eddybrando** [comment]
> @eddybrando do you want me to open a PR for this issue?

Thank you very much @tarunsamanta2k20, but I decided to quickly work on it since it included an element of investigation to get to the technical details that explained how we needed to change this exactly.

It's detailed in https://github.com/Qiskit/qiskit.org/pull/3319.
