### ISSUE TITLE
[EcosystemTestTable]: extra spacing in table

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3207]
### Steps to reproduce the problem

1. Go to https://qiskit.org/ecosystem
2. Click on any card that has an `EcosystemTestTable` (dropdown accordion)
3. Scroll down
4. See extra spacing

### What is the current behavior?

The test table has extra spacing

### What is the expected behavior?

The test table doesn't need to have extra spacing

### Screenshots

https://github.com/Qiskit/qiskit.org/assets/6276074/449744fb-6065-4ae5-8bd9-dbe65dfb2133

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue

**Comment by tarunsamanta2k20** [comment]
@techtolentino this is looking good. i think this is a default behavior of vue data table. Another solution might be clipping content, then scrolling will be disabled. What is your suggestions?

**Comment by techtolentino** [comment]
@tarunsamanta2k20 - one thing to consider would be adding the `display: inherit` to the `.test-table` styles [here](https://github.com/Qiskit/qiskit.org/blob/cc93f1f50a9b759ce642a5d3aefe31834ec1dbb5/components/Ecosystem/EcosystemTestTable.vue#L121-L123) - let me know if it works.

**Comment by tarunsamanta2k20** [comment]
@techtolentino if I put display: inherit to the .test-table, then scrolling will be disabled. Do you want that?

**Comment by techtolentino** [comment]
@tarunsamanta2k20 - is the scroll needed?

**Comment by tarunsamanta2k20** [comment]
> @tarunsamanta2k20 - is the scroll needed? I guess that's the question... I'm unsure if we need the scroll, if there's no content below that last table row.
> 
> thinking

Not needed. All rows will be clipped without scrolling.

**Comment by techtolentino** [comment]
Coming back to this:

I actually think that the extra whitespace is caused (and needed) by the information tooltip. And unless we find a design pattern where we can get rid of those icon tooltips, we need to allow the whitespace to exist.

https://github.com/Qiskit/qiskit.org/assets/6276074/37e4ecd8-0b30-4fea-af9c-f873db5fab45
