### ISSUE TITLE
[EcosystemTestTable]: Tooltip is using the wrong color

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3208]
### Steps to reproduce the problem

1. Go to https://qiskit.org/ecosystem
2. Click on any card that has an `EcosystemTestTable` (dropdown accordion)
3. Hover over an of the `<Information>` icons to reveal the tooltip
4. See the tooltips using purple

### What is the current behavior?

The Tooltips have a purple background

### What is the expected behavior?

I believe they should have consistency with the other Tooltip in the card (using the default dark/black background)

### Screenshots

https://github.com/Qiskit/qiskit.org/assets/6276074/a9e70900-fc20-4456-b73e-f2aa137350ed

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue
