### ISSUE TITLE
Bug: missing spaces in External Recommended readings

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3211]
### Where does the issue happen?

https://qiskit.org/learn/course/basics-quantum-information/

### What is the content issue?

In some of the External Recommended readings, we're missing spaces after the `,`

### Screenshots

![Screenshot 2023-05-12 at 7 36 50 AM](https://github.com/Qiskit/qiskit.org/assets/6276074/801768d7-46e5-4540-a810-a43824d3e52b)

**Comment by tungbq** [comment]
Hi @techtolentino do you need help? Can I pick up this task?
