### ISSUE TITLE
add a "found a problem" link to code examples

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3222]
As we include more code beyond Qiskit (providers, I'm looking at you :) ) in the website, other people will find issue that will need fix.

It would be great to have a quick way to report a mistake (something like this, but not necessarily this) 

![Screenshot 2023-05-16 at 14 42 44](https://github.com/Qiskit/qiskit.org/assets/766693/3bf76f29-6f06-4341-b952-6910e1a9ea9f)

(the link you also be in the boxes in https://qiskit.org/providers/)

In this case, the link should point to https://github.com/Qiskit/qiskit.org/issues/new?template=provider-update.yml

**Comment by eddybrando** [comment]
Is this the final design? I believe that the space between interactive elements (button and link) might be too small and could cause issues for touch-screen users, like users in smartphones. 🤔

If we still need a design proposal we can work on that. 🙂

**Comment by JRussellHuffman** [comment]
Personally, I don't think we should include this on the home page. Both the home page and the provider page are functionally marketing pages and there really should never be errors on those pages, especially consider the code doesn't run on those pages. If this feature was in the docs pages, I think it makes sense, but on our home page, it feels like we are selling ourselves short.

But, if there is a use case here that I don't understand (which is definitely possible), we could do a few things possibly:

**Comment by techtolentino** [comment]
(gentle nudge)

@1ucian0 - just seeing if you saw Russell's feedback

**Comment by 1ucian0** [comment]
I agree that "found a problem" is not the best phrasing. The code in those boxes involve third parties that might want to let us know that something is not right (for example, because they make an update on their end). I'm good with any method that allows other so let us know that the code needs change.

**Comment by techtolentino** [comment]
Just following up here:

I was able to have a conversation w/ @vabarbosa and learned a few things:

- they're replacing HotJar w/ Alchemer, which _does_ provide flexibility (modals, widgets, inline CTA), however:
  - a survey isn't the correct interaction for this requirement
  - we would have to go into a dashboard to see user feedback

Instead, the user need here might best be summarized like so:

> As a user, I need a clear way to report an issue in that I find in a Provider code example.


And to follow the spirit of open-source, we should guide users to [this new Provider issue template](https://github.com/Qiskit/qiskit.org/issues/new?assignees=1ucian0&labels=provider+code&projects=&template=provider-update.yml&title=%5Bprovider+%3Cname%3E%5D%3A+%3Cdescription%3E), where they can effectively call out any change that is needed.

**Comment by y4izus** [comment]
The component mentioned has been removed, so we can close this issue
