### ISSUE TITLE
quantilier -> quantalier

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#324]
Change all instances of quantilier to quantalier on this webpage

https://community.qiskit.org/experiments/quantilier

and any webpages referencing it, if needed

Ideally before qiskit camp tokyo starts

**Comment by delapuente** [comment]
@lerongil priority?

**Comment by delapuente** [comment]
Also, removing assessment in effort until the development team could provide it.

**Comment by lerongil** [comment]
I updated this in the video too - thanks @y4izus!
