### ISSUE TITLE
Card component title consistency

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3261]
### Feature description

As we prepare to roll out the QAMP cards, we now have two card treatments that use the same component; however, the Ecosystem cards have a larger header size.

We should use the same type size. 
(I personally recommend removing the `font-size: 20px` style rule in the Ecosystem card)

https://github.com/Qiskit/qiskit.org/assets/6276074/f886dee5-3703-4f2b-b91e-1b251956e5fc

**Comment by eddybrando** [comment]
There was an internal agreement in the team to remove the `font-size: 20px`, so we'll do that.
