### ISSUE TITLE
[Ecosystem] Create toggle between Card and Table view

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3274]
### Feature description

In the [Ecosystem page](https://qiskit.org/ecosystem/) we want to give the user the option to toggle between a "card" and a "table" view of the ecosystem projects.

### Additional context

![image](https://github.com/Qiskit/qiskit.org/assets/22047320/ad594d54-ef05-4d2b-a87d-127579fed76f)

**Design:** https://www.figma.com/file/N34caXM86bY1778Whk1c31/2503-ecosystem-page?type=design&node-id=705-7376&t=ME2tYW6PZjJE7YQi-0

**Comment by techtolentino** [comment]
Closing this for now since we'll not be using a table view
