### ISSUE TITLE
[Ecosystem] Create "Table" view

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3276]
### Feature description

We need to create a "Table" view of the projects in the [Ecosystem page](https://qiskit.org/ecosystem/).

If we find a Carbon component that already handles searching and pagination out-of-the-box, we should try to use it. If not, we will need to create new GitHub issues to address these features separately in new PRs.

### Additional context

![Screenshot 2023-05-30 at 14 15 34](https://github.com/Qiskit/qiskit.org/assets/22047320/f6e94694-5e2d-4683-971f-05f49262d5d6)

**Design:** https://www.figma.com/file/N34caXM86bY1778Whk1c31/2503-ecosystem-page?type=design&node-id=705-7376&t=ME2tYW6PZjJE7YQi-0

**Comment by y4izus** [comment]
Per offline conversations we decided not to work on this view right now, so I'm gonna close it
