### ISSUE TITLE
Bug: UiMultiselect component not working in desktop (mobile view)

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3282]
### Steps to reproduce the problem

1. Go to qiskit.org/events, using a desktop, but mobile view (inspect element)
2. Try using the `UiMultiselect` component 
3. See that nothing happens

(it works on an actual phone, but not in a desktop browser, making it difficult for devs to do development work)

### What is the current behavior?

Nothing happens - options are not being selected

### What is the expected behavior?

Options should be selected, the same way shown in the [bx-multiselect storybook](https://web-components.carbondesignsystem.com/?path=/story/components-multi-select--default)

### Screenshots

https://github.com/Qiskit/qiskit.org/assets/6276074/163c319f-7f1c-4560-ba66-4a6d10328fb5

### Device

Macbook

### OS

MacOS Ventura 13.4

### Browser

Chrome, inspect element

**Comment by y4izus** [comment]
Could you double check it? it's working for me 😕

**Comment by y4izus** [comment]
Confirmed, it's working, we can close it
