### ISSUE TITLE
Remove links from the landing page that are not Qiskit

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3289]
The following elements should be removed from the landing page:

- [ ] the twitching tile to Metal
- [ ] the top navbar (blocked by https://github.com/Qiskit/qiskit.org/issues/3170)
![Screenshot 2023-06-02 at 16 27 57](https://github.com/Qiskit/qiskit.org/assets/766693/a8c8bfa1-a643-48e7-894f-b23a56fe1a34)

**Comment by y4izus** [comment]
Per offline conversations, we have to:

- the twitching tile to Metal
- just the link to metal on the top menu
