### ISSUE TITLE
elements webpage information not useful

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#330]
on the elements webpages
 
(https://qiskit.org/terra, https://qiskit.org/aqua, https://qiskit.org/aer, https://qiskit.org/ignis)

users reported
- not understanding the purpose or information conveyed by contents under "stack"
- not understanding code example, wanting more comments in the code
- thinking stack content and code example content were related due to design proximity 

users wanted to see
- links to algorithms within each element
- links to github tutorials related to each element

**Comment by lerongil** [comment]
Stack seems to be referencing the feature set of that specific element and not the actual stack of the element.
