### ISSUE TITLE
user expectations of community page 

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#332]
sponsored users report expectations for community page to be 
- calendar of events
- blog
- forum to talk with other users
- announcements of new updates / qiskit versions

users liked the content they saw on the community page but they did not expect to find it there.

**Comment by CatherineKlauss** [comment]
possible solutions include
- moving some content, such as education, to its own tab (#288)
- renaming community website

**Comment by lerongil** [comment]
I like this - in regards to announcements of new updates/qiskit version, I believe that is something we should consider for the front page of qiskit.org.
