### ISSUE TITLE
users dont like tutorials being on IQX

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#335]
sponsored users did not like that "tutorials" link on qiskit front page takes them to the IBMQ account. users reported expecting to go to github

**Comment by CatherineKlauss** [comment]
a possible solution is to have two tutorial options:
"tutorials on IQX"
"tutorials on github"

**Comment by y4izus** [comment]
@lerongil, I think this is the same as [this one](https://github.com/Qiskit/qiskit.org/issues/462) that is already closed. We can close this one, right?

**Comment by lerongil** [comment]
Yup - will close.
