### ISSUE TITLE
As a developer or designer working on Qiskit.org, I want to have an updated Figma resource, so that I can reference when coding and designing and keep it consistent.

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3358]
### Feature description

There are several situations that make us need that resource:
- We have lost the alignment between Figma and qiskit.org. 
- Our design capacity has decreased, so we need to be more efficient on this side (@eddybrando proposed to create an assets library). 
- @Eric-Arellano and @javabster are working on the documentation and they need more clarity with the qiskit.org designs , so they can be align with the rest of the site

If @JRussellHuffman agrees, we can use the [file that already exists](https://www.figma.com/file/PDbN8wcg5WteWVvinjAEUv/qiskit.org-main--file?type=design&node-id=3-2574&t=HKmf9AVUwg0ZJfzp-0) and update it

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/qiskit.org/issues/3359
- [ ] https://github.com/Qiskit/qiskit.org/issues/3360
```

**Comment by JRussellHuffman** [comment]
There is actually another figma file [here](https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?type=design&node-id=2671%3A5547&t=65I9f4HAbcC5AIYI-1) that was originally used as the asset library for everything. But it has gotten stale over time.

**Comment by eddybrando** [comment]
We will only create the Figma designs for the core components and pages of Qiskit.org.

We'll try to keep the definitions simple and use Carbon variables whenever possible to also facility the work with other teams.
