### ISSUE TITLE
Update the style guideline and library of assets / components in Figma for Qiskit.org

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3359]
We will only create the Figma designs for the core components and pages of Qiskit.org.

We'll try to keep the definitions simple and use Carbon variables whenever possible to also facility the work with other teams and possibly create a path for our own refactoring and simplification of the codebase.

**Comment by y4izus** [comment]
Deprioritize until we know if the designs are gonna change

**Comment by eddybrando** [comment]
We will only create the Figma designs for the core components and pages of Qiskit.org.

We'll try to keep the definitions simple and use Carbon variables whenever possible to also facility the work with other teams and possibly create a path for our own refactoring and simplification of the codebase.

**Comment by y4izus** [comment]
This issue is not relevant anymore, so I close it
