### ISSUE TITLE
Define standards for content and components

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3364]
## The problem
We currently pull in content from various sources and use this data to render different parts of the Qiskit org experience. Our this data is used in places such as `/events`, `/advocates`, and `/ecosystem`. For the most part, we leverage some variation of our `UiCard` component, to display this content.

The problem is that, because the content can widely vary, it creates an inconsistency in the UI, and this can cause undesirable aesthetics or even a bit of confusion, at times. 

### Acceptance criteria 
We should establish and document a set of standards/guidelines for the following:

- Card `name` or `title` 
- Card `description`
- Card `image` (dimensions, centering, etc - essentially guidelines on the best workable/scalable images for cards)

**As a fallback**
- our UI should also be able to handle inconsistent, even non-existent `string` lengths.
- our UI should be able to elegantly handle missing images 

### The outcome
- [ ] Documented standards
- [ ] Any updates to the code that is needed to improve the consistency, or, handle edge cases

___

## Screenshots of the inconsistency issues
![Screenshot 2023-06-20 at 9 56 20 AM (2)](https://github.com/Qiskit/qiskit.org/assets/6276074/4db44640-f109-49b9-b570-502f2f4f7332)

![Screenshot 2023-06-20 at 10 01 22 AM (2)](https://github.com/Qiskit/qiskit.org/assets/6276074/4f8d6ebc-4c81-4c52-b6c5-9f239e800c0a)

![Screenshot 2023-06-20 at 10 04 15 AM (2)](https://github.com/Qiskit/qiskit.org/assets/6276074/382e900f-b614-4dc3-aa50-540cf634a798)

**Comment by techtolentino** [comment]
Update: designs are currently being reviewed by @JRussellHuffman

**Comment by techtolentino** [comment]
Content guidelines are [viewable in Figma](https://www.figma.com/file/025EpGKBt27LQXuoFOhCp2/Qiskit-Card-content-guidelines?type=design&node-id=222-1591&mode=design&t=Zmcm9j5r23R9y08v-4)

**Comment by eddybrando** [comment]
Thanks a lot for this @techtolentino! I think this can be now marked as done.
