### ISSUE TITLE
Implement VS Code Dev Container

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3365]
This issue aims to implement a Visual Studio Code Dev Container to enhance the development experience.

By leveraging Docker and Visual Studio Code's Remote - Containers extension, we will be able provide a consistent and reproducible environment. This ensures consistency, reproducibility, and scalability for developers.

### Tasks

- [ ] Docker setup
- [ ] Dev Container definition
- [ ] Integration with VS Code

**Comment by eddybrando** [comment]
We decided to close this issue for the time being, since installing Node v18 is already easy enough and probably easier than setting up Docker Desktop or an alternative like Rancher Desktop, only to end up with a machine with Node v18 as well.
