### ISSUE TITLE
users want to see external users on community page

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#337]
sponsored users report wanting to see external users on community page, specifically under experiment highlights and advocates. 

Even though the experiments and advocates highlighted are not promoted as being IBM associates, the sponsored users recognized all or some of the projects / people as being internal to IBM.

**Comment by CatherineKlauss** [comment]
possible solution: put external affiliation of all non-IBMers, and be honest about which projects/people are from within IBM, so even if a few reps are from within IBM the user does not assume that all are from within IBM

**Comment by delapuente** [comment]
@CatherineKlauss, would you mind to clarify what do you mean by "to see external users"? You mean "contributions of non IBM users"?

**Comment by CatherineKlauss** [comment]
Yes, exactly. And know that they are non-IBMers, as seeing 1-2 IBMers not identified as IBMers in the mix makes it look like we’re trying to pass of a whole bunch of IBMer-based work as from the community.
