### ISSUE TITLE
Bug: category filter on ecosystem page is very slow

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3370]
### Steps to reproduce the problem

1. Go to qiskit.org/ecosystem
2. Click on any category filter
3. try to unclick the filter
4. wait 5 seconds
5. see that it takes a long time for the filter to become "unchecked"

Not sure how widespread this issue is, everything else on the qiskit.org site loads very quickly for me, but this is feature is super slow. I'm using a chrome browser if that helps

### What is the current behavior?

category filter is very slow to uncheck

### What is the expected behavior?

category filter should uncheck immediately on clicking

**Comment by eddybrando** [comment]
Related to: https://github.com/Qiskit/qiskit.org/issues/3368
