### ISSUE TITLE
[Ecosystem] update search result text to suggest looking at other tiers

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3400]
when using the search/filter functionality on the ecosystem page it is sometimes unclear that just because there are no results for a given tier, there may actually be results for another tier.

For example, in the following example the filter result message implies that there are no projects that match the criteria AT ALL, when in fact there are just no results in the current tier tab

<img width="1101" alt="Screenshot 2023-07-05 at 2 00 02 PM" src="https://github.com/Qiskit/qiskit.org/assets/23662430/b0f90da1-4c2b-432a-b94a-b5a00384c2fd">

Can we update the search result text to suggest the user search for other tiers, rather than just the generic suggestion of widening their search criteria? possibly might even be nice to be more specific and say that while there are no results in this tier there are X results in Y tier

**Comment by y4izus** [comment]
This problem will be fixed with the solution proposed [here](https://github.com/Qiskit/qiskit.org/issues/3404#issuecomment-1641731227), so I will close this issue in favor of [the one that will build the solution](https://github.com/Qiskit/qiskit.org/issues/3404)
