### ISSUE TITLE
[Ecosystem] rethink how we display tiers?

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3404]
The way we have redesigned the ecosystem page to use different tabs for each tiers and search/filtering within the tabs presumes that users have an understanding/need for the tier differentiation, but perhaps this is not as relevant as we originally assumed.

This comment/question in slack illustrates this, and it was upvoted a few times implying that others had the same feeling:

> Is there a way to filter across the 3 groups? Like for me the main, ecosystem, and community separation doesn't mean anything and I just want to find the ecosystem projects that are plugins or converters

I think in general having the tabs is useful but perhaps there are some adjustments we could make to help users find what they're looking for more easily. Probably requires further discussion and design input, but possible solutions could be:

- move the search box and filtering components outside of the tier tabs to make it clearer that searching/filtering applies to all the tabs?
- create an "all projects" tab where all the projects are listed out, in addition to the tiers tab

**Comment by y4izus** [comment]
Per offline conversations, this is the new design:

- Move the tiers to the sidebar left, creating a new section for filtering by tier
- It is important to have an explanation of the different tiers we have, so we will use the same structure (see image) we have on the advocates page right after the header to explain the 3 tiers we have:
<img width="1298" alt="Captura de pantalla 2023-07-19 a las 11 15 59" src="https://github.com/Qiskit/qiskit.org/assets/17231966/ac1280a6-045e-43e9-b7ed-f1fe5a4294a3">
- We still need the final content, but we can start building the structure

**Comment by techtolentino** [comment]
Leaving some notes from our sync as a team, on how we'll be handling this:

- Page header
  - [ ] add the purple cards to the hero of the page, with each card being an opportunity to define each tier
  - [ ] use a similar layout / structure to what we have on the Advocates page
  
- Tabs
  - [ ] remove the Tabs that separate tiers
  - [ ] remove logic for showing results count

- Filters
  - [ ] add a filter section for Tiers
