### ISSUE TITLE
Remove the course "Understanding Quantum Information and Computation"

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3408]
### Feature description

With the launch of the new learning platform, some course were migrated and this is one of them. We need to remove all the references to this course on qiskit.org

**Acceptance criteria**

- [x] Update the card on the [learn page ](https://qiskit.org/learn/), following [this](https://github.com/Qiskit/qiskit.org/issues/3408#issuecomment-1634182353) comment
![Captura de pantalla 2023-07-07 a las 12 45 33](https://github.com/Qiskit/qiskit.org/assets/17231966/a3c42312-cdf4-4940-9c84-56337472354c)

- [x] Delete the [course description page](https://qiskit.org/learn/course/basics-quantum-information/)
- [x] Create a redirection from the above page to the new page on the new learning platform. Done [here](https://github.ibm.com/IBM-Q-Software/cloud-deployment/pull/6241)
- [x] Check if there are images that are used only for this course and remove them
- [x] ~Removes the course links from the mega menu dropdown~. Having the redirections, we can postpone this tasks until we define a better migration plan

![Captura de pantalla 2023-07-07 a las 12 45 09](https://github.com/Qiskit/qiskit.org/assets/17231966/7e42bacf-d3ab-4991-992c-142e1672b640)

This course has two units, so we need to remove the second unit too. So we should also:

- [x] Update the card on the [learn page ](https://qiskit.org/learn/), following [this](https://github.com/Qiskit/qiskit.org/issues/3408#issuecomment-1634182353) comment
![Captura de pantalla 2023-07-13 a las 14 13 17](https://github.com/Qiskit/qiskit.org/assets/17231966/d787fa96-158c-4c4d-be1c-755bc2050bd5)

- [x] Delete the [course description page](https://qiskit.org/learn/course/fundamentals-quantum-algorithms/)
- [x] Make sure that the redirection is created. Done [here](https://github.ibm.com/IBM-Q-Software/cloud-deployment/pull/6241)
- [x] Check if there are images that are used only for this course and remove them

### Additional context

Do the PR to the `feat/sunset-learn-01` branch

**Comment by y4izus** [comment]
On hold because there is still [conversations ongoing](https://github.ibm.com/IBM-Q-Software/saiba/issues/478#issuecomment-59701870)

**Comment by 1ucian0** [comment]
- [ ] Change CTA text to "Take this course in IBM Quantum Learning" (this adds the "external link" visual automatically? otherwise, let's add it)
- [ ] Move Unit 2 card next to Unit 1.
