### ISSUE TITLE
Remove course "Variational Algorithm Design"

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3409]
### Feature description

With the launch of the new learning platform, some course were migrated and this is one of them. We need to remove all the references to this course on qiskit.org

**Acceptance criteria**

- [x] Update the card on the [learn page ](https://qiskit.org/learn/), following [this](https://github.com/Qiskit/qiskit.org/issues/3408#issuecomment-1634182353) comment
![Captura de pantalla 2023-07-07 a las 12 49 21](https://github.com/Qiskit/qiskit.org/assets/17231966/d2345e86-5965-4cdd-ba99-fff565b1a80f)

- [x] Delete the [course description page](https://qiskit.org/learn/course/algorithm-design/)
- [x] Create a redirection from the above page to the new page on the new learning platform. Done [here](https://github.ibm.com/IBM-Q-Software/cloud-deployment/pull/6241)
- [x] Check if there are images that are used only for this course and remove them
- [x] ~Removes the course links from the mega menu dropdown~. Having the redirections, we can postpone this tasks until we define a better migration plan
![Captura de pantalla 2023-07-07 a las 12 50 00](https://github.com/Qiskit/qiskit.org/assets/17231966/4479fc91-4c5a-491a-a83c-e7f205823f1c)

### Additional context

Do the changes but not merge them until the learning platform team says is the moment to go live

**Comment by RickleAndMortimer** [comment]
I'd be happy to work on this issue!

**Comment by y4izus** [comment]
Thanks @RickleAndMortimer !! but we can't start with this issue yet, I have to add the On hold label because there is still [internal conversations ongoing](https://github.ibm.com/IBM-Q-Software/saiba/issues/478#issuecomment-59701870)

**Comment by 1ucian0** [comment]
- [ ] Change CTA text to "Take this course in IBM Quantum Learning" (this adds the "external link" visual automatically? otherwise, let's add it)
