### ISSUE TITLE
VarQITE docs Source  link is not working

### ISSUE THREAD

**Issue by Raghav-Bell** [Qiskit/qiskit.org#3417]
### Where does the issue happen?

https://qiskit.org/documentation/stubs/qiskit.algorithms.VarQITE.html#varqite

### What is the content issue?

VarQITE documentation Source link is not working (as shown in screenshot).

### Screenshots

![image](https://github.com/Qiskit/qiskit.org/assets/83136390/cb880e78-c1a7-4e53-89d7-b917ec6fcd84)

### Additional information

It should redirect to [Source code for qiskit.algorithms.time_evolvers.variational.var_qite](https://qiskit.org/documentation/_modules/qiskit/algorithms/time_evolvers/variational/var_qite.html#VarQITE)

**Comment by jackoconnordev** [comment]
Hi @Raghav-Bell, I'm rather infuriatingly unable to capture my mouse pointer in a screenshot so hopefully these edited images will make sense.

The red boxes I've drawn on top of the following screenshots highlight the clickable areas that when clicked take you to the corresponding source code page.

In Grover search the entire text box is clickable, while in VarQITE the box is shifted down and the top half of the text [SOURCE] is not part of the link. I would imagine the same is the case for you as I am just using the online version of the website?

<img width="1004" alt="grover-source" src="https://github.com/Qiskit/qiskit.org/assets/134723582/7e7e9d10-9d87-4113-a686-c05a49d9af89">

If the lower half of VarQite is clicked then I am redirected to the source code you linked [Source code for qiskit.algorithms.time_evolvers.variational.var_qite](https://qiskit.org/documentation/_modules/qiskit/algorithms/time_evolvers/variational/var_qite.html#VarQITE)

<img width="1004" alt="varqite-source" src="https://github.com/Qiskit/qiskit.org/assets/134723582/421837c2-a9be-4b03-b71d-372146444305">

---------------------------------------------------------------------------------------------------------

The function signature content on the VarQITE page seems to be overflowing its container which doesn't happen on the grover page.

<img width="1491" alt="grover-no-content-overflow" src="https://github.com/Qiskit/qiskit.org/assets/134723582/0f7aa71a-a021-4453-b6c6-db881baaf70f">

<img width="1491" alt="varqite-content-overflow" src="https://github.com/Qiskit/qiskit.org/assets/134723582/2c9e6e9e-17fc-4bad-855d-7f58b18e7f71">
 
---------------------------------------------------------------------------------------------------------

There are also differences in the number of styles included in the head of each page after the segment analytics tag but I don't know what the implications or reasons of that are, if any.

<img width="1491" alt="grover-styles-in-head" src="https://github.com/Qiskit/qiskit.org/assets/134723582/f11ffd49-265d-460c-a25c-efee57d87b1e">
<img width="1491" alt="varqite-styles-in-head" src="https://github.com/Qiskit/qiskit.org/assets/134723582/0399dd4c-fc51-413b-aedd-7fecd81ec467">

**Comment by Raghav-Bell** [comment]
Thanks @jackoconnordev for clearly explaining the bug, your screenshots will help the maintainers/contributors to debug it fast.

**Comment by y4izus** [comment]
there is a [new page for VarQITE docs](https://docs.quantum.ibm.com/api/qiskit/qiskit.algorithms.VarQITE) and this error doesn't exist right now, so I close this issue
