### ISSUE TITLE
code highlighting?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3421]
The landing page has several boxes with code. It would be great to have code highlighting for easy reading.

**Comment by jackoconnordev** [comment]
Is there a preference for the theme of the code highlighting? Jupyter notebooks and IBM Quantum could be two options that people would be familiar with.

And would the way to implement this be just wrapping all relevant pieces of text with span tags to match a given code highlighting theme?

_Note: Comment colour on current website does not match comment colour of jupyter notebook or IBM Quantum notebook._

## Current
<img width="865" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/18686965-6ab0-4dab-b1a7-7b5983e71b67">

## Jupyter notebook code highlighting

<img width="561" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/ecc7a0c0-22a3-45a0-9a9c-9c367e5e32d2">

## IBM Quantum code highlighting

<img width="561" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/67928cef-8eb2-4eed-81cf-9ca3d8387346">

<img width="561" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/5c3e914a-419f-40a4-90da-38f3eaffdc25">

**Comment by jackoconnordev** [comment]
There's a package called highlight.js that could be an easy way to get code highlighting on the website.

It has a script on a cdn that can be pulled in (or else can just be npm installed) that gives access to a function called `highlightAll` which applies syntax highlighting and theme of your choice to any text that's wrapped in `<pre><code>...<code><pre>` tags.


Small blog post talking about it: https://blog.robbie.digital/posts/highlight-js

**Comment by y4izus** [comment]
This issue is no relevant anymore, so I close it
