### ISSUE TITLE
Add Alchemer survey to Qiskit.org

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3439]
We need to add a survey to our Qiskit.org site with **[Alchemer](https://www.alchemer.com/)** using what they call [website intercept](https://help.alchemer.com/help/website-intercept).

- [x] Add Alchemer's Beacon (JavaScript code) to the site
- [x] ~Create CSS to style survey box~ (The modal uses an iframe with a fixed CSS width inside. We cannot modify it from outside of the iframe)

The scope has been extended after a review:

- [x] Add "feedback" tab (fixed to the right, centered vertically, with text from top to bottom that triggers the survey)
- [x] Change survey text (requires input from @1ucian0)

**Comment by eddybrando** [comment]
Added "needs information" since we need input about the text and general content that will be displayed in the popup.
