### ISSUE TITLE
Copy button text change for calendar subscription links

### ISSUE THREAD

**Issue by jackoconnordev** [Qiskit/qiskit.org#3454]
## Current behaviour

Current copy button text after pressing the copy button is "Copy calendar sync url".

This could be misleading as it implies that there is another action to take in order to copy the link text to the clipboard.

## Suggested change

Change the popup text to "Copied calendar sync url" to make it clear that the link has already been copied to the clipboard after pressing the button the first time.

I've included screenshots of the what the suggested change would look like. I'm not a UX guy by any means so if this is not a good idea I'd love to know why.

### Current behaviour

<img width="699" alt="Screenshot 2023-07-26 at 20 44 09" src="https://github.com/Qiskit/qiskit.org/assets/134723582/4dc35c34-66a9-46b3-831a-35c7eded91d9">

### Suggested Change

<img width="699" alt="Screenshot 2023-07-26 at 20 48 01" src="https://github.com/Qiskit/qiskit.org/assets/134723582/21d447ae-5d2f-4ad8-a63a-51ce0d341224">

**Comment by techtolentino** [comment]
@jackoconnordev - sounds like a good suggestion, and it follows some of the other code snippet buttons where if a user copies the code, the feedback says "Copied"

I say go for it.

Thank you

**Comment by eddybrando** [comment]
Nice catch @jackoconnordev, thank you very much!

I suggest to keep it simple and consistent with the other elements in the page and rename it to "Copied!", which is how we're displaying it right now in other parts:

![Screenshot 2023-07-28 at 13 26 58](https://github.com/Qiskit/qiskit.org/assets/22047320/a3c4212f-e0a3-4ac8-b433-4d04de5519da)

**Comment by jackoconnordev** [comment]
Sounds good and thanks for the feedback 👍. I can make that change this evening
