### ISSUE TITLE
Qiskit Camp 2020 page needed

### ISSUE THREAD

**Issue by justjosie** [Qiskit/qiskit.org#346]
WEBSITE CONTENT

**What is Qiskit Camp?**
Qiskit Camp brings together the quantum community for an immersive three days of training sessions, deep technical talks, and a hackathon with the Qiskit core development team. Learn about new updates to Qiskit and meet the people building it.

Taking place after the annual APS 2020 meeting, the invite-only experience includes a one-day conference at IBM Q research headquarters before embarking to a mountain resort where we will host a hackathon competition in a barn, enjoy winter campfires, and many other surprises!

Transportation, accommodation*, entertainment and food is included.

_* The Mountain Top Inn & Resort consists of cabins where hackathon team members can opt in to be co-located in shared cabin space with priority given to students or others needing travel assistance. A limited number of individual accommodations will be available, so we ask that you make your own bookings if that is preferred._

**When & Where?**
March 10
IBM Thomas J. Watson Research Center
Yorktown Heights, NY
One day conference with talks and training sessions with the Qiskit core team, including a visit to the lab to see real quantum computers.

March 11-13
Mountain Top Inn & Resort
Killington, VT
From the research center, attendees will head to the mountain resort for the hackathon, awards, after-party and winter snow activities.

**Agenda**
- coming soon - 

**Code of Conduct**
(same as content from qiskit.camp/africa)

OTHER NOTES/REFERENCE SITE

Original 2019 site (for reference)
qiskit.camp

(if at all possible, would love to feature the 2019 recap video on the new page in a similar fashion as the 2019 page, thank you!)

**Comment by KallieFerguson** [comment]
@lerongil can you add the old photo from the original Qiskit Camp Vermont so that it's the correct photo for this website?

Also we need the link to be qiskit.camp/2020

**Comment by lerongil** [comment]
PR #372 should update the background. I'd like Salva to review when he returns. The link will also be created by him.

**Comment by delapuente** [comment]
The shortcut https://qiskit.camp/2020 has been created and #347 is merged. Closing.
