### ISSUE TITLE
replace ibm q awards dec 13

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#348]
ibm q awards ends on dec 13. After that date, replace that section of the website with a link to the Qiskit Camp 2020 announcement

**Comment by lerongil** [comment]
@CatherineKlauss - Can you please add the suggested copy?

**Comment by CatherineKlauss** [comment]
Your favorite flagship event is returning, now with an even larger and more diverse community. Learn more about [Qiskit Camp 2020](https://medium.com/qiskit/qiskit-camp-2020-coming-next-march-7b8c39e5d42c), collapsing March 10–13.


I could take or leave the collapsing pun, anyone for or against it?

**Comment by lerongil** [comment]
This should be updated and since Catherine is OOO, I will update this
