### ISSUE TITLE
Information architecture and benchmark (UX) for Qiskit.org

### ISSUE THREAD

**Issue by marinaaisa** [Qiskit/qiskit.org#349]
Information architecture and benchmark (UX) for Qiskit.org.

You can find the work done so far here on Figma: https://www.figma.com/file/1zOwVzeDZiV6mAWVBmomGZ/qiskit-site-architecture?node-id=1%3A23

**Comment by JRussellHuffman** [comment]
Synthesizing the work in the above figma file into a keynote here: https://ibm.box.com/s/xg88udy8yzyk3u8a8zo4o0fp723tgub5

**Comment by JRussellHuffman** [comment]
Latest keynote of synthesized work is here: https://ibm.box.com/s/65zpq27eoc6c2tglf5vzqrw4sgkft6ay

Latest figma work can be found the page title `site architecture and user flows` in this file: https://www.figma.com/file/1zOwVzeDZiV6mAWVBmomGZ/qiskit-site-architecture?node-id=283%3A8

**Comment by JRussellHuffman** [comment]
In the beginning of the year, Elizabeth and I will be engaging with the qiskit advocates and quantum ambassadors to do tree testing and card sorting research activities. 

More about that effort is listed here: https://github.ibm.com/IBM-Q-Software/IQX-Design/issues/119#issuecomment-16697833

**Comment by JRussellHuffman** [comment]
So far we have 14 individuals volunteer to participate in the card sorting test. All of them have been sent the URPA with 2 participants being IBMers and therefore not needing the URPA. 7 have signed and returned the URPA, and have been sent the link to the test. 4 have completed the test. We requests the tests be complete by Friday, Jan 10th.

**Comment by lerongil** [comment]
@JRussellHuffman @marinaaisa Can we scope this issue down a bit so it doesn't hang out in the backlog? One possible suggestion could be to edit the title of this card specifically for the card sorting activity, up to you both.

**Comment by JRussellHuffman** [comment]
Certainly. For now, I think it makes sense to break it into 3 issues
1- card sort usability
2- user flows
3- overall information architecture.

**Comment by JRussellHuffman** [comment]
Fyi @lerongil I split this issue into 3 (see above, #349, #401, #407). This work is being presented to the design agency on Wednesday (Jan 15), so will hope to close these issues after that presentation.

**Comment by JRussellHuffman** [comment]
@lerongil I'm scoping this issue to be about IA for the agency playback. It sounds like the work will be an ongoing effort, but will close the issue for now as the agency playback has come and gone.
