### ISSUE TITLE
Add 1XP announcements

### ISSUE THREAD

**Issue by mackinziblank** [Qiskit/qiskit.org#3494]
### Feature description

To announce 1XP and highlight the new Docs and Learning experiences being released, we should add a couple of announcements on Qiskit.org:

- [x] Home: Announcement section
  <img width="938" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/59657965/2dff9f2e-d637-4daa-827d-fe839ac5dd81">
- [x] Home: Banner
  ![Screenshot 2023-08-10 at 10 48 19](https://github.com/Qiskit/qiskit.org/assets/22047320/4d6dded7-6521-47b3-9422-56f5288dc65e)
- [x] Learn: Announcement section
  ![Screenshot 2023-08-10 at 10 48 56](https://github.com/Qiskit/qiskit.org/assets/22047320/e98f861a-6b4b-40d6-8941-a5c4c7705b34)
- [x] Course pages: Banner
  ![Screenshot 2023-08-10 at 10 49 31](https://github.com/Qiskit/qiskit.org/assets/22047320/dbcee526-b66b-45e4-bb1c-5bc01a33322b)

fyi @abb

### Additional context

- Design: https://www.figma.com/file/0Je6YtTaizU1Y7lCubTenn/Qiskit.org-page-updates

**Comment by eddybrando** [comment]
We need to include the changes from a feature branch to deliver them together with this PR.
