### ISSUE TITLE
Provide a template for filing bugs

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#351]
Per @y4izus suggestion, provide a template with steps to reproduce, actual and expected behaviour to provide a coherent structure to the bugs, specifically.

**Comment by lerongil** [comment]
Can we use the same template as the core qiskit template issues?

**Comment by delapuente** [comment]
@y4izus any thoughts?

**Comment by y4izus** [comment]
I think that having this is enough:

### Steps to reproduce the problem

### What is the current behavior?

### What is the expected behavior?
