### ISSUE TITLE
Bug: The advocates page only displays the first letter of the country

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3526]
### Where does the issue happen?

https://qiskit.org/advocates

### What is the content issue?

The list of advocates has cards with city and country of each advocate. Only the first letter of the country is displayed. 

### Screenshots

![Screenshot 2023-08-30 at 15 08 30](https://github.com/Qiskit/qiskit.org/assets/766693/2346d4d0-0cd8-47c4-a9bc-fe8c6750c566)
<img width="1144" alt="Screenshot 2023-08-30 at 15 04 07" src="https://github.com/Qiskit/qiskit.org/assets/766693/3cb3f76e-7fa9-43fe-ac12-3676a18cc4d5">

**Comment by jackoconnordev** [comment]
Hi guys, I did a very quick fix for this if that's okay https://github.com/Qiskit/qiskit.org/pull/3535. Still waiting to see if it builds but I would imagine it will?
