### ISSUE TITLE
Update banners content

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3555]
### Feature description

Banners content need to be updated

### Acceptance criteria

- [x] Updates content of the banner on the top on the qiskit.org page
- [x] Updates content of the banner on the announcement section on the qiskit.org page
- [x] Updates content of the banner on the announcement section on the qiskit.org/learn page
- [x] Updates content of the banner on the top on the qiskit.org/[course] page

**Comment by vabarbosa** [comment]
FYI, it looks like the `Check it out` and `Learn more` links need to also get updated to point to the new blog link:

https://github.com/Qiskit/qiskit.org/issues/3556#issuecomment-1766858215
