### ISSUE TITLE
Update Qiskit Banners for Sunset

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/qiskit.org#3556]
### Feature description

The current banners for the Qiskit Homepage must be updated to the new wording as we get closer to sunset. The "Check it out" links should link to the blog. All dates on the banners should be updated to November 29, 2023. The updated banners can be found [here](https://www.figma.com/file/0Je6YtTaizU1Y7lCubTenn/Qiskit.org-page-updates?type=design&node-id=442%3A5700&mode=design&t=XESKKfgkCymUNoBe-1)
<img width="754" alt="updated qiskit banner" src="https://github.com/Qiskit/qiskit.org/assets/89415444/bf40637f-4b5e-4691-b00c-6318ac0c1d6b">

**Comment by gracelindsell** [comment]
Please note: For all of the banners, the date should be November 29, 2023 as now shown in the designs [here](https://www.figma.com/file/0Je6YtTaizU1Y7lCubTenn/Qiskit.org-page-updates?type=design&node-id=442%3A5700&mode=design&t=5zmAw2jnAb0JLyeK-1) Additionally, the "check it out" and "learn more" should link out to the new blog.

**Comment by gracelindsell** [comment]
here is the link to the blog post for the learn more links in the banners: https://medium.com/qiskit/important-changes-to-qiskits-documentation-and-learning-7f4e346b19ab

**Comment by gracelindsell** [comment]
here is the link to the blog post for the learn more links in the banners: https://medium.com/qiskit/important-changes-to-qiskits-documentation-and-learning-7f4e346b19ab

**Comment by vabarbosa** [comment]
@gracelindsell i think this can be closed now

**Comment by y4izus** [comment]
this issue is done, closing it

**Comment by gracelindsell** [comment]
![image (7)](https://github.com/Qiskit/qiskit.org/assets/89415444/10bce2d7-e905-4340-9e08-559aab606ae6)
This banner needs to be updated to the correct dates as shown in the Figma designs, thanks!
