### ISSUE TITLE
qiskit.org/textbook build fails

### ISSUE THREAD

**Issue by aasfaw** [Qiskit/qiskit.org#379]
### Steps to reproduce the problem
Merge any pull request in the textbook repository ([github.com/Qiskit/qiskit-textbook](github.com/Qiskit/qiskit-textbook)). 
### What is the current behavior?
Merges to both `master` and `stable` fail.
### What is the expected behavior?
Merges to both branches should not fail. This change occurred after the textbook was moved from [community.qiskit.org/textbook](community.qiskit.org/textbook) to [qiskit.org/textbook](qiskit.org/textbook).

**Comment by aasfaw** [comment]
We should prioritize fixing this bug because it is blocking any updates to the textbook.

**Comment by delapuente** [comment]
Solved in Qiskit/qiskit-textbook@c97b55a
