### ISSUE TITLE
As a potential attendee, I want to see the upcoming events in my city in under 30 seconds 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#381]
Events team requested a way for potential attendees to see upcoming events. 

It might not necessarily in their city as they might be in a different region or traveling and would like to see events in another area.

**Comment by lerongil** [comment]
The team brought up an example they enjoyed: https://www.uipath.com/events. Specifically the regions, filters of regions and links to more details.

**Comment by delapuente** [comment]
We did it 🎉 !
