### ISSUE TITLE
As a potential attendee, I want to know what type of events are available, so that I know which event is right for me.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#383]
Some ideas of content the team had were recaps, blog posts, videos to get a better feel of the types of events. Surveys for what people say about the events. Email FAQ: [include here]

**Comment by lerongil** [comment]
[EmailFAQ.docx](https://github.com/Qiskit/qiskit.org/files/4031958/EmailFAQ.docx)

**Comment by lerongil** [comment]
#381 is related and will be affected by this one

**Comment by delapuente** [comment]
Also done 🎉
