### ISSUE TITLE
The word "collapsing" seems to be a misspelling

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#392]
The word "collapsing" in the sentence "Learn more about Qiskit Camp 2020, collapsing March 10–13" seems to be a misspelling of "coming".

**Comment by y4izus** [comment]
@CatherineKlauss could you give your opinion in order to advance with this issue? Thank you!!

**Comment by CatherineKlauss** [comment]
Looks spelled correctly to me, 
https://www.merriam-webster.com/thesaurus/collapsing

**Comment by nonhermitian** [comment]
So "Learn more about Qiskit Camp 2020, collapsing March 10–13." is correct then?

**Comment by CatherineKlauss** [comment]
"collapsing" is a pun on a wave function collapse for when the event culminates into existence. But if it's falling flat, we can write something more literal.

**Comment by nonhermitian** [comment]
It looks to me like someone who meant to say "coming" and made a mistake.

**Comment by delapuente** [comment]
You are not the one thinking the same and this has been reported internally a couple of times more. Now it is solved.
