### ISSUE TITLE
Add new advocates to the existing landing page

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#397]
Currently advocates are highlighted here: https://community.qiskit.org/advocates

We need to add the new cohorts to this page, contact me for information

**Comment by delapuente** [comment]
Do we have the pictures for all of them? If we are thinking of an alternative representation of the advocates list, we will need a new design.

**Comment by lerongil** [comment]
I'd like to keep the current struct of the page without a new design but have a see more feature as to not display the entire list.

**Comment by delapuente** [comment]
Sure, let's start adding 20 of them and see how it feels and we will come up with some kind of pagination not to display all of them in first place.

**Comment by lerongil** [comment]
As discussed, we should try and use the same mechanism as we did for events page and airtable for this as well.

**Comment by delapuente** [comment]
Yes! We can prioritize this after the preparation milestone.
