### ISSUE TITLE
Keep the texbook TOC preview in qiskit.org/education up to date

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#419]
After merging https://github.com/Qiskit/qiskit-textbook/pull/163 the textbook no longer will trigger a new deployment of the website so the textbook preview may fall out of sync when the TOC is altered.

We should find a solution in the textbook or qiskit.org end for dealing with this avoiding triggering a new deployment all the times the textbook is changed.

**Comment by lerongil** [comment]
Is this still an open issue?

**Comment by delapuente** [comment]
Since we set up the daily cron for the event site, this no longer applies.
