### ISSUE TITLE
 The visitor should identify the correct IBM Quantum brand across the web

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#420]
Replace instances of "IBM Q" with "IBM Quantum" attending to the IBM Quantum guidelines.

**Comment by lerongil** [comment]
To do for Leron: Validate IBM Q Community and IBM Q Account need to be updated as well.

**Comment by delapuente** [comment]
We will address what we know and open a follow-up for IBM Q Account and IBM Q Community if we did not receive the information.
