### ISSUE TITLE
Adapt source for being able of feeding the event index

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#437]
Add and polish record information in the source for being able of displaying all the required information in the event index.

**Comment by delapuente** [comment]
Need to clarify #527 and #526 for closing it. Removing on hold since we started the conversations with Events and it is "in progress".

**Comment by delapuente** [comment]
Actual implementation has code to handle both situations but we should decide in favour of one towards MVP 2.0.

**Comment by y4izus** [comment]
The questions we needed to clarify are already solved and implemented on the page, so I close this issue
