### ISSUE TITLE
UI Mobile version (design)

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#439]
Mobile layout for the event index page and for the individual event

**Comment by marinaaisa** [comment]
You can see, apply filters and reset them at the mobile prototype here: https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-Events-index?node-id=234%3A3205&viewport=-752%2C2636%2C1&scaling=min-zoom Please, provide feedback. This mobile screen is the smallest screen IBM supports: 320px (iPhone 5).

**Comment by delapuente** [comment]
Let's consider this done.
