### ISSUE TITLE
Where can I find key for qiskit quantum gates?

### ISSUE THREAD

**Issue by daniv234** [Qiskit/qiskit.org#45]
the only gates I saw in youtube are Hadamart  and CNOT
when: 
q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q,c)
#hadamart 
qc.h(q[0])
#CNOT
qc.cx(q[0],q[1])

I want to know how to write the gate U3=U3(theta,lambada,gama) in qiskit language
but I only find it on the Internet in Qasm language as: u3(theta,lambada,gama) iv`e tried it on qiskit but there is always error messege when I try to run the program.

**Comment by abdonrd** [comment]
Hi @daniv234!

This repository is about the [qiskit.org](https://qiskit.org) website.
Probably [Qiskit/qiskit-terra](https://github.com/Qiskit/qiskit-terra) is a better place to ask your question.
