### ISSUE TITLE
qiskit.org landing page still shows qcamp vermont as happening

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#450]
### Steps to reproduce the problem

```
Your favorite flagship event is returning, now with an even larger and more diverse community. Learn more about Qiskit Camp 2020, coming March 10–13.
```

**Comment by delapuente** [comment]
In the landing page of qiskit.org, the text regarding Qiskit Camp Vermont continue saying it is happening on March 10-13 but given the problem with COVID-19, the Camp has been delayed and new dates are TBD.

> Your favorite flagship event is returning, now with an even larger and more diverse community. Learn more about Qiskit Camp 2020, coming March 10–13.

@justjosie should we update this? If so, what's the new copy?
