### ISSUE TITLE
The documentation link on qiskit.org currently leads to an error

### ISSUE THREAD

**Issue by attp** [Qiskit/qiskit.org#46]
[https://qiskit.org/documentation/](https://qiskit.org/documentation/) leads to a page that says "Sorry, that page doesn't exist!"

**Comment by abdonrd** [comment]
Thanks @attp! Fixed!

**Comment by abdonrd** [comment]
Finally fixed by https://github.com/Qiskit/qiskit.org/commit/178c4336dea7dadae371e741fb18224a05c742cf.
