### ISSUE TITLE
Qiskit tutorials are being moved to the documentation

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#460]
Qiskit tutorials are being moved to the documentation (many already there) so a separate link is not needed, and the title of the docs need not be just API

**Comment by lerongil** [comment]
We will be redirection qiskit.org/tutorials to here: https://qiskit.org/documentation/tutorials/fundamentals/index.html. Thanks for the heads up!

**Comment by y4izus** [comment]
To clarify:
- qiskit.org/tutorials should point to: https://qiskit.org/documentation/tutorials/fundamentals/1_getting_started_with_qiskit.html
- The "API Documentation" link label should be replaced with "Documentation"

Do you agree?

**Comment by lerongil** [comment]
Yes, thank you!
