### ISSUE TITLE
Tutorials link goes to outdated page 

### ISSUE THREAD

**Issue by abbycross** [Qiskit/qiskit.org#462]
### Where is the problem?

qiskit.org page, upper left corner, "Tutorials" link

### What is the problem?

Link goes to a page that isn't being updated anymore

### What would you expect?

[Possibly going to this page instead](https://quantum-computing.ibm.com/docs/qiskit-nb/tutorials)

**Comment by abbycross** [comment]
@nonhermitian make sense to you?

**Comment by lerongil** [comment]
We will most likely be redirecting the tutorials link to here instead: https://qiskit.org/documentation/tutorials/fundamentals/index.html

**Comment by abbycross** [comment]
@lerongil Makes sense.  Shall I close this issue?
