### ISSUE TITLE
Identify consolidation blockers within a 2 week sprint

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#463]
This issue relates to the preparation phase and any blockers that need to solved prior to the consolidation phase.

**Comment by y4izus** [comment]
These issues are related to this task [WIP]:
### Created new
- [Define a consistent structure for the components](https://github.com/Qiskit/qiskit.org/issues/473)

### Already created
- [Unified how we decided between the <nuxt-link> and the <a> link](https://github.com/Qiskit/qiskit.org/issues/405)
- [Review rel attribute values for tag <a>](https://github.com/Qiskit/qiskit.org/issues/377)
- [As dev team we want to update dependencies so we make sure we use the latest version of all our dependencies](https://github.com/Qiskit/qiskit.org/issues/316)
- [As dev team we want to have one only markup for the menu on Qiskit so it's easier to maintain](https://github.com/Qiskit/qiskit.org/issues/312)
- [As dev team we need to refactor breakpoints so we write better SCSS media queries](https://github.com/Qiskit/qiskit.org/issues/310)
- [Find a better CSS methodology for allowing component consumers to customize component's layouts](https://github.com/Qiskit/qiskit.org/issues/271)
- [Default layout CSS is bleeding to other layouts not inheriting from it](https://github.com/Qiskit/qiskit.org/issues/245)

I have also created a label called `type; refactor` to easily find the issues related to this task

**Comment by lerongil** [comment]
As discussed this issue will track blockers needed to move towards consolidation. The above list needs to be reduced to the issues needed to move past the preparation phase.

**Comment by lerongil** [comment]
@y4izus @delapuente Instead of this I created the preparation milesone. Let me know what you think.

**Comment by delapuente** [comment]
Yaiza and I prioritized the most important refactors we estimate they will make a difference for progressing to the next stage. They are all reunited under the [Preparation milestone](https://github.com/Qiskit/qiskit.org/milestone/2). Those tagged as meta require further splitting.
