### ISSUE TITLE
Update news section with kids activity

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#464]
Title (option 1) : Love Crosswords? 
Title (option 2) : Kids meet quantum 

Body: 
This activity will teach your kids about quantum computing through fun activities like crosswords, mazes, word searches and more! Fun for all kids and parents! 

URL:

**Comment by anamita** [comment]
Title: Quantum for kids // Kids meet quantum
Body: This activity pack will entertain your kids with fun activities about quantum computing. Fun for all kids and parents!
[Quantum Activity Pack - Final.pdf](https://github.com/Qiskit/qiskit.org/files/4370583/Quantum.Activity.Pack.-.Final.pdf)


File is attached.

If we want to post this on twitter/share with other, what link will we pass to them? Will that get tracked?
