### ISSUE TITLE
Define a consistent structure for the components

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#473]
Now we are using two ways to organize the components:
- By website sections (advocates, ...)
- By components (cards, ...)

For example, we have the folder 'advocates' with the map component inside, but we have the component `CompactFeature` that is only used in the advocate's pages in a separate folder 'features'
We should discuss which one we prefer and use it throughout all the code. We could also choose both but we need to define when to use one or another in order to have a more consistent and easy to understand code

**Comment by y4izus** [comment]
This is my proposal based on this [post](https://vueschool.io/articles/vuejs-tutorials/structuring-vue-components/):

📂 **components/**
- 📁 **ui/** : Reusable components that are used across the whole app
- 📁 **layout/** : Components used for layouts. They are used in all the pages
- 📁 **[domain]/** : Components that belong to a specific domain. The folder name should be the "domain" it refers to (for example: advocates, education, ...), having one folder per domain

📂 **layouts/**
📂 **pages/**

For `layouts` and `pages` folders, follow [Nuxt documentation](https://nuxtjs.org/guide/views). Make sense for you @delapuente ??

**Comment by delapuente** [comment]
Works for me although definitions are a bit subjective in the post. I like the rule you suggested in our offline conversations about "everything belongs to a domain until you need to use it in a different place, then it becomes a UI element" and we can try to follow it. Would be good to document it somewhere.

I don't like the distinction between UI and layout in the post. I find them very subjective and hard to classify. For instance, does a menu belong to layout or UI? Traditionally, "layout" refers to the way you arrange the items on a medium so I would keep this folder for very abstract components, such as "ColumnLayout" or "GridLayout" or "FlexLayout".

**Comment by y4izus** [comment]
We had the offline conversation when I was still defining the structure. After analyzing everything, I don't think the rule "everything belongs to a domain until you need to use it in a different place, then it becomes a UI element" is a good solution. For me, the structure with more sense is:

📂 **components/**
- 📁 **ui/** : Reusable components that are used across the whole app. The generic components like button, carousel, list, ...
- 📁 **layout/** : Components used for layouts. They are used in all the pages. The components that are used in the `layouts` folder (Header, Footer, ...)
- 📁 **[domain]/** : Components that belong to a specific domain. The folder name should be the "domain" it refers to (for example: advocates, education, ...), having one folder per domain. For example, an AdvocateCard is related to the advocates domain, even if it is used in more than one place. If we have a generic `card` that can be used for both `advocates` and `events` (for example) it should go to ui

I hope this is more clear
