### ISSUE TITLE
Host Qiskit schemas on website

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit.org#48]
A major part of the 0.6 release will be defining and implementing a set of json schema. Can we host the schemas on `qiskit.org/schemas`, so that the backends and anyone else who needs to validate against them has a canonical place to read them from? Each schema has, at the top of it, the address where it will be hosted:
https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/schemas

Some issues:
- The schemas may change in Qiskit-Terra master. Can the website pull the latest one when they change?
- Can we host previous versions as well?

**Comment by ajavadia** [comment]
No. The latest version lives in the qiskit-terra repo under `qiskit/schemas`, and we make pull requests there when we want to change anything. I'm saying the website should grab those and displat them, as they are a defining feature of qiskit.

**Comment by jaygambetta** [comment]
@abdonrd could @ajavadia and I discuss this with you. Maybe slack would be better

**Comment by lerongil** [comment]
@ajavadia Are we still interested in adding this to qiskit.org? What is the benefit of having its own dedicated page over in the documentation? 

I see we have qiskit.org urls in the identifier but they point to a `not found` page.

**Comment by ajavadia** [comment]
This is not just for human readability, but also potentially used by tools to validate against a schema. So yes I would say we need a url to host these.

**Comment by mtreinish** [comment]
@ajavadia this is very easy to do now that we've migrated the site to be hosted on cloud object storage. We can either upload it directly to the buck used to host the website, or add the necessary schema files to the directory we upload in: https://github.com/Qiskit/qiskit.org/blob/master/deploy/deploy_cos.sh
