### ISSUE TITLE
Compare Marina and Human design work

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#486]
Design kickoff session with human to compare and align on work to be done

**Comment by JRussellHuffman** [comment]
Did a first pass at this effort by taking Marina's work and applying the brand and components from the Human efforts.

Attached are screenshots of the light and dark versions of that.
![1056px-Breakpoint-16 column-1](https://user-images.githubusercontent.com/7633881/82609060-68d38300-9b81-11ea-892c-1b466012b0ad.png)
![1056px-Breakpoint-16 column](https://user-images.githubusercontent.com/7633881/82609066-6c670a00-9b81-11ea-81e7-1223d94bd59d.png)

**Comment by lerongil** [comment]
This can be closed off it seems. Is that right @JRussellHuffman
