### ISSUE TITLE
Code not visible on home page of Aqua and Chemistry when using Firefox

### ISSUE THREAD

**Issue by pistoia** [Qiskit/qiskit.org#49]
Several users have reported (and I have confirmed it too) that on Firefox on macOS 10 the two code snippets that should be embedded in the Aqua home page (https://qiskit.org/aqua) do not show up:
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/11150011/45772862-d09c3280-bc16-11e8-90f1-1ef089ea23b3.png">
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/11150011/45772885-e27dd580-bc16-11e8-9feb-ee4abcc0e753.png">
Both code snippets are displayed correctly on Safari on macOS 10.

**Comment by abdonrd** [comment]
Fixed by https://github.com/Qiskit/qiskit.org/commit/a6dd5b9ffc92559f8e08ea6a25da51a6f2e1bfde! ⚡️

**Comment by pistoia** [comment]
Thank you, @abdonrd, for taking care of this issue so promptly.
