### ISSUE TITLE
Update Aqua element for upcoming release

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#490]
- [x] 1. Update new section with release copy + blog link

- [x] 2. Translators -> Applications, Core algorithms -> Aqua core algorithms & link 

- [x] 3. AI -> ML

- [x] 4. Add optimization section to mimic the about and example portion 

Due Date: 4/29/20

**Comment by lerongil** [comment]
Here is the copy and placement for 1. 
<img width="1645" alt="Screen Shot 2020-04-07 at 12 53 00 PM" src="https://user-images.githubusercontent.com/9096989/78713287-e2aff580-78ce-11ea-94fe-b230e122d14d.png">

@stefan-woerner - please thumbs up if you approve of this copy or suggest an update.

**Comment by lerongil** [comment]
Here is the copy and placement for 2. and 3. 
<img width="1644" alt="Screen Shot 2020-04-07 at 1 15 58 PM" src="https://user-images.githubusercontent.com/9096989/78715278-088ac980-78d2-11ea-9b60-5e9b137ccf6d.png">

**Comment by lerongil** [comment]
For 4. 

We should duplicate the section above with an about and example. 

The "About" portion should say: 
Qiskit Optimization enables easy and efficient modeling of optimization problems by using established high-level modeling languages, such as docplex. Qiskit Optimization covers the whole stack from high-level modeling of optimization problems, from automatic conversion of problems to different required representations, to a suite of easy-to-use quantum optimization algorithms that are ready to run on classical simulators, as well as on real quantum devices via Qiskit.

Example:  TBD

For this section please use the same background color as the first with Aqua: #dbfbfb

**Comment by delapuente** [comment]
On hold because we are still waiting for the links and should decide about [kids' activities](https://github.com/Qiskit/qiskit.org/pull/513#pullrequestreview-391970274).

**Comment by lerongil** [comment]
Just got word of the release being pushed back to April 29. Updating original issue.

**Comment by lerongil** [comment]
This is now pushed to April 30 @delapuente

**Comment by lerongil** [comment]
This will continue to be on hold.

**Comment by lerongil** [comment]
No longer required.
