### ISSUE TITLE
Implement placeholder for no events.

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#496]
Now, when we filter in the events page and there are no results, nothing is shown:

<img width="1012" alt="Screen Shot 2020-04-08 at 16 14 51" src="https://user-images.githubusercontent.com/17231966/78794471-16188000-79b4-11ea-81f2-d9e10fd6afbe.png">

We should have this message instead:
**Plan an event in your area today! (Insert CTA)**

There is another [issue to implement the CTA](https://github.com/Qiskit/qiskit.org/issues/507) because we are waiting for some info. Meanwhile, we can advance work just implementing the placeholder text

**Comment by delapuente** [comment]
Closed by #514
