### ISSUE TITLE
Update community pages with carbon design

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#502]
Advocates and Events should all be one consistent design

**Comment by JRussellHuffman** [comment]
The main event page, and the individual events page are underway. The advocates page has not been started yet.

**Comment by JRussellHuffman** [comment]
Scoped the advocates page:

**problem we are solving:**
- recruiting community representatives to the program
- helping users connect with community representatives

**For what user:**
- qiskit experts (Xavier & Quinn)
- the quantum curious (Clyde)

**Page requirements:**
- value of the program to both users
- link to applications
- showcase and index members
  - who they are
  - their value to the community
  - where they are
  - how to contact
  - consider a list or map


**What success looks like:**
- increase number of applicants
- conversion from this page to the application form
- connecting individuals to community represenatives
- community grows

**Comment by JRussellHuffman** [comment]
Event pages and advocate pages are done, including light and dark themes and all break points.
The pages are included in the master figma file.

closing.
