### ISSUE TITLE
Update type categories for events

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#509]
The type categories for the events should be:

- Hackathon
- Camp
- Unconference
- Conference? (TBD)
- Convention? (TBD)
- Meetup? (TBD) 
- Virtual? (TBD)

Also, refactor type categories following the structure defined [here](https://github.com/Qiskit/qiskit.org/blob/ae0f03191da8a7415a321443f9c1c4724005da6f/constants/filters.ts) for location categories

**Comment by delapuente** [comment]
Closed by #521
