### ISSUE TITLE
Make `Online` a "Type of Event" instead of a "Region"

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#526]
Per offline conversations, we agreed on moving `Online` value under the "Type of Event" column. Current implementation automatically convert this special _region_ into an _event type_ and would be ideal if the product decision is observed in the Airtable too.

**Comment by delapuente** [comment]
As per comment in #437, we leave this for MVP 2.0.

**Comment by lerongil** [comment]
Per offline discussion we agreed to move online to type in the airtable

**Comment by y4izus** [comment]
[We already have `online` under `Type of event` ](https://qiskit.org/events/). I close this issue
