### ISSUE TITLE
How to navigate from qiskit.org/documentation back to qiskit.org?

### ISSUE THREAD

**Issue by abbycross** [Qiskit/qiskit.org#569]
### Steps to reproduce the problem

Apologies if this isn't the right repo for this issue -- please point me in the right direction if so :) There appears to be no way to navigate back to qiskit.org from the qiskit.org/documentation page.   

The home icon in the upper left would suggest that you can return "home" to qiskit.org, but it only brings you back to the documentation home page.  

Likewise, clicking on the qiskit icon in the upper left does the same thing.

**Comment by lerongil** [comment]
This is the right repo. It's an issue with the docs theme. Thanks for opening it up, we will take a look at addressing this.

**Comment by aditya-giri** [comment]
I can pick this up and look into it ...

**Comment by y4izus** [comment]
This is fixed, I close the issue
