### ISSUE TITLE
Tutorials link in top nav 404s

### ISSUE THREAD

**Issue by derivation** [Qiskit/qiskit.org#570]
### Steps to reproduce the problem
Click the **Tutorials** link in the top nav.

### What is the current behavior?
Returns "Page not found".

### What is the expected behavior?
Direct to tutorials.

**Comment by lerongil** [comment]
Thanks @derivation. This is being tracked here: https://github.com/Qiskit/qiskit-tutorials/issues/891

In the mean time we will link to this: https://quantum-computing.ibm.com/jupyter/tutorial/1_start_here.ipynb

**Comment by lerongil** [comment]
Will open a new one once the tutorials are back in docs.
