### ISSUE TITLE
Design Overview page

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#578]
This issue references the overview page that will replace the individual elements landing page. This will include some details around (to be finalized): 

Elements, additional features, element hierarchy and interactions, benchmarking

**Comment by JRussellHuffman** [comment]
This work is being tracked in figma here: https://www.figma.com/file/wwCBYK31rPz0QXcwJo4yfY/Qiskit-Wireframes?node-id=537%3A6 on the page titled "FINAL".
