### ISSUE TITLE
Incorporate Virtual Event Guide onto website pages 

### ISSUE THREAD

**Issue by justjosie** [Qiskit/qiskit.org#593]
Add a link to the qiskit website in two locations: 
1. qiskit.org/education
2. qiskit.org/events

That provides a direct link to the recently created Virtual Event Planning Guide assembled by the events team. Links are below. 

Github Repo: https://github.com/justjosie/Virtual-Event-Guide/blob/master/index.md

Site page: https://pages.github.ibm.com/Josie-Kies/virtual-event-guide/

The goal of this guide is to provide a resource to the community as we collectively shift to virtual events, and support initial planning efforts and information about how to plan a Qiskit event themselves.

**Comment by lerongil** [comment]
Thanks for the submission. I think we should choose a single page to list this and if it is as you mentioned a high priority item then maybe I can recommend we replace the kids activity portion located here: qiskit.org with this new submission. Does that work for you?

**Comment by lerongil** [comment]
Per offline discussion this will be replaced with qiskit.org kids meet quantum

**Comment by lerongil** [comment]
Copy: 

Element Header: Virtual Event Guide!

Element paragraph: Host your own virtual event using this guide currated by the community! Use everything from hackathon projects to sample agendas to make your next event awesome.

Try it

**Comment by delapuente** [comment]
I think the CTA should link to the virtual guide but it is behind a login wall. I'm using `qiskit-community` to publish a public copy.
