### ISSUE TITLE
Virtual Hackathon Dedicated Event Landing Page

### ISSUE THREAD

**Issue by justjosie** [Qiskit/qiskit.org#594]
Target Date: May 21
Template/Layout: qiskit.camp

Event Details to be provided - target date May 16 - to finalize the site. Basic content and layout will remain the same as Qiskit Camps, new copy to be provided by that target date.

**Comment by lerongil** [comment]
Thanks. We will add this to the next sprint. Let me know if anything changes with the target date.

**Comment by lerongil** [comment]
@justjosie May 21 is now in the past, is this issue still needed?

**Comment by lerongil** [comment]
New date: June 20 (not final)
