### ISSUE TITLE
Adjust breakpoints to em CSS units

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#600]
Carbon guidelines [specify breakpoints in pixels](https://www.carbondesignsystem.com/guidelines/2x-grid/basics#breakpoints). However, [accessibility recommendations](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Accessibility_concerns) advise using `em`s instead for making the media queries adapt to user changes in the font size.

**Comment by y4izus** [comment]
In Carbon Guidelines, they specify the breakpoints in pixels and in rem. Look the second column:

<img width="307" alt="Screen Shot 2020-05-13 at 09 47 10" src="https://user-images.githubusercontent.com/17231966/81785695-e0a90a00-94fe-11ea-851d-4a93f7dbe322.png">

One interesting detail about `rem` and `em` units when used as units for media queries: they always keep the same value of 1rem = 1em = browser-set font size. The reason for this behavior is explained in the [media query spec](https://drafts.csswg.org/mediaqueries/#units) (emphasis added). So, we can use the given `rem` value from Carbon guidelines as `em` value for media queries

**Comment by delapuente** [comment]
Based on this, let's make it happen in the PR.
