### ISSUE TITLE
Design Learn page as textbook landing page

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#604]
This is in reference to the new learn page as apart of qiskit.org which in the beginning will serve as the textbook landing page.

**Comment by lerongil** [comment]
This might be slightly updated. The new date for this page is July 1.

**Comment by delapuente** [comment]
Would be worth creating a milestone for each important date so we can see at a glance what tasks are closer to deadlines and prioritize accordingly.

**Comment by JRussellHuffman** [comment]
Adding the designs for the page from this sprint.

Problem statement:
A site visitor wants to get started with learning quantum computing in a way that appropriate to their needs. 

The MVP version of solving the above problem statement is to present the learning content Qiskit has available with 2 dimensions of filter: time, and domain familiarity.

Default state
![Default state](https://user-images.githubusercontent.com/7633881/85885709-67156480-b7aa-11ea-8772-f392d019fc07.png)

Representative filter screen:
![one day beginner](https://user-images.githubusercontent.com/7633881/85885759-7c8a8e80-b7aa-11ea-8cf1-f7ffdb029794.png)

loading state:
![loading state](https://user-images.githubusercontent.com/7633881/85885775-84e2c980-b7aa-11ea-9e51-3a5998825a92.png)
