### ISSUE TITLE
Illustration work with new textbook illustrations

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#605]
This is in reference to the ongoing illustration work but with a more purposeful design using the textbook requirements as a guide for what should be illustrated.

**Comment by JRussellHuffman** [comment]
These are the 5 specifically requested illustrations that are currently in the textbook
![tele1](https://user-images.githubusercontent.com/7633881/82235150-f8fe9780-98f7-11ea-9358-004f9e1d4f44.png)
![car_track_1](https://user-images.githubusercontent.com/7633881/82235141-f69c3d80-98f7-11ea-9799-b2cdce159323.png)
![car_track_2](https://user-images.githubusercontent.com/7633881/82235143-f734d400-98f7-11ea-8345-cea5ec94e026.png)
![qpe_intuition](https://user-images.githubusercontent.com/7633881/82235144-f734d400-98f7-11ea-9c5c-fcb4a2a70e6b.png)
![superdense](https://user-images.githubusercontent.com/7633881/82235146-f7cd6a80-98f7-11ea-8ad9-eb839d5f0e39.png)

**Comment by JRussellHuffman** [comment]
Links to the above images in the textbook: 

https://qiskit.org/textbook/ch-states/representing-qubit-states.html
https://qiskit.org/textbook/ch-algorithms/teleportation.html
https://qiskit.org/textbook/ch-algorithms/superdense-coding.html
https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html

**Comment by lerongil** [comment]
Also include PPT art in curriculum diagram: https://qiskit.org/textbook/preface.html
<img width="813" alt="Screen Shot 2020-06-02 at 9 32 27 AM" src="https://user-images.githubusercontent.com/9096989/83545418-0731e380-a4b4-11ea-9c08-863765b66ea2.png">

**Comment by lerongil** [comment]
Target date: June 19

**Comment by JRussellHuffman** [comment]
First pass at the 5 above illustrations.
![car 01](https://user-images.githubusercontent.com/7633881/85627248-d87ed700-b633-11ea-8b8d-32880084b2ba.jpg)
![car 02](https://user-images.githubusercontent.com/7633881/85627253-d9b00400-b633-11ea-8e71-dca8d44f67a2.jpg)
![encode qubit](https://user-images.githubusercontent.com/7633881/85627258-da489a80-b633-11ea-8f6a-73cebe794d3f.jpg)
![fourier](https://user-images.githubusercontent.com/7633881/85627261-dae13100-b633-11ea-88e4-03ee3011e29b.jpg)
![teleportation](https://user-images.githubusercontent.com/7633881/85627262-db79c780-b633-11ea-93ce-c36419fee445.jpg)

**Comment by frankharkins** [comment]
Do I have permission to incorporate these into the textbook immediately (barring the teleportation image)?

**Comment by JRussellHuffman** [comment]
Yes, they are good to go on my side. Also including updated teleportation image, which is cross referenced here: https://github.com/qiskit-community/qiskit-textbook/issues/400

![teleportation v2](https://user-images.githubusercontent.com/7633881/85886367-911b5680-b7ab-11ea-96f4-f47012f3aca3.jpg)

**Comment by JRussellHuffman** [comment]
Let me know if you need any other file types or sizes
