### ISSUE TITLE
The hero moment in the new landing page seems off

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#631]
Perhaps caused by the picture "falling outside" the content box. It's worth trying rebalancing this feeling.

**Comment by lerongil** [comment]
The padding on each side is not even, it might be ok that it is cut off.

**Comment by JRussellHuffman** [comment]
Took a stab at re-balancing the hero graphic to be inside the content area. Attaching the large and medium breakpoints. The graphic is a little smaller and not cropped. I think it works better. Thoughts?

![Main Page-672px-Breakpoint-8 column](https://user-images.githubusercontent.com/7633881/84702731-b9d65d00-af1c-11ea-8fd8-89876b3410de.png)
![Main Page-1056px-Breakpoint-16 column](https://user-images.githubusercontent.com/7633881/84702743-bcd14d80-af1c-11ea-8423-a6ab100f168a.png)

**Comment by JRussellHuffman** [comment]
Note that the updated and finalized image is slightly different. It can be found here: https://ibm.box.com/s/o0h87egixlg28u4qb2g9aj0ejl5bnh3z

**Comment by JRussellHuffman** [comment]
Design aspect of this issue is done. Removing label and unassigned.
