### ISSUE TITLE
Persona Illustrations

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#632]
### Where is the problem?
Details to come.

**Comment by delapuente** [comment]
@JRussellHuffman is this issue still active? If so, can you provide more context, please? Feel free to close if it no longer applies.

**Comment by JRussellHuffman** [comment]
To add some context, this was a design request that came through, but details were never given. I think its the right call to keep the issue closed. will open a new issue if this comes back up.
