### ISSUE TITLE
Extend past events in events index to show beyond 1 month 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#634]
In the current events index we show 30 days in the future and 30 days in the past, this issue is proposing to extend the 30 days in the past as to keep big event pages (qiskit camps) connected to qiskit.org

**Comment by y4izus** [comment]
The `type:enhancement` label is going to [disappear](https://github.com/Qiskit/qiskit.org/issues/1041) . This enhancement is not related to the code quality but with a new feature, that's why I added the `type: feature request` label

**Comment by pandasa123** [comment]
(This seems to be resolved, the current events have the past 60 days)
