### ISSUE TITLE
Modify the contained mixin not to modify the padding of the element

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#657]
Current `contained` mixin modifies the internal geometry of the component for automatically aligning the start of the content with the grid. However, it also violates the principle of minimum astonishment: the mixin should not modify the padding or it should be more clear in its intention. We should review this behaviour and come up with a better solution.

**Comment by delapuente** [comment]
No one has complaint ever since we open it. Maybe it was less astonishing than I thought.

**Comment by y4izus** [comment]
@delapuente , I just wanted to add that the `contained` mixing is going to disappear due to the max-screen size design
