### ISSUE TITLE
Illustration for Qiskit Blog Feature Story 6/21/2020 - How Do I Build a Quantum Computer in My House? 

### ISSUE THREAD

**Issue by anamita** [Qiskit/qiskit.org#671]
TASK: Design lead image of this blog post to be an illustration showing a person (gender/ethnically ambiguous if possible) crafting a quantum computer in their garage. The computer should have components that make it clear that it’s a DIY tech project—a 3D printer or optical components, for example.

The image should be in a 16x9 dimension and will live atop the blog and appear in social tiles.

DATE/GO-LIVE: 6/21
Will be published 10am EST 6/22.

**Comment by lerongil** [comment]
Blog and image are here: https://medium.com/qiskit/how-do-i-build-a-quantum-computer-in-my-house-1c7e9dc0c242
