### ISSUE TITLE
Update "Qiskit on Youtube" block copy on front page of qiskit.org

### ISSUE THREAD

**Issue by anamita** [Qiskit/qiskit.org#673]
Want to learn how to code a quantum computer? Interested in learning more from quantum researchers and developers? Subscribe to the Qiskit YouTube channel, where we release new videos weekly.

[WATCH NOW!] > https://www.youtube.com/channel/UClBNq7mCMf5xm8baE_VMl3A

QUESTION: is the button already tagged? should we give you a tracked url instead?

**Comment by lerongil** [comment]
Do you have an updated URL you would like to use?

**Comment by anamita** [comment]
Nope, since the button is tracked, the url provided above is the one we want to use! Thanks!
