### ISSUE TITLE
Styles of the hero moment description

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#686]
### Steps to reproduce the problem
Go to new redesign home page

### What is the current behavior?
<img width="382" alt="Screen Shot 2020-06-23 at 11 53 03" src="https://user-images.githubusercontent.com/17231966/85389728-1acaea00-b548-11ea-86e3-8d7e3fff924d.png">

### What is the expected behavior?
- Color text should be $gray-60
- Block description width should be a little bit smaller

<img width="343" alt="Screen Shot 2020-06-23 at 11 53 19" src="https://user-images.githubusercontent.com/17231966/85389758-23bbbb80-b548-11ea-9d45-b3fccd69c9b8.png">

**Comment by delapuente** [comment]
Closed by #689
