### ISSUE TITLE
Styles of the "what qiskit can do" description

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#687]
### Steps to reproduce the problem
Go to new redesign home page

### What is the current behavior?
<img width="387" alt="Screen Shot 2020-06-23 at 12 00 05" src="https://user-images.githubusercontent.com/17231966/85390403-15ba6a80-b549-11ea-8b6e-1d28f4ebab6b.png">

### What is the expected behavior?
- Color text should be $gray-60
- Block description width should be a little bit bigger

<img width="436" alt="Screen Shot 2020-06-23 at 12 00 25" src="https://user-images.githubusercontent.com/17231966/85390447-210d9600-b549-11ea-9877-86613cd84674.png">

**Comment by delapuente** [comment]
Closed by #688
