### ISSUE TITLE
Apply a different theme from the general one to an specific component

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#703]
Per early decisions, we started customizing a Carbon dark theme. Now we are using a light one and we need the components sometimes with the dark look & feel/ sometimes with the light one. Research if this is possible with the [@carbon/themes](https://github.com/carbon-design-system/carbon/tree/master/packages/themes) package or figure out an alternative.

**Comment by y4izus** [comment]
I think this is done with #965. @delapuente do you agree? Could we close this one?

**Comment by delapuente** [comment]
Let's close it the.
