### ISSUE TITLE
dead link on summer school page

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit.org#723]
### Where is the problem?
summer school [page](https://github.com/Qiskit/qiskit.org/blob/master/content/events/summer-school.md)

### What is the problem?
second link on line 27 is dead: https://github.com/Qiskit/qiskit.org/blob/master/content/events/summer-school.md#L27

### What would you expect?
link somewhere

**Comment by lerongil** [comment]
@aasfaw or @KallieFerguson Do either of you want to take a look at this?
