### ISSUE TITLE
Update qiskit advocate page

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#726]
- [x] update steps to become an advocate 
- [x] update cta with clickable button and link to: 
- [ ] add advocate 

Due: July 15

**Comment by delapuente** [comment]
@lerongil, see the preview at: https://qiskitorg-git-fork-delapuente-issue-726-update-qisk-f12342.qiskit.now.sh/advocates
And by the way, what is the "add advocate" check?
