### ISSUE TITLE
Mobile images 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#759]
Circuits, Hardware access and algorithm images on mobile either do not scale properly or disappear

**Comment by y4izus** [comment]
@lerongil , could you add more information? This is the Figma design:
<img width="290" alt="Screen Shot 2020-07-21 at 10 07 32" src="https://user-images.githubusercontent.com/17231966/88029230-00c9fa80-cb3a-11ea-9194-493b4e354199.png">

And this is the implemented mobile version:
<img width="298" alt="Screen Shot 2020-07-21 at 10 08 16" src="https://user-images.githubusercontent.com/17231966/88029282-1a6b4200-cb3a-11ea-95a1-eb27f3dcef1e.png">

So:
- Following Figma design, circuits images shouldn't be shown
- Hardware image scales properly but doesn't show the same quantum computer part, you mean that?
- It's true, it doesn't scale the same way, we will fix it

**Comment by y4izus** [comment]
- [ ] Circuits image -> Waiting for response
- [ ] Hardware image -> Waiting for response
- [ ] Algorithms image

**Comment by lerongil** [comment]
Let's open up a new issue. The implementation for the circuits and hardware image is correct. Thank you for fixing the Algorithms image.

**Comment by JRussellHuffman** [comment]
Opened up 783 and adding comments there.
