### ISSUE TITLE
Pull chemisty out of aqua

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#77]
Can we make it so that the chemistry is a tab at the top.

Think of it as  Qiskit | elements | components | tutorial | documentation | tools | fun. 

The elements are terra, aer, aqua, ignis. I would make this a pull down
The components are chemistry, providers, (more to come).

The tools are (vscode, gui)
So in the tools i think we need submenus for vscode, chemistry gui, ...

**Comment by lerongil** [comment]
I like this format. Would each tab be a drop down? e.g. elements would expand when clicked and show all the elements underneath? 

I would also add Community at the top which could include fun, (possibly) tools, roadmap, community . projects, events and more. 

So,  Qiskit | elements | components | tutorials | documentation | community.

**Comment by jaygambetta** [comment]
I think each should be a pull-down like you say or like https://pytorch.org/resources.

**Comment by lerongil** [comment]
ok, I will work with @carlosazaustre to get something similar to this structure up.

**Comment by jaygambetta** [comment]
sounds great. I think you should close this issue and divide it up into ones that make sense. Its kinda turned into a discussion on multiple things.

**Comment by lerongil** [comment]
Closing issue, will create new set with some of these topics.
