### ISSUE TITLE
Populate overview page design with content

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#784]
Part of #727

**Comment by JRussellHuffman** [comment]
figma file here: https://www.figma.com/file/5pRmV74VaYV9aqHNTDfWxG/784-overview-page-content?node-id=0%3A1

**Comment by JRussellHuffman** [comment]
Prototype here: https://www.figma.com/proto/PDbN8wcg5WteWVvinjAEUv/qiskit.org-master-file?node-id=993%3A633&viewport=927%2C715%2C0.3848015069961548&scaling=min-zoom

**Comment by JRussellHuffman** [comment]
Still need images for VQE, QAOA, and Calibration. Otherwise everything is in place.

**Comment by JRussellHuffman** [comment]
Everything is done expect for the last few images, which we are waiting for input from the experts. Closing this issue and created a new issue for those last images here: https://github.com/Qiskit/qiskit.org/issues/824
