### ISSUE TITLE
Add grid decorations to the overview page

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#787]
**Description**

Currently, the Overview page includes the grid background in its hero section at the top of the page. The delivered [design for the Overview page](https://www.figma.com/file/PDbN8wcg5WteWVvinjAEUv/qiskit.org-master--file?node-id=1%3A6169) calls for the dissolving grid decorations to be used in various parts of the page.

**Acceptance criteria**

Add dissolving grid decorations to the following sections
- [ ] between Research Applications and Collection of Algorithms
- [ ] between Experimentalist Toolbox and Circuits
- [ ] between Circuits and Simulate Quantum Hardware
- [ ] below Run Circuits on Real Quantum Systems

**Notes**
This PR should be made to the `feature/overview-page` branch

**Comment by techtolentino** [comment]
Unassigning myself until this becomes actionable again

**Comment by delapuente** [comment]
So far, this has not been a problem. Closing.
