### ISSUE TITLE
Quick start instructions can be simplified.

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit.org#803]
### Steps to reproduce the problem

Use the 'quick start' guide on qiskit.org and toggle between Linux / OSX / Windows

### What is the current behavior?

- The command for Linux and "stable" is: `pip install -U pip pip install qiskit`.
- The commands for Linux, OSX and Windows are identical, except for selecting Linux and "Stable"

### What is the expected behavior?

- I believe `pip install -U pip pip install qiskit` should be split over two lines. 
- I also believe that:
```
pip install -U pip
pip install qiskit
```
should apply to all systems. If this is correct then the commands for all systems are then identical and I believe the buttons could be removed.

**Comment by delapuente** [comment]
It must be two different lines, you're right.

Regarding the different paths, sure doing `pip install -U pip` is a good practice but it is almost mandatory for Aer (if you want the Linux binaries), thus the difference. Not a hard pusher on this, though. @lerongil, thouhgts?

**Comment by frankharkins** [comment]
Just realised the instructions for installing the compilers / headers are different for each system but this is not obvous unless you expand the accordian. I think my main reservation was that it feels a bit weird as a user to have three buttons with (apparently) almost identical instructions.

Also not a hard pusher, this is both minor and subjective.

**Comment by lerongil** [comment]
As mentioned the buttons are there for installing the correct compilers / headers. Will look at simplifying in a few iterations down the road. Not a huge priority at the moment.
