### ISSUE TITLE
Implement typewritting effect on RelevantWord component

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#804]
Following comment at https://github.com/Qiskit/qiskit.org/pull/802#discussion_r463436947, this task is about to rename the component and encapsulate a typewritting effect:

![Typewriter effect](https://reactjsexample.com/content/images/2019/03/react-rotating-text.gif)

**Comment by y4izus** [comment]
Read #904 before starting

**Comment by lerongil** [comment]
**Learn:** 
Qiskit 
Python
Quantum Computing
Error Mitigation
Quantum Hardware 
Quantum Algorithms
Quantum Applications

**Overview:**
feature rich 
modular 
open
popular
