### ISSUE TITLE
Add website citation

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#805]
Can we make citation information available on the qiskit.org site? 

example citation information: https://github.com/Qiskit/qiskit/blob/master/Qiskit.bib

**Comment by JRussellHuffman** [comment]
related to https://github.com/Qiskit/qiskit.org/issues/285

**Comment by lerongil** [comment]
This might be the right place for it: https://qiskit.org/documentation/faq.html

**Comment by y4izus** [comment]
The `type:enhancement` label is going to [disappear](https://github.com/Qiskit/qiskit.org/issues/1041) . This enhancement is not related to the code quality but with a new feature, that's why I added the `type: feature request` label
