### ISSUE TITLE
Redraw images for textbook

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit.org#809]
Could the following images please be redrawn in the style of the textbook?

**Images from Grover's Algorithm Chapter (some of these are from Yuri):**
(Please omit the blue text from this image)
![step0](https://user-images.githubusercontent.com/36071638/89307454-feeb5580-d668-11ea-99e8-fa43c1f0594b.png)
![step1](https://user-images.githubusercontent.com/36071638/89307460-00b51900-d669-11ea-8961-ace9f42bdf63.png)
![step2](https://user-images.githubusercontent.com/36071638/89307464-014daf80-d669-11ea-8d6a-98c44450cd39.png)
<img width="448" alt="grover_algorithm" src="https://user-images.githubusercontent.com/36071638/91421495-e7f5e880-e84d-11ea-8a23-5bdb17628f90.png">
![grover_search](https://user-images.githubusercontent.com/36071638/89307530-1a566080-d669-11ea-8c21-bbd0f7b90fe9.png)

**From other miscellaneous chapters:**
Context for images below: [atoms of computation](https://qiskit.org/textbook/ch-states/atoms-computation.html)
<img width="998" alt="04498f84a69d4e859afd19b2760ced24atoms6" src="https://user-images.githubusercontent.com/36071638/89310003-10822c80-d66c-11ea-839e-303a4553a774.png">
<img width="538" alt="classical_circuit" src="https://user-images.githubusercontent.com/36071638/89310054-1d9f1b80-d66c-11ea-95bf-7de83ef65890.png">

Context for images below: [defining quantum circuits](https://qiskit.org/textbook/ch-algorithms/defining-quantum-circuits.html#3.-Example:-Quantum-Teleportation-)
![teleportation-labeled](https://user-images.githubusercontent.com/36071638/89310079-22fc6600-d66c-11ea-95fc-c0e74f3608a0.png)
![vqe-labeled](https://user-images.githubusercontent.com/36071638/89310081-242d9300-d66c-11ea-9ecd-682c825b8096.png)

Context for image below: [chapter 1 introduction](https://qiskit.org/textbook/ch-states/introduction.html)
<img width="602" alt="b37a8ea62054452f83a2c051e7de12efatoms10" src="https://user-images.githubusercontent.com/36071638/89310134-360f3600-d66c-11ea-8928-14f0ca3e6e51.png">

**Comment by JRussellHuffman** [comment]
Updated images so far:
![Grover_Amplitude_1](https://user-images.githubusercontent.com/7633881/92011871-4f5ddd80-ed11-11ea-8621-7bfc779c9ce8.jpg)
![Grover_Amplitude_2](https://user-images.githubusercontent.com/7633881/92011881-52f16480-ed11-11ea-9560-eb179a0d85e8.jpg)
![Grover_Amplitude_3_v2](https://user-images.githubusercontent.com/7633881/92011884-5389fb00-ed11-11ea-8f14-3769002a2013.jpg)
![grover circuit](https://user-images.githubusercontent.com/7633881/92011907-5b499f80-ed11-11ea-8dd8-b5a70b1226c6.png)
![List](https://user-images.githubusercontent.com/7633881/92011924-60a6ea00-ed11-11ea-90ab-004812187bac.png)
![Algo_Goes_Here](https://user-images.githubusercontent.com/7633881/92011963-6d2b4280-ed11-11ea-8d62-4d9a2f5beab5.png)
![Logic_Gates](https://user-images.githubusercontent.com/7633881/92011972-71eff680-ed11-11ea-8a76-b933b79df175.png)

**Comment by JRussellHuffman** [comment]
Last image.

![gate groups](https://user-images.githubusercontent.com/7633881/93127131-f5ef9a00-f692-11ea-9653-8bd35dcaf9ea.png)

**Comment by JRussellHuffman** [comment]
All drawings are complete. Closing this issue
