### ISSUE TITLE
Fix punctuation, hyphenation, and text inconsistencies on the qiskit.org homepage

### ISSUE THREAD

**Issue by RafeyIqbalRahman** [Qiskit/qiskit.org#818]
### Where is the problem?
The problem is in the content of the qiskit.org homepage.

### What is the problem?
The following pieces of text have issues:

- "Qiskit [kiss-kit] is an **open source** SDK for working with quantum computers at the level of pulses, circuits **and** algorithms."

- "Research and prototype machine learning, optimization **and** chemistry applications by building upon a library of quantum algorithms."

- "When you are looking to start with Qiskit **you** have two options. You can get started locally and use your favorite development environment, or you can get started online with **IBM’s hosted** Jupyter Notebooks."

- "To install Qiskit locally, you will need Python 3.5+. Although it **isn't** required, we recommend using a virtual environment with Anaconda."

- "**IBM's hosted** Jupyter Notebooks let you get started without installing anything."

### What would you expect?

Instead, the above sentences should be:

**Hyphenation and Punctuation**

- "Qiskit [kiss-kit] is an open-source SDK for working with quantum computers at the level of pulses, circuits, and algorithms."

**Punctuation and Text Made Consistent**

- Research and prototype machine learning, optimization, and chemistry applications by building upon a library of quantum algorithms.

**Punctuation**

- "When you are looking to start with Qiskit, you have two options. You can get started locally and use your favorite development environment, or you can get started online with Jupyter Notebooks hosted by IBM."

**Inconsistent Text**

- "To install Qiskit locally, you will need Python 3.5+. Although it is not required, we recommend using a virtual environment with Anaconda."

- "Jupyter Notebooks hosted by IBM let you get started without installing anything."

_All of the above-expected pieces of text have been tested using Grammarly (Screenshots and Report attached)._

![issue](https://user-images.githubusercontent.com/59226057/89705171-74f70180-d974-11ea-83b4-5120f5ca8431.PNG)

![perf](https://user-images.githubusercontent.com/59226057/89705184-9fe15580-d974-11ea-8614-e6257e6eed11.PNG)

[report.pdf](https://github.com/Qiskit/qiskit.org/files/5044820/report.pdf)

**Comment by shil-m** [comment]
Is this already taken care of? If not, can I work on it @RafeyIqbalRahman

**Comment by y4izus** [comment]
You can work on it @shil-m !! thank you very much!
