### ISSUE TITLE
Add decoration issues for upcoming sprint 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#819]
Currently we have 2 issues for the decoration sprint, let's add a few more this sprint in preparation for upcoming the upcoming sprint.

**Comment by delapuente** [comment]
Let's book some time to brainstorm about this this week, after welcoming Randy to the team.

**Comment by delapuente** [comment]
Let's add a 👍 if we think the issue adds value and a 🎉 if we would like to work on it. Taking the idea from @lerongil, let's also use up to 3 ❤️ each of us for marking the issues we **absolutely love**.
