### ISSUE TITLE
👍👍👍👍 Consider global registration of the base components

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#820]
There is a set of components (like `AppLink` or `AppCta`) so widely used that it would be convenient to register them globally instead of importing each time. A good indicator of when a component should be registered globally is that it's a [base component](https://vuejs.org/v2/guide/components-registration.html#Automatic-Global-Registration-of-Base-Components). Our base components are prefixed by `App`.

**Comment by delapuente** [comment]
This includes finding the `App*` components automatically so it can be a bit more elaborated than expected.

**Comment by korgan00** [comment]
Per offline conversations, consider https://github.com/nuxt/components.

**Comment by korgan00** [comment]
Ok, I will sum up the most interesting features for me.

- **[Dynamic Imports/Lazy Load](https://github.com/nuxt/components#dynamic-imports)**: Lazy load any component. I don't know the tech details about this.
- **[Directory based features](https://github.com/nuxt/components#directories)**: Can be configurated in the nuxt.config. 
  - We can choose a list of files/directories to include ([path](https://github.com/nuxt/components#path), [file extensions](https://github.com/nuxt/components#extensions), [pattern](https://github.com/nuxt/components#pattern)).
  - [Ignore](https://github.com/nuxt/components#ignore) some files in the specified path.
  - Establish a [prefix](https://github.com/nuxt/components#prefix) to the components in a specific path. For example: `components/app/button.vue` could be prefixed with `app` to be instanced with `<AppButton>`.
- A new [hook](https://github.com/nuxt/components#library-authors) for creating/importing component libraries.
