### ISSUE TITLE
[General UI] The smooth scroll is not working properly

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#821]
### Steps to reproduce the problem
Go to https://qiskitorg-git-feature-overview-page.qiskit.vercel.app/overview and click on one of the link on the sidebar

### What is the current behavior?
The page directly moves to the section

### What is the expected behavior?
This movement should be smooth

**Comment by delapuente** [comment]
Adding `type: bug`. It can be considered as decoration but if it should be behaving in a different way and it is not doing so, then it is a bug. We can decide not to fix or give it a low priority though.

**Comment by korgan00** [comment]
Debugging on chrome, the function `scrollToPosition` from `vue-router.esm.js` is overwriting the behavior of the `window.scrollTo()`.
In the last version of `vue-router`, that behavior is fixed. [vue-router.esm.js line 1859](https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.esm.js).
Once it is updated, the `resolve` function on our `router.scrollBehavior.js` should be called with an object as a parameter, as shown [here](https://router.vuejs.org/guide/advanced/scroll-behavior.html#async-scrolling).

**Comment by pandasa123** [comment]
I think this isn't a significant user benefit today since the user gets to the content anyway? 

@JRussellHuffman, do you mind if we close this this?

**Comment by JRussellHuffman** [comment]
yep, closing.
