### ISSUE TITLE
Use Carbon Code Snippet component to reuse copy functionality

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#822]
Per offline conversation let's use the [Carbon Code Snippet component](http://vue.carbondesignsystem.com/?path=/story/components-cvcodesnippet--default) to implement the `SyntaxHighlight` component and so, taking advantage of copy functionality.

**Comment by pandasa123** [comment]
We have this functionally implemented and can close this issue

<img width="703" alt="Screenshot 2022-06-21 at 15 13 25" src="https://user-images.githubusercontent.com/6241840/174879787-be51cede-2cf8-4c7f-9ec6-16ecc04f2974.png">
