### ISSUE TITLE
Follow-up accordion component

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#830]
Follow-up of #792 .

When the carbon accordion component has a content bigger than 4 lines (more or less), the scroll is weird. We have this behavior on the overview page and we have checked it big increasing the text by hand on the [documentation page](https://www.carbondesignsystem.com/components/accordion/usage/)

**Comment by JRussellHuffman** [comment]
I think the ideal version is something like this: https://jqueryui.com/accordion/. It has a nice smooth transition and the active tab is highlighted. I’m not necessarily saying to import jquery-ui, but they do a surprisingly good job.

**Comment by y4izus** [comment]
We have enough space for our content, so we don't have this issue on our page. I close the issue
