### ISSUE TITLE
Images on the accordion component doesn't scale properly on small devices

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#833]
### Steps to reproduce the problem
Go to qiskit > overview on small devices

### What is the current behavior?
The image doesn't scale properly:
<img width="375" alt="Screen Shot 2020-08-13 at 11 53 04" src="https://user-images.githubusercontent.com/17231966/90120880-8e74c080-dd5b-11ea-8f93-ca32cc4f21cc.png">
<img width="378" alt="Screen Shot 2020-08-13 at 11 53 19" src="https://user-images.githubusercontent.com/17231966/90120903-97659200-dd5b-11ea-93d1-cf4d7e0cdd0a.png">

### What is the expected behavior?
Images scale properly:
<img width="131" alt="Screen Shot 2020-08-13 at 11 54 26" src="https://user-images.githubusercontent.com/17231966/90121024-bebc5f00-dd5b-11ea-9851-6e4d0625e482.png">

**Comment by delapuente** [comment]
Closed by #839
