### ISSUE TITLE
aqua page is not working

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#84]
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/15731369/52892348-98fecb80-315f-11e9-8b62-fc3239a5a207.png">

On Mac using firefox if i click on aqua it does not load.

**Comment by abdonrd** [comment]
Fixed by https://github.com/Qiskit/qiskit.org/commit/8db0300e1e467ba0eb9f86b9f8b0c8d925740511#diff-98d896d2173434dc860959ed43e91f49L286!
