### ISSUE TITLE
Add refactor issues for sprint in November

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#858]
In the spirit of #819, let's decide together about the criticality of the [code-quality issues](https://github.com/Qiskit/qiskit.org/issues?q=is%3Aissue+is%3Aopen+label%3Acode-quality). The goal of refactor sprints is to address the technical debt that is hurting the project most.

Let's add up to **10 x 👍** if we think the refactor solves an important problem and use up to **3 x ❤️** each of us for marking the issues we consider we should **absolutely address**.

**Comment by delapuente** [comment]
We have decided to delay the refactor sprint until Sep, 14th and use the next one as a decoration sprint.

**Comment by y4izus** [comment]
Just to clarify:
- Decoration sprint: 7th-18th, September
- Refactor sprint: 21st September - 2nd October

**Comment by y4izus** [comment]
Due to [this issue](https://github.com/Qiskit/qiskit.org/issues/1041) now we have refactor and enhance issues combined on code quality issues, so I have modified the link on the description
