### ISSUE TITLE
make a page for ignis

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#86]

**Comment by ajavadia** [comment]
@lerongil and @dcmckayibm will put a proposal here.

**Comment by carlosazaustre** [comment]
Pull Request #96 opened with the following look:
![image](https://user-images.githubusercontent.com/650752/53324090-384e5c00-38e0-11e9-9df7-5e9c67eba2a8.png)

**Comment by jaygambetta** [comment]
I think we need to tweak the content on the page. @dcmckayibm can you do this. But it looks good. @mtreinish will the qiskit ignis be part of qiskit mega on the first install?

**Comment by dcmckayibm** [comment]
The text/example is a little out of date since I gave the first draft, I'll update.

**Comment by dcmckayibm** [comment]
@carlosazaustre should I just post it here?

**Comment by carlosazaustre** [comment]
I think is Ok, it will be public so why not? :)

**Comment by mtreinish** [comment]
Yeah I think the plan was to push a new ``qiskit`` package release (likely 0.8.0) as soon as ignis is out. So when you install qiskit it will pull in ``qiskit-terra``, ``qiskit-aer``, and ``qiskit-ignis``. That being said I think the individual element package name will be ``qiskit-ignis`` not ``qiskit_ignis``.

**Comment by lerongil** [comment]
@dcmckayibm can we also shorten the tag line to one line to match the consistency of the other pages?

@carlosazaustre looks good, thanks!

**Comment by dcmckayibm** [comment]
@carlosazaustre I sent you some updated text/code via email

**Comment by carlosazaustre** [comment]
Thanks @dcmckayibm!
I just committed the last updates on #96
