### ISSUE TITLE
Research the mechanism for loading external content files in the overview section

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#860]

**Comment by y4izus** [comment]
There are [two ways of fetching content with `nuxt/content`](https://content.nuxtjs.org/fetching):
- Using `this.$content` when the Vue instance is initialized. Looking at the [nuxt lifecycle](https://nuxtjs.org/guides/concepts/nuxt-lifecycle) we can see that the hook `beforeCreated` is called when the Vue instance is initialized, so, this is the first hook where we could use `this.$content`. In [this](https://www.digitalocean.com/community/tutorials/vuejs-component-lifecycle) post we see the recommended hook for fetching data: `created`. This hook is executed both on the server and on the client, and each time we navigate via `<NuxtLink>`
- Using `context.$content` when `context` is available, that means for plugins, `asyncData`, `fetch`, `nuxtServerInit` and `middleware`. 
  - `asyncData` is executed one time on the server-side and the rest on the client. The result of `asyncData` is merged with `data`
  - `fetch` is deprecated => use `middleware` instead
  - `plugins`: Executed before initializing the root Vue Application
  - `middleware`: Executed before initializing the Vue instance. Called once on build time for static pages. Need a store to set the fetched data
  - `nuxtServerInit`: First lifecycle hook called from the server-side if the Vuex store is set.

We are not creating a [full static](https://nuxtjs.org/blog/going-full-static/) site yet, so the best option for fetching content to avoid several unnecessary calls is to use `middleware`. If we finally go full static, IMO `asyncData` will be the best option

**Comment by delapuente** [comment]
We are moving forward with this:
> We are not creating a [full static](https://nuxtjs.org/blog/going-full-static/) site yet, so the best option for fetching content to avoid several unnecessary calls is to use `middleware`. If we finally go full static, IMO `asyncData` will be the best option

So let's use `middleware` right now.

Thank you for your research @y4izus !
