### ISSUE TITLE
Review community page tab and ux of navigating between pages

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#862]
This issue is for how a user navigates to the events and advocates page under the community tab. Currently there is no "community" page that would serve as a landing page.

**Comment by lerongil** [comment]
This should also encompass the mobile version of the 2nd menu

**Comment by JRussellHuffman** [comment]
Some thoughts for this:
- will it need to scale to more pages?
- will other pages eventually need a second nav too
- do we need a community base page?

**Comment by JRussellHuffman** [comment]
Current designs being reviewed by the team.
![Screen Shot 2020-10-22 at 4 43 29 PM](https://user-images.githubusercontent.com/7633881/96933246-bc762f80-1485-11eb-9d0d-2d104afcee60.png)
