### ISSUE TITLE
Redesign of the learn section on the home page for small devices

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#881]
The design of the learn card has changed:

- Current design
<img width="314" alt="Screen Shot 2020-08-31 at 15 47 35" src="https://user-images.githubusercontent.com/17231966/91726946-4bab4900-eba1-11ea-8eb0-4693ee73a41e.png">

- New design
<img width="347" alt="Screen Shot 2020-08-31 at 15 48 16" src="https://user-images.githubusercontent.com/17231966/91727029-64b3fa00-eba1-11ea-86f7-d345f2a817da.png">

**Comment by y4izus** [comment]
@JRussellHuffman , should we implement the design as is right now on Figma or could we reuse the card component we have already created?

**Comment by pandasa123** [comment]
Learn page is [migrated](https://qiskit.org/learn/), we can close this issue
