### ISSUE TITLE
❤️ Identify and test critical components and functionality

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#885]
Some of our components (such as [TheQuickStart](https://github.com/Qiskit/qiskit.org/tree/master/components/landing/TheQuickStart) or [TheTableOfContents](https://github.com/Qiskit/qiskit.org/blob/1b4cd98d5da8ac7e3bdd0333631a3a8aa8c5c08e/components/overview/TheTableOfContents.vue)) are more than passive components markup; they encapsulate complex behaviour that should be [tested](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html).

Also, there is critical functionality regarding integration with the Events Airtable and other external content that should be also tested.

This task would improve the quality of our codebase.

**Comment by delapuente** [comment]
The codebase has remained with very basic tests for a very long time and now we start integrating more and more complex interaction, we should start thinking in testing the functionality in components, hooks, plug-ins and mixins. This would require to assess the current coverage, come up with a testing plan and implementing it.

**Comment by eddybrando** [comment]
This is now a duplicate of https://github.com/Qiskit/qiskit.org/issues/3372.
