### ISSUE TITLE
Implement line-animate some of our hero images

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#889]
Our hero images have this sketchy effect that would look awesome if combined with line animation like the following examples:

![X-BOX](https://i.imgur.com/DxGEiod.gif)

* https://cssdeck.com/labs/captain-america-shield-2
* https://tympanus.net/Development/SVGDrawingAnimation/index.html

**Comment by y4izus** [comment]
This issue is no longer relevant, so I close it
