### ISSUE TITLE
Shuffle letters animation on Qiskit pronunciation

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#890]
The Qiskit pronunciation shows "[quiss-kit]"/"[kiss-kit]" 50% of the time. Would be cool if we make some rolling-letters effect before it sets and displays the final pronunciation:

https://codepen.io/kkolasinski/pen/RGzdWp

**Comment by lerongil** [comment]
We decided that while this is a neat idea, the hero spot already has one animation and adding another may cause it to be a bit busy. In addition, we already have an effect on words and this would cause an inconsistent experience in qiskit.org.
