### ISSUE TITLE
❤️  Overview page asset optimization

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#898]
**Description**
Currently, the Overview images within the accordion components load fine on desktop, however on mobile phone, there's a delay in image rendering. 

Maybe we can check for potential optimization opportunities that would improve load times.

**Comment by delapuente** [comment]
Should look at this sooner than later. Rising its priority a bit.

**Comment by techtolentino** [comment]
Just double checked this to see if issue still exists.. it seems to perform better on my phone.
