### ISSUE TITLE
Prototype animation for typewriting effect

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#903]
Prototype typewriter effects.

Some considerations:
- is the animation "show/hide"?
- is the animation "writing itself out"?
- does the animation include the cursor.

Size: S

**Comment by JRussellHuffman** [comment]
First prototype for the typewriter effect here: https://www.figma.com/proto/kE5NsAbZlqOI0FQU86xsD9/typewriter?node-id=1%3A16151&viewport=-862%2C451%2C0.24102739989757538&scaling=min-zoom

Some thoughts regarding timing:
It pauses on a word for 2 seconds. Should it be longer?
It adds and removes letters one a time, taking .1 seconds per letter. It could be faster, but it will look less “typewriter-y” if it goes much faster.
there is a gap of .6 seconds where the RelevantWord is blank, before it starts typing a new word. I think this feels about right.

**Comment by delapuente** [comment]
@JRussellHuffman can we close this? At least, initial implementation has been merged in #913

**Comment by JRussellHuffman** [comment]
yes. closing.
