### ISSUE TITLE
Research different implementation approaches for typewritting effect

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#904]
Size: S

**Comment by y4izus** [comment]
I found different ways to implement the "Typewriter Effect":

| Using | Examples | ✅ | ❌ |
| --- | --- | --- | --- |
| Pure CSS3 | [Typewriter Effect with Pure CSS3](https://medium.com/@valentyn.vasylenko/typewriter-effect-with-alternating-text-in-pure-css3-72cf0c7e6c5) | WIP | The effect looks more like a smooth appearance of the letters than a typewriter<br/>Animating `width` can be expensive ([Animations and Performance](https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance?hl=en#css-vs-javascript-performance), [CSS Triggers](https://csstriggers.com/))<br/>More complicated to implement when we don't know all the alternative text in advance |
| JS without [Web Animation API](https://drafts.csswg.org/web-animations/) | [Typewriter Effect with JS 1](https://codepen.io/Coding_Journey/pen/BEMgbX)<br/>[Typewriter Effect with JS 2](https://codepen.io/gschier/pen/jkivt) | It's not a strict animation but a simulation just using JS, so it can be used in all browsers | WIP |
| CSS + JS | [Typewriter Effect with CSS + JS](https://codepen.io/lefourbefromage/pen/qBbZWEJ) | WIP | WIP |
| External library | [Typewriter Effect with TheaterJS](https://codepen.io/Zhouzi/pen/JoRazP) | WIP | WIP |
| SVG Text | [Typewriter Effect with SVG Text](https://codepen.io/tmrDevelops/pen/yyprGq) | WIP | WIP |

**Comment by techtolentino** [comment]
Hey @y4izus - this is awesome research... 

I looked at all of these yesterday and I agree with all of your notes.

There's a similar approach that I ran into, using a Vue component, and the JS implementation is very similar to the Typewriter Effect with JS 1, I believe.

| Using | Examples | ✅ | ❌ |
| --- | --- | --- | --- |
| CSS + JS (Vue component) | [vuejs-typeeffect](https://github.com/webnoobcodes/vuejs-typeeffect/blob/master/src/components/TypeEffect.vue) | Also nice effect<br/> Includes options for granular control<br/> Vue component ready |  |

**Comment by y4izus** [comment]
Yes @techtolentino ! it's quite similar, and it's the option I like the most 😄 . 

I think we are ready to implement the effect on #804, so I close this one.
