### ISSUE TITLE
As a Qiskit user, I want to discover Qiskit's extensions, so that I can learn about new functionality not covered by vanilla Qiskit.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#911]
The first pass of this will be done with issue #910 but this is a larger user story that will require additional thoughtfulness and organization including the criteria for which extensions get highlighted, where CTAs lead and how one interacts with all extensions.

**Comment by pandasa123** [comment]
The overview page captures this. We can close this issue out
