### ISSUE TITLE
Quantum Volume visuals

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#915]
Petar Jurcevic and a few others are looking to move forward with a visualization for quantum volume, possibly in connection with the textbook.

**Comment by JRussellHuffman** [comment]
final version of the first prototype is here:  https://www.figma.com/proto/QicY1yBT9hGP2Rln4Wu3Jn/915-quantum-volume-exploration?node-id=86%3A235&scaling=min-zoom

A lot of feedback has been shared and a second prototype needs to be made.

**Comment by lerongil** [comment]
Within this issue, I would also like to accomplish the following:

1. Continue pushing on edu platform 
2. Showing an example of a QL handoff 
3. Dev, Design and Edu collaboration
