### ISSUE TITLE
Usability research for textbook

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#918]
This issue is to track the progress of usability testing around the Qiskit Textbook. We hope to gather data to reinforce our decisions around the future of the textbook.

**Comment by delapuente** [comment]
Can you provide a little description of what is need to be done in the first comment?

**Comment by JRussellHuffman** [comment]
This work has been on hold due to licensing issues with user research tools. Should be picked back up next sprint.

**Comment by JRussellHuffman** [comment]
New sprint started but this is still on hold due to licensing issues :(
