### ISSUE TITLE
Site tabbing

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#919]
If a user is tabbing through the site, some buttons are skipped, and the order is a little off, depending on the browser.

**Comment by delapuente** [comment]
Sorry, I do not understand. What do you mean by "tabbing"?

**Comment by y4izus** [comment]
@JRussellHuffman , you mean moving through the buttons by clicking on the tab key, right?

**Comment by korgan00** [comment]
Yes, I detected that while testing accessibility things.
I also noticed that if the `<a>` tag has an empty href, the links/buttons are not skipped.
