### ISSUE TITLE
As a new member of the dev team, I want to get up to speed quickly, so I can start providing meaningful contributions quickly.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#923]
This user story encompasses the efforts for stablishing some procedures and documents now the team is growing, so new members can get up to the speed efficiently, reducing the dependence with other members of the team. It also seeks to gather the values of the people working in the project so they can act as a guiding star in the lack of more specific recommendations.

**Comment by pandasa123** [comment]
@Tansito, does the new onboarding documentation solve this issue?

**Comment by 1ucian0** [comment]
I think this can be closed by the new https://qisk.it/contribute , otherwise, reopen :)

**Comment by y4izus** [comment]
This is related with the workflow on our team (our onboarding, specifically), not with contributing to qiskit. I'm gonna reopen it

**Comment by y4izus** [comment]
Since we are not adding more features to this project, we can close this issue
