### ISSUE TITLE
As a member of the development team, I want my contributions to be as good as possible, so I deliver the most of the value without compromising code maintainability.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#924]
This user story encompasses the efforts of checking code quality automatically. Code reviews should focus on providing valuable human-insight, such as readability and understandability, and delegate on automatic tools as much as possible.

**Comment by pandasa123** [comment]
@eddybrando, I think we have tools like linters in our CI/CD that close out this issue?

**Comment by jackoconnordev** [comment]
I'd imagine the code of conduct covers the valuable human insight portion already too?

**Comment by eddybrando** [comment]
@y4izus we can probably close this, right?

**Comment by eddybrando** [comment]
I think that we can close this.

In general, we already have a CI/CD setup as @pandasa123 pointed out, and a code of conduct in place as @jackoconnordev pointed out.

CC: @y4izus
