### ISSUE TITLE
As a member of the dev team, I want to learn the team way of work and best practices, so I don't disrupt the regular functioning of the team

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#925]
This user story aims at formalizing some of the most frequent processes so we can set our development culture in a scalable, easy and predictive way the team and share knowledge about common challenges and situations.

**Comment by pandasa123** [comment]
@Tansito, same thing as #923 -- are dev processes covered in onboarding documentation?

**Comment by 1ucian0** [comment]
I think this can be closed by the new https://qisk.it/contribute , otherwise, reopen :)

**Comment by y4izus** [comment]
I think they are different things. This issue is intended to improve our workflow as a dev team, and you are pointing to the guidelines to contribute to qiskit. I'm gonna reopen it

**Comment by y4izus** [comment]
Since we are not adding more features to this project, we can close this issue
