### ISSUE TITLE
Assess the difficulty of changing the core UI from a development perspective

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#928]
Part of #782 

Explore official or unofficial ways of changing/extending Mathigon UI. Propose an example of how would it be to adapt Mathigon UI to our style, based on current design mocks. If there is no official way to do it, think of an extension mechanism enabling us to implement our requirements with reuse in mind.

**Comment by lerongil** [comment]
#928 and #929 seem to be duplicated

**Comment by delapuente** [comment]
Dup of #929
