### ISSUE TITLE
Assess the difficulty of consuming Jupyter Notebook format as the source for Mathigon content.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#931]
Part of #782

Explore the official or unofficial ways of converting formats different from Markdown into Mathigon content. If there is no official way to do it, think of an extension mechanism enabling us to consume Jupyter Notebook and other formats in a scalable way.

- [x] #939
- [x] #936

**Comment by vabarbosa** [comment]
an approach for consuming Jupyter notebooks in Mathigon includes:

- creating a [custom `nbconvert` exporter](https://nbconvert.readthedocs.io/en/latest/external_exporters.html)
- using the custom exporter convert notebooks to markdown format recognized by Mathigon 
- run Mathigon's parser/build against the exported markdown files to create site

this process works for a basic notebook without too much effort, but when thinking about support for widgets and incorporating Mathigon's custom markdown a notebook may need to include either or both

- writing custom Mathigon markdown in the notebook cells (knowing it may not render properly in Jupyter but should render as expected when converted and viewed from Mathigon server)
- adding additional metadata to the notebook cell for the custom exporter to make use of when exporting the notebook

this process could be leveraged to convert existing notebooks to Mathigon markdown, however, using the notebook as a format of choice for Mathigon does add additional work. updates such as creating new widgets will require work in Mathigon (to define/add new widget) and also in the custom exporter and/or notebook to properly handle the widget syntax.
