### ISSUE TITLE
Replace logo SVG in header and footer

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#932]
The logo in the header and the footer should be replaced with this version: https://ibm.box.com/s/ynxl9ykg75cxuckqnfe3hunzklkc4chv

**Comment by JRussellHuffman** [comment]
tagging @y4izus and @techtolentino

**Comment by y4izus** [comment]
@JRussellHuffman , could you give me access to the file? :)

**Comment by korgan00** [comment]
@JRussellHuffman Could you give access to the SVG?

**Comment by JRussellHuffman** [comment]
invites sent

**Comment by y4izus** [comment]
Thank you Russell!
