### ISSUE TITLE
Research official mechanism for UI overwrite

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#935]
Part of #929

**Comment by vabarbosa** [comment]
the recommended/documented approach for updating the theme/UI allows for:

- updating a course's primary color and/or main icon via the course's [`curriculum.yaml`](https://github.com/mathigon/textbooks/blob/master/curriculum.yaml)
- style changes (using LESS) to specific course content (e.g., [`styles.less`](https://github.com/mathigon/textbooks/blob/master/content/circles/styles.less))

for more in-depth changes or to completely overhaul the default layout, the ability to update/replace the styles and templates being served by the server would need to be made possible.

**Comment by delapuente** [comment]
@vabarbosa can you write a summary of your findings in #929? I'm assuming this done.
