### ISSUE TITLE
Create demo for consuming jupyter notebook files

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#936]
Part of #931

* Get the content translated into Mathigon HTML flavor.
* Implement a mechanism for embedding standard Mathigon widgets into Jupyter Notebooks.
* Implement a machanism for embedding custom widgets into Jupyter Notebooks.

**Comment by vabarbosa** [comment]
with the creation of a notebook extension it is possible to get the custom markdown to display properly in a Jupyter. the user could then just write some of the Jupyter content in the custom markdown. although it may not be straightforward for some widgets depending on their complexity. 

the work that has been started on the notebook extension could be leveraged to create a [custom `nbconvert` exporter](https://nbconvert.readthedocs.io/en/latest/external_exporters.html) that will convert the Jupyter notebook to the document format expected by Mathigon.

**Comment by delapuente** [comment]
Let's keep it open until we complete the exploration of that custom exporter.

**Comment by delapuente** [comment]
Done already. Nice work.
