### ISSUE TITLE
Research official mechanism other than markdown source formats

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#939]
Part of #931

**Comment by vabarbosa** [comment]
from my initial investigation, the recommended/documented approach for providing content for a course is via a [custom markdown](https://github.com/mathigon/textbooks/blob/master/docs/markdown.md) syntax.

the custom markdown is parsed using the [`@mathigon/parser`](https://github.com/mathigon/parser) into a JSON file (containing HTML fragments, etc.) that is consumed by the server.

while not documented, it is possible to replace the default parser with a custom one which could process a different source format (e.g., Jupyter notebook) into the specific JSON expected by the server. the expected JSON schema is currently not documented.

**Comment by delapuente** [comment]
We considered this done. Thank you @vabarbosa!
