### ISSUE TITLE
Create empty state card

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#945]
**Description**
On the Events page, the design calls for having an empty state card. This card should appear when there are no events that match the filtered criteria.

**Comment by delapuente** [comment]
I've removed the acceptance criteria for the task. If included, acceptance criteria should appear in the user story such as #381 or #383 and also act as a guide for what we should test.

Keep tasks as simple and informative as possible and rely on talking to the team for clarifying questions.
