### ISSUE TITLE
Redesign documentation components

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#947]
This issue is to look over the documentation pages and take note of all the the components being used (eg. accordions, tables, etc) and redesign them to match our visual system.

**Comment by nonhermitian** [comment]
There is already a Sphinx template for Qiskit: https://github.com/Qiskit/qiskit_sphinx_theme

You can help with that if so desired.

**Comment by JRussellHuffman** [comment]
Thanks, I saw the new live version. We're discussing how to best build off of that work.

**Comment by JRussellHuffman** [comment]
components have been migrated to the main figma file under "documentation" here: https://www.figma.com/file/PDbN8wcg5WteWVvinjAEUv/qiskit.org-main-file?node-id=2%3A1930

**Comment by JRussellHuffman** [comment]
This is done for now. If/when further design work is needed during implementation, I will create a new issue.
