### ISSUE TITLE
Create component for filters list

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#950]
**Description**
We should be able to reuse the filters list component that is used on both the Events and Learn pages. This task would be to abstract the commonalities and create a component that can be leveraged in both use cases.

Potential refactor story

**Comment by eddybrando** [comment]
@techtolentino, @y4izus, isn't this a duplicate or at least very similar to https://github.com/Qiskit/qiskit.org/issues/944?

**Comment by korgan00** [comment]
I think #944 refactor should include this one.

**Comment by y4izus** [comment]
In my opinion, we can do it separately, but we should do #944 first and this one after

**Comment by techtolentino** [comment]
No longer relevant with new Learn page designs
