### ISSUE TITLE
Provide the list of words for the events page header

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#952]
The typewriter effect shows several words, but now we only have one for the events page header. The complete list of words is needed

**Comment by delapuente** [comment]
Let's remove the high priority tag since there is still time until the end of the sprint.

@lerongil for when you have a moment, please. I think this is a question for you.

**Comment by techtolentino** [comment]
Following [this conversation](https://ibm-quantumcomputing.slack.com/archives/GNJ1PAM0E/p1601560703007100) in our team's internal Slack channel, we will be using a list of words that can be used, related to "events", and not "largest".

Potential list of words, based on event types:
"events"
"hackathons"
"camps"
"unconferences"
"talks"

**Comment by lerongil** [comment]
This is a good idea and the list looks good to me!
