### ISSUE TITLE
Consistent spacing between Learn and Events page (on mobile)

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#963]
### Steps to reproduce the problem
On a mobile device, visit the Learn page, then visit the Events page.

### What is the current behavior?
You'll see the left and right spacing (padding or margin) is different.

### What is the expected behavior?
Consistent spacing on both pages.

![learn-page](https://user-images.githubusercontent.com/6276074/94841694-a53ca880-03d7-11eb-8f2f-f44a95efb1be.png)

![events-page](https://user-images.githubusercontent.com/6276074/94841702-a7066c00-03d7-11eb-93bb-797c9535abd0.png)

**Comment by y4izus** [comment]
I reopen the issue because I thought it was related to the content inside the card, but it's related with the page content itself
