### ISSUE TITLE
Investigate header animation on mobile

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#964]
We need to ensure that the animated header (typewriting effect) does not introduce unwanted shifts in the layout, due to some strings being longer than others.

**Comment by eddybrando** [comment]
@techtolentino, I believe this may be a duplicate of https://github.com/Qiskit/qiskit.org/issues/920.

**Comment by delapuente** [comment]
Indeed, this is covered by #920. Closing.
