### ISSUE TITLE
❤️👍👍👍   Use Carbon themes and customize it to match visual identity

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#965]
Since all of the pages have moved to the light theme, we need to modify the `community-theme.scss` file to match our visual branding.

This work is the follow-up for the suggestion mentioned [here](https://github.com/Qiskit/qiskit.org/pull/951#discussion_r495666584).

**Comment by korgan00** [comment]
I think this may be related to #703

**Comment by eddybrando** [comment]
We are currently importing some styles in the layouts to overwrite the dark styles, which are no longer the default. So we should reorder this.

Also, this is a good opportunity to look deeper into the copy / typography styles that need to be imported individually in various components to avoid FOUT, as suggested offline by @y4izus.

**Comment by delapuente** [comment]
>> Also, this is a good opportunity to look deeper into the copy / typography styles that need to be imported individually in various components to avoid FOUT, as suggested offline by @y4izus.

Is there an issue for this specific part?
