### ISSUE TITLE
❤️👍👍   Unified and refactor links, ctas, and buttons

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#973]
We have different ways to "link" to another page:

- Basic links
<img width="403" alt="Screen Shot 2020-10-06 at 13 33 44" src="https://user-images.githubusercontent.com/17231966/95196663-ab1bfa80-07d8-11eb-86a9-a4cf3efc76e9.png">

- Basic links on dark page:
<img width="465" alt="Screen Shot 2020-10-19 at 15 42 22" src="https://user-images.githubusercontent.com/17231966/96458837-b122ca00-1221-11eb-9cc0-928afee53689.png">

- Footer links
<img width="289" alt="Screen Shot 2020-10-06 at 13 35 10" src="https://user-images.githubusercontent.com/17231966/95196750-cdae1380-07d8-11eb-90aa-8e2965f6b40f.png">

- Ctas = Links with dynamic icon
<img width="227" alt="Screen Shot 2020-10-06 at 13 36 16" src="https://user-images.githubusercontent.com/17231966/95196827-eb7b7880-07d8-11eb-9d51-e161b0b479a3.png">
<img width="164" alt="Screen Shot 2020-10-06 at 13 36 39" src="https://user-images.githubusercontent.com/17231966/95196852-f8986780-07d8-11eb-9754-71dc1a2596c3.png">

- Landing cta (primary) = Style like a button and always have an arrow (even if it's a external link)
<img width="295" alt="Screen Shot 2020-10-06 at 13 38 26" src="https://user-images.githubusercontent.com/17231966/95197021-385f4f00-07d9-11eb-9ce4-46d32539c51e.png">

- Landing cta (secondary) = Style like a button and always have an arrow (even if it's a external link)
<img width="265" alt="Screen Shot 2020-10-06 at 13 39 00" src="https://user-images.githubusercontent.com/17231966/95197069-4ca34c00-07d9-11eb-8e46-a05f69cc29c3.png">

- Ctas with button style
<img width="192" alt="Screen Shot 2020-10-06 at 13 39 38" src="https://user-images.githubusercontent.com/17231966/95197117-62b10c80-07d9-11eb-949a-7feb75712be8.png">

We should try to refactor these components in order to reuse them properly and to avoid the use of the `!important` CSS property in the last one.

Also, we should clarify with design if the Landings cta should have always an arrow and which elements should have the on hover effect

**Comment by y4izus** [comment]
Per offline conversations:
- Basic links without the underline but with different purple for dark and light themes
- Footer links remain the same
- Ctas with purple background = primary buttons
- Ctas with gray background = secondary buttons
- Ctas with transparent background = [ghost buttons](https://www.carbondesignsystem.com/components/button/usage)

**Comment by delapuente** [comment]
@y4izus can we mark this as decided or is the conversation still going on?

**Comment by y4izus** [comment]
Is still going on, I found more differences, and I'm going to create a document and with it, come back to Russell and discuss again

**Comment by y4izus** [comment]
There are a lot of versions, so I've created a [document](https://ibm.ent.box.com/integrations/officeonline/openOfficeOnline?fileId=735549570881&wdPid=f33ca55) to try to summarize them and find what they have in common. Feel free to include/modify what you want

**Comment by JRussellHuffman** [comment]
@y4izus let me know if there is anything else you need from the design story over in #1120
