### ISSUE TITLE
Ensure we have all designs for the dark page

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#975]
Currently, we have dark page designs at the larger screens only - we'll need to work with design to strategize the layout/experience for other screens.

Design considerations:
- how the header looks on smaller screens
- order of stacking elements in intro
- how do we handle the ui (scroll feature)
- feature cards on smaller screens
- keep in touch content stacking

**Comment by techtolentino** [comment]
@delapuente @y4izus @korgan00 

Hello - I wanted to summarize the conversation that Russell and I had on Monday afternoon.


**Note**: the designs that Russell in **Latest Version 2020-10-07** page, in Figma, will be the most recent.

**Header**
- the header has been updated with a new hero and background image
- the background grid image is the full image
- the line leading to the focus (within image) is different now (it has a wave and larger focal point)

**Video section**
- we just discussed the stacking order and how it looks at medium and small screens (designs are updated)

**Fake UI**
- Russell updated the fake ui to look like a little more real
- we'll still the scrolling interactions as planned, so no research effort should be wasted

**Feature section**
- the Feature section remained the same as original design
- although, it _is_ possible the images could change (from photos to more sketch-look)
- we discussed modals, and Russell agreed that we don't really need one yet

**Keep in touch section**
- more content
- added an illustration
- discussed how image displays at different breakpoints (only shows on large breakpoints and up)


Lastly, I'm learning (after typing this) that this ☝️ isn't the best way to review my discussion with Design, so in the future, I'll most likely schedule follow-up meetings if there's any discussion or updates, during your off-hours.


@JRussellHuffman - (tagging you for visibility and for a sanity-check if I missed anything)
