### ISSUE TITLE
Research how the "dark theme" can be implemented

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#984]
In the Metal page, we come up with a quick and effective solution for implementing a dark theme although further research for alternatives is needed.

**Comment by techtolentino** [comment]
@korgan00 - I think the dark footer is already being handled in https://github.com/Qiskit/qiskit.org/pull/987, right?

**Comment by techtolentino** [comment]
@delapuente - would this research involve something more than what Yaiza's already done for the dark page?

If so, would this need to be a refactor story?

**Comment by pandasa123** [comment]
This is in the navbar design. I think we can close out this issue since we've investigated it and come up with a great design to implement? 

CC: @techtolentino

**Comment by techtolentino** [comment]
@pandasa123 - good catch... this has been _investigated_ and even partially implemented on the Textbook side. I don't think much investigation is needed at this point.

Closing for now.
